export const HERO_JOB_LOCALIZATION_PART_6 = [
  [1009, { nameCn: "变化姬", nameKr: "쉐이프 시프터", status: "CONFIRMED_KR" }],
  [1010, { nameCn: "幻影魔姬", nameKr: "미라지 퀸", status: "CONFIRMED_KR" }],
  [1011, { nameCn: "血妖", nameKr: "블러드 밴시", status: "CONFIRMED_KR" }],
  [1012, { nameCn: "魔将", nameKr: "데몬 제네럴", status: "CONFIRMED_KR" }],
  [1013, { nameCn: "血伶人", nameKr: "블러드 마스터", status: "CONFIRMED_KR" }],
  [1014, { nameCn: "魔神", nameKr: "마신", status: "CONFIRMED_KR" }],
  [1015, { nameCn: "血魔姬", nameKr: "블러드 엠프레스", status: "CONFIRMED_KR" }],
  [1016, { nameCn: "茶会之主", nameKr: "다과회 주인", status: "CONFIRMED_KR" }],
  [1017, { nameCn: "歼灭天使", nameKr: "섬멸천사", status: "CONFIRMED_KR" }],
  [1018, { nameCn: "混血魔裔", nameKr: "마족의 후예", status: "CONFIRMED_KR" }],
  [1019, { nameCn: "魔界王选", nameKr: "마족의 왕", status: "CONFIRMED_KR" }],
  [1020, { nameCn: "魔界之焰", nameKr: "마계의 불꽃", status: "CONFIRMED_KR" }],
  [1021, { nameCn: "邪王炎杀", nameKr: "사왕염살", status: "CONFIRMED_KR" }],
  [1022, { nameCn: "魔界盗贼", nameKr: "마계 도적", status: "CONFIRMED_KR" }],
  [1023, { nameCn: "妖狐转生", nameKr: "요호의 환생", status: "CONFIRMED_KR" }],
  [1024, { nameCn: "前世之力", nameKr: "전생의 힘", status: "CONFIRMED_KR" }],
  [1025, { nameCn: "力·80%", nameKr: "파워 80%", status: "CONFIRMED_KR" }],
  [1026, { nameCn: "力·100%", nameKr: "파워 100%", status: "CONFIRMED_KR" }],
  [1027, { nameCn: "魔神使", nameKr: "마신의 종복", status: "CONFIRMED_KR" }],
  [1028, { nameCn: "魔王化身", nameKr: "마왕의 화신", status: "CONFIRMED_KR" }],
  [1029, { nameCn: "死灵法师", nameKr: "엘더 리치", status: "CONFIRMED_KR" }],
  [1030, { nameCn: "死之统治者", nameKr: "오버로드", status: "CONFIRMED_KR" }],
  [1031, { nameCn: "血族", nameKr: "혈족", status: "CONFIRMED_KR" }],
  [1032, { nameCn: "吸血鬼", nameKr: "뱀파이어", status: "CONFIRMED_KR" }],
  [1033, { nameCn: "真祖", nameKr: "진조", status: "CONFIRMED_KR" }],
  [1034, { nameCn: "护卫魔骑", nameKr: "언홀리 나이트", status: "CONFIRMED_KR" }],
  [1035, { nameCn: "暗黑骑士", nameKr: "다크 나이트", status: "CONFIRMED_KR" }],
  [1036, { nameCn: "魔晶浪客", nameKr: "마수정의 낭인", status: "CONFIRMED_KR" }],
  [1037, { nameCn: "邪神之翼", nameKr: "사신의 날개", status: "CONFIRMED_KR" }],
  [1038, { nameCn: "邪术师", nameKr: "사술사", status: "CONFIRMED_KR" }],
  [1039, { nameCn: "邪灵", nameKr: "사령", status: "CONFIRMED_KR" }],
  [1040, { nameCn: "邪神", nameKr: "사신", status: "CONFIRMED_KR" }],
  [1041, { nameCn: "影妖", nameKr: "레이더", status: "CONFIRMED_KR" }],
  [1042, { nameCn: "月影魔使", nameKr: "달그림자의 마술사", status: "CONFIRMED_KR" }],
  [1043, { nameCn: "循梦者", nameKr: "꿈을 쫓는 자", status: "CONFIRMED_KR" }],
  [1044, { nameCn: "魔剑使者", nameKr: "데몬 스워드", status: "CONFIRMED_KR" }],
  [1045, { nameCn: "魔剑素体", nameKr: "마검의 클론", status: "CONFIRMED_KR" }],
  [1046, { nameCn: "终极素体", nameKr: "궁극의 클론", status: "CONFIRMED_KR" }],
  [1047, { nameCn: "夷灭者", nameKr: "섬멸자", status: "CONFIRMED_KR" }],
  [1048, { nameCn: "全世之坏灭", nameKr: "속세의 종언", status: "CONFIRMED_KR" }],
  [1049, { nameCn: "暗之子", nameKr: "어둠의 부산물", status: "CONFIRMED_KR" }],
  [1050, { nameCn: "混沌裂影", nameKr: "혼돈의 그림자", status: "CONFIRMED_KR" }],
  [1051, { nameCn: "混沌代行者", nameKr: "혼돈의 대행자", status: "CONFIRMED_KR" }],
  [1052, { nameCn: "黑暗画师", nameKr: "어둠의 화가", status: "CONFIRMED_KR" }],
  [1053, { nameCn: "断末魔之主", nameKr: "단말마의 주인", status: "CONFIRMED_KR" }],
  [1054, { nameCn: "宵暗之女", nameKr: "옅은 어둠의 여자", status: "CONFIRMED_KR" }],
  [1055, { nameCn: "辉黯使者", nameKr: "빛과 어둠의 사자", status: "CONFIRMED_KR" }],
  [1056, { nameCn: "魔域源核", nameKr: "마역 코어", status: "CONFIRMED_KR" }],
  [1057, { nameCn: "魔能机器", nameKr: "마력 메카", status: "CONFIRMED_KR" }],
  [1058, { nameCn: "死灵之械", nameKr: "데스 메카닉", status: "CONFIRMED_KR" }],
  [1059, { nameCn: "魔剑精灵", nameKr: "마검의 정령", status: "CONFIRMED_KR" }],
  [1060, { nameCn: "魔剑具象", nameKr: "알하자드 형상", status: "CONFIRMED_KR" }],
  [1061, { nameCn: "死灵唤师", nameKr: "사령 소환사", status: "CONFIRMED_KR" }],
  [1062, { nameCn: "死灵君王", nameKr: "사령의 군왕", status: "CONFIRMED_KR" }],
  [1063, { nameCn: "魔装鬼", nameKr: "마장귀", status: "CONFIRMED_KR" }],
  [1064, { nameCn: "黎之魔王", nameKr: "그렌델", status: "CONFIRMED_KR" }],
  [1065, { nameCn: "深渊使徒", nameKr: "심연의 사도", status: "CONFIRMED_KR" }],
  [1066, { nameCn: "渊狱召现者", nameKr: "지옥 소환자", status: "CONFIRMED_KR" }],
  [1067, { nameCn: "深渊之影", nameKr: "심연의 그림자", status: "CONFIRMED_KR" }],
  [1068, { nameCn: "黯蚀凶源", nameKr: "검은 침식의 근원", status: "CONFIRMED_KR" }],
  [1069, { nameCn: "终焉之神降", nameKr: "종말 신의 강림", status: "CONFIRMED_KR" }],
  [1070, { nameCn: "白鬃勇者", nameKr: "흰 갈기의 용사", status: "CONFIRMED_KR" }],
  [1071, { nameCn: "月狼首领", nameKr: "월랑 두목", status: "CONFIRMED_KR" }],
  [1072, { nameCn: "白狼王", nameKr: "백랑 왕", status: "CONFIRMED_KR" }],
  [1073, { nameCn: "原初造物", nameKr: "원초의 피조물", status: "CONFIRMED_KR" }],
  [1074, { nameCn: "兽神之首", nameKr: "조아로드", status: "CONFIRMED_KR" }],
  [1075, { nameCn: "孤高的超王", nameKr: "고고한 초왕", status: "CONFIRMED_KR" }],
  [1076, { nameCn: "流浪者", nameKr: "방랑자", status: "CONFIRMED_KR" }],
  [1077, { nameCn: "涤恶使徒", nameKr: "멸악의 사도", status: "CONFIRMED_KR" }],
  [1078, { nameCn: "光暗主宰", nameKr: "빛과 어둠의 지배자", status: "CONFIRMED_KR" }],
  [1079, { nameCn: "破灭者", nameKr: "파멸자", status: "CONFIRMED_KR" }],
  [1080, { nameCn: "炎狱使徒", nameKr: "염옥의 사도", status: "CONFIRMED_KR" }],
  [1081, { nameCn: "炎狱掌控者", nameKr: "염옥의 지배자", status: "CONFIRMED_KR" }],
  [1082, { nameCn: "匣梦之堕", nameKr: "타락한 꿈 상자", status: "CONFIRMED_KR" }],
  [1083, { nameCn: "匣梦枭魔", nameKr: "상자 속 악마", status: "CONFIRMED_KR" }],
  [1084, { nameCn: "始祖妖精", nameKr: "태초의 엘프", status: "CONFIRMED_KR" }],
  [1085, { nameCn: "梦之统领", nameKr: "꿈의 지도자", status: "CONFIRMED_KR" }],
  [1086, { nameCn: "梦之女王", nameKr: "꿈의 여왕", status: "CONFIRMED_KR" }],
  [1087, { nameCn: "解放者", nameKr: "해방자", status: "CONFIRMED_KR" }],
  [1088, { nameCn: "碎刃战皇", nameKr: "전쟁의 황제", status: "CONFIRMED_KR" }],
  [1089, { nameCn: "锥心者", nameKr: "심장 관통자", status: "CONFIRMED_KR" }],
  [1090, { nameCn: "诡影邪姬", nameKr: "그림자의 마녀", status: "CONFIRMED_KR" }],
  [1091, { nameCn: "攫命惑心者", nameKr: "유혹의 살인자", status: "CONFIRMED_KR" }],
  [1092, { nameCn: "狂笑人偶", nameKr: "광소의 인형", status: "CONFIRMED_KR" }],
  [1093, { nameCn: "灾厄神偶", nameKr: "재앙의 인형", status: "CONFIRMED_KR" }],
  [1094, { nameCn: "复仇者", nameKr: "어벤져", status: "CONFIRMED_KR" }],
  [1095, { nameCn: "堕魂之刃", nameKr: "타락한 영혼의 검", status: "CONFIRMED_KR" }],
  [1096, { nameCn: "永夜之王", nameKr: "영원한 밤의 왕", status: "CONFIRMED_KR" }],
  [1098, { nameCn: "衰败祸根", nameKr: "쇠락의 화근", status: "CONFIRMED_KR" }],
  [1099, { nameCn: "毁灭之具象", nameKr: "파멸의 실체", status: "CONFIRMED_KR" }],
  [1101, { nameCn: "暗杀者", nameKr: "밴디트", status: "CONFIRMED_KR" }],
  [1102, { nameCn: "忍者", nameKr: "닌자", status: "CONFIRMED_KR" }],
  [1103, { nameCn: "突击者", nameKr: "라이더", status: "CONFIRMED_KR" }],
  [1104, { nameCn: "影", nameKr: "쉐도우", status: "CONFIRMED_KR" }],
  [1105, { nameCn: "大统帅", nameKr: "하이 마스터", status: "CONFIRMED_KR" }],
  [1106, { nameCn: "漆黑之牙", nameKr: "칠흑의 송곳니", status: "CONFIRMED_KR" }],
  [1107, { nameCn: "执行者", nameKr: "집행자", status: "CONFIRMED_KR" }],
  [1108, { nameCn: "漆黑魅影", nameKr: "다크 팬텀", status: "CONFIRMED_KR" }],
  [1109, { nameCn: "魔界忍者", nameKr: "마계 도적", status: "CONFIRMED_KR" }],
  [1110, { nameCn: "冰河忌子", nameKr: "빙하국의 저주받은 아이", status: "CONFIRMED_KR" }],
  [1111, { nameCn: "邪眼师", nameKr: "사안사", status: "CONFIRMED_KR" }],
] as const;
