export const HERO_JOB_LOCALIZATION_PART_5 = [
  [802, { nameCn: "修女", nameKr: "시스터", status: "CONFIRMED_KR" }],
  [803, { nameCn: "主教", nameKr: "주교", status: "CONFIRMED_KR" }],
  [804, { nameCn: "圣骑士", nameKr: "팔라딘", status: "CONFIRMED_KR" }],
  [805, { nameCn: "圣徒", nameKr: "마터", status: "CONFIRMED_KR" }],
  [806, { nameCn: "司祭", nameKr: "프리스트", status: "CONFIRMED_KR" }],
  [807, { nameCn: "圣女", nameKr: "세인트", status: "CONFIRMED_KR" }],
  [808, { nameCn: "神使", nameKr: "오라클", status: "CONFIRMED_KR" }],
  [809, { nameCn: "圣骑统帅", nameKr: "템플러", status: "CONFIRMED_KR" }],
  [810, { nameCn: "圣者", nameKr: "세인트", status: "CONFIRMED_KR" }],
  [811, { nameCn: "先知", nameKr: "프로핏", status: "CONFIRMED_KR" }],
  [812, { nameCn: "女武神", nameKr: "발키리", status: "CONFIRMED_KR" }],
  [813, { nameCn: "公主", nameKr: "프린세스", status: "CONFIRMED_KR" }],
  [814, { nameCn: "圣女骑士", nameKr: "세인트 나이트", status: "CONFIRMED_KR" }],
  [815, { nameCn: "神官骑士", nameKr: "홀리 나이트", status: "CONFIRMED_KR" }],
  [816, { nameCn: "传令官", nameKr: "헤럴드", status: "CONFIRMED_KR" }],
  [817, { nameCn: "战修女", nameKr: "워 프리스티스", status: "CONFIRMED_KR" }],
  [818, { nameCn: "王女", nameKr: "프린세스", status: "CONFIRMED_KR" }],
  [819, { nameCn: "皇家特使", nameKr: "로열 엔보이", status: "CONFIRMED_KR" }],
  [820, { nameCn: "利贝尔公主", nameKr: "리벨 공주", status: "CONFIRMED_KR" }],
  [821, { nameCn: "利贝尔女王", nameKr: "리벨 여왕", status: "CONFIRMED_KR" }],
  [822, { nameCn: "树语者", nameKr: "클레릭", status: "CONFIRMED_KR" }],
  [823, { nameCn: "木贤者", nameKr: "아바탈", status: "CONFIRMED_KR" }],
  [824, { nameCn: "学者", nameKr: "학자", status: "CONFIRMED_KR" }],
  [825, { nameCn: "智士", nameKr: "책사", status: "CONFIRMED_KR" }],
  [826, { nameCn: "军师", nameKr: "군사", status: "CONFIRMED_KR" }],
  [827, { nameCn: "千金小姐", nameKr: "백작의 딸", status: "CONFIRMED_KR" }],
  [828, { nameCn: "梦幻之吻", nameKr: "초능력 소녀", status: "CONFIRMED_KR" }],
  [829, { nameCn: "圣剑精灵", nameKr: "성검의 정령", status: "CONFIRMED_KR" }],
  [830, { nameCn: "圣剑公主", nameKr: "성검의 공주", status: "CONFIRMED_KR" }],
  [831, { nameCn: "灵能者", nameKr: "영능력 소년", status: "CONFIRMED_KR" }],
  [832, { nameCn: "灵界侦探", nameKr: "영계탐정", status: "CONFIRMED_KR" }],
  [833, { nameCn: "使徒", nameKr: "사도", status: "CONFIRMED_KR" }],
  [834, { nameCn: "黑色圣徒", nameKr: "다크 필그림", status: "CONFIRMED_KR" }],
  [835, { nameCn: "影依圣女", nameKr: "다크 세인트", status: "CONFIRMED_KR" }],
  [836, { nameCn: "银之启动者", nameKr: "은의 기동자", status: "CONFIRMED_KR" }],
  [837, { nameCn: "钢之圣女", nameKr: "강철의 성녀", status: "CONFIRMED_KR" }],
  [838, { nameCn: "银骑士", nameKr: "실버 나이트", status: "CONFIRMED_KR" }],
  [839, { nameCn: "银骑统帅", nameKr: "백은의 발키리", status: "CONFIRMED_KR" }],
  [840, { nameCn: "大贤者", nameKr: "대현자", status: "CONFIRMED_KR" }],
  [842, { nameCn: "布道师", nameKr: "전도사", status: "CONFIRMED_KR" }],
  [843, { nameCn: "灵光圣女", nameKr: "영광의 성녀", status: "CONFIRMED_KR" }],
  [844, { nameCn: "圣职者", nameKr: "성직자", status: "CONFIRMED_KR" }],
  [845, { nameCn: "虔信者", nameKr: "신앙인", status: "CONFIRMED_KR" }],
  [846, { nameCn: "异端裁决者", nameKr: "인퀴지터", status: "CONFIRMED_KR" }],
  [847, { nameCn: "圣术士", nameKr: "홀리 메이지", status: "CONFIRMED_KR" }],
  [848, { nameCn: "赐圣僧侣", nameKr: "홀리 프리스트", status: "CONFIRMED_KR" }],
  [849, { nameCn: "血晶传人", nameKr: "핏빛 수정의 전승자", status: "CONFIRMED_KR" }],
  [850, { nameCn: "血晶支配者", nameKr: "핏빛 수정의 지배자", status: "CONFIRMED_KR" }],
  [851, { nameCn: "仁斗士", nameKr: "투사 료", status: "CONFIRMED_KR" }],
  [852, { nameCn: "烈火之仁", nameKr: "열화의 료", status: "CONFIRMED_KR" }],
  [853, { nameCn: "智影者", nameKr: "지장", status: "CONFIRMED_KR" }],
  [854, { nameCn: "天空之智", nameKr: "천공의 지", status: "CONFIRMED_KR" }],
  [855, { nameCn: "神女", nameKr: "수호신의 딸", status: "CONFIRMED_KR" }],
  [856, { nameCn: "净地末裔", nameKr: "카오스의 후예", status: "CONFIRMED_KR" }],
  [857, { nameCn: "大主教", nameKr: "대주교", status: "CONFIRMED_KR" }],
  [859, { nameCn: "超越者", nameKr: "초월자", status: "CONFIRMED_KR" }],
  [860, { nameCn: "创生者", nameKr: "창조자", status: "CONFIRMED_KR" }],
  [861, { nameCn: "万灵之初诞", nameKr: "모든 영혼의 시조", status: "CONFIRMED_KR" }],
  [862, { nameCn: "亲卫队长", nameKr: "친위대장", status: "CONFIRMED_KR" }],
  [863, { nameCn: "眼镜之主", nameKr: "안경이 본체", status: "CONFIRMED_KR" }],
  [865, { nameCn: "自然通联者", nameKr: "자연의 공명자", status: "CONFIRMED_KR" }],
  [866, { nameCn: "原初祈求者", nameKr: "태초의 기도사", status: "CONFIRMED_KR" }],
  [867, { nameCn: "方舟宰相", nameKr: "방주 재상", status: "CONFIRMED_KR" }],
  [868, { nameCn: "方舟总帅", nameKr: "방주 총사령관", status: "CONFIRMED_KR" }],
  [869, { nameCn: "修道者", nameKr: "수도사", status: "CONFIRMED_KR" }],
  [870, { nameCn: "灵宗长老", nameKr: "영종 장로", status: "CONFIRMED_KR" }],
  [871, { nameCn: "灵宗首席", nameKr: "영종의 지도자", status: "CONFIRMED_KR" }],
  [872, { nameCn: "唤灵斗者", nameKr: "환령 투사", status: "CONFIRMED_KR" }],
  [873, { nameCn: "驱灵尊者", nameKr: "소울마스터 존자", status: "CONFIRMED_KR" }],
  [874, { nameCn: "月咏师", nameKr: "달의 시인", status: "CONFIRMED_KR" }],
  [875, { nameCn: "月之贤人", nameKr: "달의 현인", status: "CONFIRMED_KR" }],
  [876, { nameCn: "舞者", nameKr: "무도가", status: "CONFIRMED_KR" }],
  [877, { nameCn: "战颂舞姬", nameKr: "전쟁의 무희", status: "CONFIRMED_KR" }],
  [879, { nameCn: "保卫者", nameKr: "수호자", status: "CONFIRMED_KR" }],
  [880, { nameCn: "守护者", nameKr: "수호자", status: "CONFIRMED_KR" }],
  [881, { nameCn: "圣护使徒", nameKr: "신성의 사도", status: "CONFIRMED_KR" }],
  [882, { nameCn: "先灵信徒", nameKr: "선령의 신도", status: "CONFIRMED_KR" }],
  [883, { nameCn: "触灵行者", nameKr: "소울 워커", status: "CONFIRMED_KR" }],
  [884, { nameCn: "慈悲者", nameKr: "자비로운 자", status: "CONFIRMED_KR" }],
  [885, { nameCn: "未世的祈颂", nameKr: "미래의 송가", status: "CONFIRMED_KR" }],
  [886, { nameCn: "彼端异客", nameKr: "낯선 손님", status: "CONFIRMED_KR" }],
  [887, { nameCn: "圣扉之钥", nameKr: "성문의 열쇠", status: "CONFIRMED_KR" }],
  [888, { nameCn: "辉剑使", nameKr: "빛의 검 사역자", status: "CONFIRMED_KR" }],
  [889, { nameCn: "圣辉使徒", nameKr: "성휘의 사도", status: "CONFIRMED_KR" }],
  [890, { nameCn: "辉耀的圣裁", nameKr: "성스러운 빛의 심판관", status: "CONFIRMED_KR" }],
  [891, { nameCn: "尘封者", nameKr: "먼지를 덮어쓴 자", status: "CONFIRMED_KR" }],
  [892, { nameCn: "贯时神珀", nameKr: "시간을 달리는 자", status: "CONFIRMED_KR" }],
  [893, { nameCn: "彼端异客", nameKr: "낯선 손님", status: "CONFIRMED_KR" }],
  [894, { nameCn: "命扉圣者", nameKr: "운명의 문 수호자", status: "CONFIRMED_KR" }],
  [895, { nameCn: "求索者", nameKr: "탐색자", status: "CONFIRMED_KR" }],
  [896, { nameCn: "格致者", nameKr: "탐구자", status: "CONFIRMED_KR" }],
  [897, { nameCn: "圣契者", nameKr: "신성 계약자", status: "CONFIRMED_KR" }],
  [898, { nameCn: "光辉圣徒", nameKr: "빛의 신성 사도", status: "CONFIRMED_KR" }],
  [899, { nameCn: "见习修女", nameKr: "견습 시스터", status: "CONFIRMED_KR" }],
  [902, { nameCn: "黑暗法师", nameKr: "다크 메이지", status: "CONFIRMED_KR" }],
  [903, { nameCn: "黑暗王子", nameKr: "다크 프린스", status: "CONFIRMED_KR" }],
  [1002, { nameCn: "死神", nameKr: "데스", status: "CONFIRMED_KR" }],
  [1003, { nameCn: "死神领主", nameKr: "데스 로드", status: "CONFIRMED_KR" }],
  [1006, { nameCn: "魔剑使者", nameKr: "데몬 스워드", status: "CONFIRMED_KR" }],
  [1007, { nameCn: "混沌化身", nameKr: "디스오더", status: "CONFIRMED_KR" }],
  [1008, { nameCn: "变化使", nameKr: "모프", status: "CONFIRMED_KR" }],
] as const;
