export const HERO_JOB_LOCALIZATION_PART_2 = [
  [260, { nameCn: "剑之使者", nameKr: "검의 사자", status: "CONFIRMED_KR" }],
  [261, { nameCn: "剑之传承", nameKr: "검의 계승자", status: "CONFIRMED_KR" }],
  [263, { nameCn: "翼剑士", nameKr: "천상의 검사", status: "CONFIRMED_KR" }],
  [264, { nameCn: "翔空剑士", nameKr: "창공의 검사", status: "CONFIRMED_KR" }],
  [265, { nameCn: "驭空之刃", nameKr: "공중의 칼날", status: "CONFIRMED_KR" }],
  [266, { nameCn: "击剑师", nameKr: "검술사", status: "CONFIRMED_KR" }],
  [267, { nameCn: "里万事屋之主", nameKr: "해결사 사무소 주인", status: "CONFIRMED_KR" }],
  [268, { nameCn: "游击士", nameKr: "유격사", status: "CONFIRMED_KR" }],
  [269, { nameCn: "迅剑手", nameKr: "신속 검사", status: "CONFIRMED_KR" }],
  [270, { nameCn: "剑之少女", nameKr: "검의 소녀", status: "CONFIRMED_KR" }],
  [271, { nameCn: "王国公主", nameKr: "왕국의 공주", status: "CONFIRMED_KR" }],
  [272, { nameCn: "闪电公主", nameKr: "섬전의 공주", status: "CONFIRMED_KR" }],
  [273, { nameCn: "黄金雷击姬", nameKr: "성순검의 공주", status: "CONFIRMED_KR" }],
  [274, { nameCn: "魔剑士", nameKr: "엘프 파이터", status: "CONFIRMED_KR" }],
  [275, { nameCn: "神灭魔剑士", nameKr: "신멸 마검사", status: "CONFIRMED_KR" }],
  [276, { nameCn: "魔剑士", nameKr: "엘프 파이터", status: "CONFIRMED_KR" }],
  [277, { nameCn: "精灵剑士", nameKr: "엘프 소드 마스터", status: "CONFIRMED_KR" }],
  [278, { nameCn: "佣兵", nameKr: "용병", status: "CONFIRMED_KR" }],
  [279, { nameCn: "传承者", nameKr: "계승자", status: "CONFIRMED_KR" }],
  [280, { nameCn: "光之剑", nameKr: "빛의 검", status: "CONFIRMED_KR" }],
  [281, { nameCn: "天马公主", nameKr: "페가수스 프린세스", status: "CONFIRMED_KR" }],
  [282, { nameCn: "灿金之剑", nameKr: "휘광의 검", status: "CONFIRMED_KR" }],
  [283, { nameCn: "荣光仡刃", nameKr: "영광의 칼날", status: "CONFIRMED_KR" }],
  [284, { nameCn: "孤旅之锋", nameKr: "고독한 여정의 칼날", status: "CONFIRMED_KR" }],
  [285, { nameCn: "守世逆刃", nameKr: "세상을 수호하는 역날", status: "CONFIRMED_KR" }],
  [286, { nameCn: "山林独行者", nameKr: "산림의 독행자", status: "CONFIRMED_KR" }],
  [287, { nameCn: "群山守护者", nameKr: "뭇산의 수호자", status: "CONFIRMED_KR" }],
  [288, { nameCn: "凯普1号", nameKr: "가이버 1", status: "CONFIRMED_KR" }],
  [289, { nameCn: "巨人殖装", nameKr: "가이버 기간틱", status: "CONFIRMED_KR" }],
  [290, { nameCn: "巨神殖装", nameKr: "가이버 기간틱XD", status: "CONFIRMED_KR" }],
  [291, { nameCn: "凯普3号", nameKr: "가이버 3", status: "CONFIRMED_KR" }],
  [292, { nameCn: "黑色巨人殖装", nameKr: "블랙 가이버 기간틱", status: "CONFIRMED_KR" }],
  [293, { nameCn: "黑色巨神殖装", nameKr: "블랙 가이버 기간틱XD", status: "CONFIRMED_KR" }],
  [294, { nameCn: "旧日勇者", nameKr: "지난 날의 용사", status: "CONFIRMED_KR" }],
  [295, { nameCn: "屠龙统帅", nameKr: "드래곤 슬레이어 통솔자", status: "CONFIRMED_KR" }],
  [296, { nameCn: "不灭帝皇", nameKr: "불멸의 황제", status: "CONFIRMED_KR" }],
  [297, { nameCn: "处决者", nameKr: "처형자", status: "CONFIRMED_KR" }],
  [299, { nameCn: "见习战士", nameKr: "견습 파이터", status: "CONFIRMED_KR" }],
  [301, { nameCn: "骑士", nameKr: "나이트", status: "CONFIRMED_KR" }],
  [302, { nameCn: "骑士长", nameKr: "하이랜더", status: "CONFIRMED_KR" }],
  [303, { nameCn: "强训骑士", nameKr: "그랜드 나이트", status: "CONFIRMED_KR" }],
  [304, { nameCn: "骑士统帅", nameKr: "나이트 마스터", status: "CONFIRMED_KR" }],
  [305, { nameCn: "强袭统帅", nameKr: "그랜드 마스터", status: "CONFIRMED_KR" }],
  [306, { nameCn: "皇家骑士", nameKr: "로열 나이트", status: "CONFIRMED_KR" }],
  [307, { nameCn: "突击骑士", nameKr: "스트라이크 마스터", status: "CONFIRMED_KR" }],
  [351, { nameCn: "独角兽骑士", nameKr: "유니콘 나이트", status: "CONFIRMED_KR" }],
  [352, { nameCn: "独角兽统帅", nameKr: "유니콘 마스터", status: "CONFIRMED_KR" }],
  [353, { nameCn: "黑骑士", nameKr: "다크 나이트", status: "CONFIRMED_KR" }],
  [354, { nameCn: "光武", nameKr: "광무", status: "CONFIRMED_KR" }],
  [355, { nameCn: "光武·改", nameKr: "사쿠라 전용 광무", status: "CONFIRMED_KR" }],
  [356, { nameCn: "光武", nameKr: "광무", status: "CONFIRMED_KR" }],
  [357, { nameCn: "光武·改", nameKr: "스미레 전용 광무", status: "CONFIRMED_KR" }],
  [358, { nameCn: "光武", nameKr: "광무", status: "CONFIRMED_KR" }],
  [359, { nameCn: "光武·改", nameKr: "아이리스 전용 광무", status: "CONFIRMED_KR" }],
  [360, { nameCn: "杀手兄弟", nameKr: "암살 형제", status: "CONFIRMED_KR" }],
  [361, { nameCn: "武态·盾", nameKr: "무기 형태 · 방패", status: "CONFIRMED_KR" }],
  [362, { nameCn: "武态·剑", nameKr: "무기 형태 · 검", status: "CONFIRMED_KR" }],
  [363, { nameCn: "法术骑士", nameKr: "위저드 나이트", status: "CONFIRMED_KR" }],
  [364, { nameCn: "法术骑士长", nameKr: "위저드 나이트 로드", status: "CONFIRMED_KR" }],
  [365, { nameCn: "法骑统帅", nameKr: "위저드 나이트 마스터", status: "CONFIRMED_KR" }],
  [366, { nameCn: "西卡战巫", nameKr: "시카의 전투무녀", status: "CONFIRMED_KR" }],
  [367, { nameCn: "西卡圣女", nameKr: "시카의 성녀", status: "CONFIRMED_KR" }],
  [369, { nameCn: "机械骑士", nameKr: "머신 나이트", status: "CONFIRMED_KR" }],
  [370, { nameCn: "机械统帅", nameKr: "휠 제네럴", status: "CONFIRMED_KR" }],
  [371, { nameCn: "征伐骑士", nameKr: "토벌의 기사", status: "CONFIRMED_KR" }],
  [372, { nameCn: "征伐骑士王", nameKr: "토벌의 기사왕", status: "CONFIRMED_KR" }],
  [374, { nameCn: "坦克兵", nameKr: "전차병", status: "CONFIRMED_KR" }],
  [375, { nameCn: "高级坦克兵", nameKr: "고급 전차병", status: "CONFIRMED_KR" }],
  [376, { nameCn: "机械骁骑", nameKr: "메카닉 나이트", status: "CONFIRMED_KR" }],
  [378, { nameCn: "灵骑士", nameKr: "영의 기사", status: "CONFIRMED_KR" }],
  [379, { nameCn: "祖灵骑兵", nameKr: "선조의 기병", status: "CONFIRMED_KR" }],
  [380, { nameCn: "圣灵骁骑", nameKr: "성령 기사", status: "CONFIRMED_KR" }],
  [381, { nameCn: "野性战骑", nameKr: "야성의 기병", status: "CONFIRMED_KR" }],
  [382, { nameCn: "荒野骑将", nameKr: "황야의 기병 장교", status: "CONFIRMED_KR" }],
  [383, { nameCn: "夜骑士", nameKr: "밤의 기사", status: "CONFIRMED_KR" }],
  [384, { nameCn: "守夜人", nameKr: "야경꾼", status: "CONFIRMED_KR" }],
  [385, { nameCn: "永夜之誓", nameKr: "영원한 밤의 맹세", status: "CONFIRMED_KR" }],
  [386, { nameCn: "地火龙骑", nameKr: "불의 용기사", status: "CONFIRMED_KR" }],
  [387, { nameCn: "狱渊统帅", nameKr: "지옥의 사령관", status: "CONFIRMED_KR" }],
  [388, { nameCn: "寒渊巡骑", nameKr: "빙하의 순찰 기사", status: "CONFIRMED_KR" }],
  [389, { nameCn: "凌踏的冰爪", nameKr: "침략의 서리 발톱", status: "CONFIRMED_KR" }],
  [391, { nameCn: "铁血骁骑", nameKr: "철혈 기사", status: "CONFIRMED_KR" }],
  [392, { nameCn: "狂战统帅", nameKr: "광전 사령관", status: "CONFIRMED_KR" }],
  [393, { nameCn: "绝锋影骑", nameKr: "그림자 기사의 칼끝", status: "CONFIRMED_KR" }],
  [394, { nameCn: "敛命死神", nameKr: "영혼 수확자", status: "CONFIRMED_KR" }],
  [395, { nameCn: "烈火先锋", nameKr: "화염의 선봉", status: "CONFIRMED_KR" }],
  [396, { nameCn: "焰锋统帅", nameKr: "화염의 통솔자", status: "CONFIRMED_KR" }],
  [397, { nameCn: "孤刃骑影", nameKr: "고독한 기사", status: "CONFIRMED_KR" }],
  [398, { nameCn: "破阵骁将", nameKr: "파진 전사", status: "CONFIRMED_KR" }],
  [401, { nameCn: "鹰骑士", nameKr: "호크 나이트", status: "CONFIRMED_KR" }],
  [402, { nameCn: "飞马骑士", nameKr: "페가수스 나이트", status: "CONFIRMED_KR" }],
  [403, { nameCn: "龙骑士", nameKr: "드래곤 나이트", status: "CONFIRMED_KR" }],
  [404, { nameCn: "圣天马将军", nameKr: "페가수스 로드", status: "CONFIRMED_KR" }],
  [405, { nameCn: "龙骑统帅", nameKr: "드래곤 마스터", status: "CONFIRMED_KR" }],
  [406, { nameCn: "圣天马统帅", nameKr: "페가수스 마스터", status: "CONFIRMED_KR" }],
  [407, { nameCn: "特工", nameKr: "호문클루스 OZ74", status: "CONFIRMED_KR" }],
  [408, { nameCn: "帝国密使", nameKr: "제국 첩보원", status: "CONFIRMED_KR" }],
  [409, { nameCn: "钢翼战士", nameKr: "강익 전사", status: "CONFIRMED_KR" }],
  [410, { nameCn: "钢翼勇士", nameKr: "아이언 엔젤", status: "CONFIRMED_KR" }],
  [411, { nameCn: "翠晶统帅", nameKr: "비취 수정 기사단장", status: "CONFIRMED_KR" }],
  [412, { nameCn: "圣天马星骑", nameKr: "홀리 페가수스 나이트", status: "CONFIRMED_KR" }],
] as const;
