export const HERO_FINAL_JOB_LOCALIZATION_PART_4 = [
  [1093, { nameCn: "灾厄神偶", nameKr: "재앙의 인형", status: "CONFIRMED_KR" }],
  [1096, { nameCn: "永夜之王", nameKr: "영원한 밤의 왕", status: "CONFIRMED_KR" }],
  [1099, { nameCn: "毁灭之具象", nameKr: "파멸의 실체", status: "CONFIRMED_KR" }],
  [1104, { nameCn: "影", nameKr: "쉐도우", status: "CONFIRMED_KR" }],
  [1105, { nameCn: "大统帅", nameKr: "하이 마스터", status: "CONFIRMED_KR" }],
  [1106, { nameCn: "漆黑之牙", nameKr: "칠흑의 송곳니", status: "CONFIRMED_KR" }],
  [1108, { nameCn: "漆黑魅影", nameKr: "다크 팬텀", status: "CONFIRMED_KR" }],
  [1111, { nameCn: "邪眼师", nameKr: "사안사", status: "CONFIRMED_KR" }],
  [1114, { nameCn: "异星王子", nameKr: "크림조의 왕자", status: "CONFIRMED_KR" }],
  [1116, { nameCn: "闪击统帅", nameKr: "쉐도우 나이트 마스터", status: "CONFIRMED_KR" }],
  [1118, { nameCn: "黑妖刺客", nameKr: "다크 엘프 암살자", status: "CONFIRMED_KR" }],
  [1123, { nameCn: "忍部首领", nameKr: "닌자두목", status: "CONFIRMED_KR" }],
  [1124, { nameCn: "幻王丸", nameKr: "겐오마루", status: "CONFIRMED_KR" }],
  [1126, { nameCn: "血梦之主", nameKr: "핏빛 서큐버스", status: "CONFIRMED_KR" }],
  [1129, { nameCn: "星丽剑姬", nameKr: "성려검희", status: "CONFIRMED_KR" }],
  [1131, { nameCn: "强袭斗将", nameKr: "포스 제네럴", status: "CONFIRMED_KR" }],
  [1134, { nameCn: "独行义侠", nameKr: "외톨이 협객", status: "CONFIRMED_KR" }],
  [1136, { nameCn: "抗暴统帅", nameKr: "복수의 지휘관", status: "CONFIRMED_KR" }],
  [1138, { nameCn: "远行浪客", nameKr: "방랑 낭객", status: "CONFIRMED_KR" }],
  [1140, { nameCn: "暮影刺客", nameKr: "황혼의 암살자", status: "CONFIRMED_KR" }],
  [1142, { nameCn: "恶欲裁罚", nameKr: "악한 욕망의 징벌자", status: "CONFIRMED_KR" }],
  [1144, { nameCn: "希望之花", nameKr: "희망의 꽃", status: "CONFIRMED_KR" }],
  [1146, { nameCn: "暗楔女统帅", nameKr: "어둠의 여장군", status: "CONFIRMED_KR" }],
  [1148, { nameCn: "影锋暗将", nameKr: "음영의 장군", status: "CONFIRMED_KR" }],
  [1152, { nameCn: "忍者Ginzu", nameKr: "닌자 긴주", status: "CONFIRMED_KR" }],
  [1153, { nameCn: "小刀马克", nameKr: "맥 더 나이프", status: "CONFIRMED_KR" }],
  [1155, { nameCn: "暗夜君王", nameKr: "어둠의 군주", status: "CONFIRMED_KR" }],
  [1158, { nameCn: "断命之天神", nameKr: "단명의 천신", status: "CONFIRMED_KR" }],
  [1161, { nameCn: "寒光影姬", nameKr: "서늘한 빛의 그림자", status: "CONFIRMED_KR" }],
  [1163, { nameCn: "幽视暗裁者", nameKr: "어둠의 심판자", status: "CONFIRMED_KR" }],
  [1167, { nameCn: "惊魂假面", nameKr: "공포의 가면", status: "CONFIRMED_KR" }],
  [1170, { nameCn: "白牙斗将", nameKr: "백아 대장군", status: "CONFIRMED_KR" }],
  [1172, { nameCn: "圣辉游侠", nameKr: "성휘 레인저", status: "CONFIRMED_KR" }],
  [1174, { nameCn: "万秘主宰", nameKr: null, status: "UNRELEASED_KR" }],
  [1177, { nameCn: "孤高之花", nameKr: null, status: "UNRELEASED_KR" }],
  [1205, { nameCn: "贝希摩斯", nameKr: "베히모스", status: "CONFIRMED_KR" }],
  [1206, { nameCn: "海德拉", nameKr: "히드라", status: "CONFIRMED_KR" }],
  [1207, { nameCn: "巴哈姆特", nameKr: "바하무트", status: "CONFIRMED_KR" }],
  [1210, { nameCn: "龙族统帅", nameKr: "드래곤 제네럴", status: "CONFIRMED_KR" }],
  [1213, { nameCn: "灵龙转生使", nameKr: "정령용의 환생", status: "CONFIRMED_KR" }],
  [1217, { nameCn: "佑世真龙", nameKr: "세계 구원의 용", status: "CONFIRMED_KR" }],
  [1219, { nameCn: "炎龙王之裔", nameKr: "염룡왕의 후예", status: "CONFIRMED_KR" }],
  [20204, { nameCn: "突击队长", nameKr: "캡틴 코만도", status: "CONFIRMED_KR" }],
  [20205, { nameCn: "天才婴儿", nameKr: "베이비 헤드", status: "CONFIRMED_KR" }],
  [20208, { nameCn: "海礁统帅", nameKr: "암초 통솔자", status: "CONFIRMED_KR" }],
  [20211, { nameCn: "小恶魔女仆", nameKr: "소악마 서번트", status: "CONFIRMED_KR" }],
  [20214, { nameCn: "复兴之剑", nameKr: "부흥의 검", status: "CONFIRMED_KR" }],
  [20217, { nameCn: "匡正之剑", nameKr: "시정의 검", status: "CONFIRMED_KR" }],
  [20219, { nameCn: "荣光宰相", nameKr: "영광의 재상", status: "CONFIRMED_KR" }],
  [20222, { nameCn: "第七任会长", nameKr: "7대 마스터", status: "CONFIRMED_KR" }],
  [20225, { nameCn: "无冕帝皇", nameKr: "무관의 제왕", status: "CONFIRMED_KR" }],
  [20228, { nameCn: "荒原兽主", nameKr: "황야의 테이머", status: "CONFIRMED_KR" }],
  [20232, { nameCn: "圣辉王子", nameKr: "성휘 왕자", status: "CONFIRMED_KR" }],
  [20235, { nameCn: "寂夜影主", nameKr: null, status: "UNRELEASED_KR" }],
  [20238, { nameCn: "剑骸使者", nameKr: null, status: "UNRELEASED_KR" }],
  [20242, { nameCn: "绝命天使", nameKr: null, status: "UNRELEASED_KR" }],
  [20246, { nameCn: "夜叉王", nameKr: null, status: "UNRELEASED_KR" }],
  [20302, { nameCn: "定衡者", nameKr: "균형 정립자", status: "CONFIRMED_KR" }],
  [20304, { nameCn: "掠界狂影", nameKr: null, status: "UNRELEASED_KR" }],
  [20306, { nameCn: "千峰怒神", nameKr: null, status: "UNRELEASED_KR" }],
  [20703, { nameCn: "大炼金术士", nameKr: "대 연금술사", status: "CONFIRMED_KR" }],
  [20706, { nameCn: "辉光天使", nameKr: "휘광 천사", status: "CONFIRMED_KR" }],
  [20709, { nameCn: "罡风御主", nameKr: null, status: "UNRELEASED_KR" }],
  [20712, { nameCn: "比拉德大导师", nameKr: null, status: "UNRELEASED_KR" }],
  [20714, { nameCn: "理财传说", nameKr: null, status: "UNRELEASED_KR" }],
  [20717, { nameCn: "魔剑主宰", nameKr: null, status: "UNRELEASED_KR" }],
  [20801, { nameCn: "辉耀神眷使", nameKr: "찬란한 빛의 전령사", status: "CONFIRMED_KR" }],
  [20804, { nameCn: "星之女王", nameKr: "별의 여왕", status: "CONFIRMED_KR" }],
  [20806, { nameCn: "神眷者", nameKr: "신의 아이", status: "CONFIRMED_KR" }],
  [20808, { nameCn: "神运圣女", nameKr: "천운의 성녀", status: "CONFIRMED_KR" }],
  [20810, { nameCn: "自然共鸣者", nameKr: "자연과 공명하는 자", status: "CONFIRMED_KR" }],
  [20813, { nameCn: "幻梦舞姬", nameKr: "환상의 무희", status: "CONFIRMED_KR" }],
  [20817, { nameCn: "炽天之阳", nameKr: "눈부신 태양", status: "CONFIRMED_KR" }],
  [20819, { nameCn: "万灵使者", nameKr: "만령 사자", status: "CONFIRMED_KR" }],
  [20821, { nameCn: "弑神天使", nameKr: "갓 킬러 천사", status: "CONFIRMED_KR" }],
  [20824, { nameCn: "山罡向导", nameKr: null, status: "UNRELEASED_KR" }],
  [20827, { nameCn: "天使投资人", nameKr: null, status: "UNRELEASED_KR" }],
  [20830, { nameCn: "梵天继承者", nameKr: null, status: "UNRELEASED_KR" }],
  [201003, { nameCn: "魔渊主宰", nameKr: "마계의 주인", status: "CONFIRMED_KR" }],
  [201005, { nameCn: "噬界狂炎", nameKr: "잠식의 광염", status: "CONFIRMED_KR" }],
  [201008, { nameCn: "凝魂萨满", nameKr: "혼령 주술사", status: "CONFIRMED_KR" }],
  [201011, { nameCn: "森罗霸主", nameKr: null, status: "UNRELEASED_KR" }],
  [201014, { nameCn: "绝末魔神", nameKr: null, status: "UNRELEASED_KR" }],
  [201016, { nameCn: "黑暗天使", nameKr: null, status: "UNRELEASED_KR" }],
  [201018, { nameCn: "混沌帝王", nameKr: null, status: "UNRELEASED_KR" }],
  [201020, { nameCn: "堕夜剑魔", nameKr: null, status: "UNRELEASED_KR" }],
] as const;
