export const HERO_JOB_LOCALIZATION_PART_3 = [
  [413, { nameCn: "咒术使", nameKr: "어둠의 주술사", status: "CONFIRMED_KR" }],
  [415, { nameCn: "邪心龙使", nameKr: "사악한 용술사", status: "CONFIRMED_KR" }],
  [416, { nameCn: "魔翼斗将", nameKr: "검은 날개의 투장", status: "CONFIRMED_KR" }],
  [417, { nameCn: "锋翼统帅", nameKr: "아이언윙 마스터", status: "CONFIRMED_KR" }],
  [418, { nameCn: "龙骑士姬", nameKr: "용기사 공주", status: "CONFIRMED_KR" }],
  [419, { nameCn: "驭龙骑士", nameKr: "드래곤 기사", status: "CONFIRMED_KR" }],
  [420, { nameCn: "蔽空裂翼", nameKr: "하늘을 덮는 날개", status: "CONFIRMED_KR" }],
  [421, { nameCn: "堕临之灾厄", nameKr: "타락의 재앙", status: "CONFIRMED_KR" }],
  [422, { nameCn: "星虹冀羽", nameKr: "무지개 페가수스의 깃털", status: "CONFIRMED_KR" }],
  [423, { nameCn: "凛空皓翼", nameKr: "차가운 하늘의 밝은 날개", status: "CONFIRMED_KR" }],
  [424, { nameCn: "寒空掠影", nameKr: "냉혹한 섀도우", status: "CONFIRMED_KR" }],
  [425, { nameCn: "御空的霜翼", nameKr: "하늘을 가르는 서리 날개", status: "CONFIRMED_KR" }],
  [427, { nameCn: "逆途之影", nameKr: "역행의 그림자", status: "CONFIRMED_KR" }],
  [428, { nameCn: "终末之誓", nameKr: "종말의 맹세", status: "CONFIRMED_KR" }],
  [429, { nameCn: "反叛者", nameKr: "반역자", status: "CONFIRMED_KR" }],
  [430, { nameCn: "承袭之羽", nameKr: "계승의 깃털", status: "CONFIRMED_KR" }],
  [431, { nameCn: "凛空黯翼", nameKr: "암흑의 비상", status: "CONFIRMED_KR" }],
  [432, { nameCn: "赤曜狂龙", nameKr: "적요의 광룡", status: "CONFIRMED_KR" }],
  [433, { nameCn: "赤曜征服者", nameKr: "적요의 정복자", status: "CONFIRMED_KR" }],
  [434, { nameCn: "深林访客", nameKr: "깊은 숲의 방문객", status: "CONFIRMED_KR" }],
  [435, { nameCn: "天狗道修者", nameKr: "텐구도 수련자", status: "CONFIRMED_KR" }],
  [436, { nameCn: "缭乱的天狗姬", nameKr: "혼란의 텐구공주", status: "CONFIRMED_KR" }],
  [438, { nameCn: "执剑者", nameKr: "검 계승자", status: "CONFIRMED_KR" }],
  [439, { nameCn: "忠誓之羽", nameKr: "맹세의 날개", status: "CONFIRMED_KR" }],
  [440, { nameCn: "灿金辉翼", nameKr: "빛나는 금빛 날개", status: "CONFIRMED_KR" }],
  [441, { nameCn: "漆黑之影", nameKr: "칠흑의 그림자", status: "CONFIRMED_KR" }],
  [442, { nameCn: "罪渊黯翼", nameKr: "죄악의 검은 날개", status: "CONFIRMED_KR" }],
  [444, { nameCn: "宇宙骑士", nameKr: null, status: "UNRELEASED_KR" }],
  [445, { nameCn: "救世孤星", nameKr: null, status: "UNRELEASED_KR" }],
  [446, { nameCn: "驭虹之翼", nameKr: null, status: "UNRELEASED_KR" }],
  [447, { nameCn: "灿虹之星", nameKr: null, status: "UNRELEASED_KR" }],
  [448, { nameCn: "啼眼末裔", nameKr: null, status: "UNRELEASED_KR" }],
  [449, { nameCn: "引魂使者", nameKr: null, status: "UNRELEASED_KR" }],
  [450, { nameCn: "渡魂天翼", nameKr: null, status: "UNRELEASED_KR" }],
  [451, { nameCn: "八部众神将", nameKr: null, status: "UNRELEASED_KR" }],
  [452, { nameCn: "迦楼罗王", nameKr: null, status: "UNRELEASED_KR" }],
  [501, { nameCn: "海盗", nameKr: "파이러트", status: "CONFIRMED_KR" }],
  [502, { nameCn: "海骑士", nameKr: "서펜트 나이트", status: "CONFIRMED_KR" }],
  [503, { nameCn: "海骑统帅", nameKr: "서펜트 마스터", status: "CONFIRMED_KR" }],
  [504, { nameCn: "海斗士", nameKr: "마린 파이터", status: "CONFIRMED_KR" }],
  [505, { nameCn: "海斗统帅", nameKr: "마린 마스터", status: "CONFIRMED_KR" }],
  [506, { nameCn: "水手", nameKr: "선원", status: "CONFIRMED_KR" }],
  [507, { nameCn: "民政官", nameKr: "민정관", status: "CONFIRMED_KR" }],
  [508, { nameCn: "行政官", nameKr: "행정관", status: "CONFIRMED_KR" }],
  [509, { nameCn: "执政官", nameKr: "집정관", status: "CONFIRMED_KR" }],
  [510, { nameCn: "海畔歌者", nameKr: "바닷가의 가수", status: "CONFIRMED_KR" }],
  [511, { nameCn: "哀泪颂唱者", nameKr: "눈물의 찬송자", status: "CONFIRMED_KR" }],
  [512, { nameCn: "深海的风铃", nameKr: "심해의 풍경", status: "CONFIRMED_KR" }],
  [513, { nameCn: "人鱼少女", nameKr: "인어 소녀", status: "CONFIRMED_KR" }],
  [514, { nameCn: "幻逝谜伶", nameKr: "환상의 배우", status: "CONFIRMED_KR" }],
  [515, { nameCn: "辉光领航喵", nameKr: "빛의 항해묘", status: "CONFIRMED_KR" }],
  [516, { nameCn: "穹海纵横王", nameKr: "바다의 제왕", status: "CONFIRMED_KR" }],
  [517, { nameCn: "踏浪斗士", nameKr: "파도 위 투사", status: "CONFIRMED_KR" }],
  [518, { nameCn: "驭潮将星", nameKr: "파도의 지배자", status: "CONFIRMED_KR" }],
  [519, { nameCn: "骁浪者", nameKr: null, status: "UNRELEASED_KR" }],
  [520, { nameCn: "海潮之守", nameKr: null, status: "UNRELEASED_KR" }],
  [521, { nameCn: "海平之望", nameKr: null, status: "UNRELEASED_KR" }],
  [601, { nameCn: "射手", nameKr: "아처", status: "CONFIRMED_KR" }],
  [602, { nameCn: "狙击手", nameKr: "스나이퍼", status: "CONFIRMED_KR" }],
  [603, { nameCn: "弓骑士", nameKr: "보우 나이트", status: "CONFIRMED_KR" }],
  [604, { nameCn: "游侠", nameKr: "레인저", status: "CONFIRMED_KR" }],
  [605, { nameCn: "弓骑统帅", nameKr: "보우 마스터", status: "CONFIRMED_KR" }],
  [606, { nameCn: "骑射手", nameKr: "캐벌리 아처", status: "CONFIRMED_KR" }],
  [607, { nameCn: "帝国贵族", nameKr: "제국 귀족", status: "CONFIRMED_KR" }],
  [608, { nameCn: "乐者", nameKr: "연주가", status: "CONFIRMED_KR" }],
  [609, { nameCn: "帝国皇子", nameKr: "제국 왕자", status: "CONFIRMED_KR" }],
  [610, { nameCn: "吟游诗人", nameKr: "음유시인", status: "CONFIRMED_KR" }],
  [611, { nameCn: "射手", nameKr: "아처", status: "CONFIRMED_KR" }],
  [612, { nameCn: "狼骑士", nameKr: "울프 나이트", status: "CONFIRMED_KR" }],
  [613, { nameCn: "狼骑统帅", nameKr: "울프 마스터", status: "CONFIRMED_KR" }],
  [614, { nameCn: "复仇者", nameKr: "어벤져", status: "CONFIRMED_KR" }],
  [615, { nameCn: "破灭之翼", nameKr: "파멸의 날개", status: "CONFIRMED_KR" }],
  [616, { nameCn: "弓将", nameKr: "궁무장", status: "CONFIRMED_KR" }],
  [617, { nameCn: "空之弓将", nameKr: "천공의 궁무장", status: "CONFIRMED_KR" }],
  [618, { nameCn: "天空神", nameKr: "천공신", status: "CONFIRMED_KR" }],
  [619, { nameCn: "铳击士", nameKr: "머스킷", status: "CONFIRMED_KR" }],
  [620, { nameCn: "铳击队长", nameKr: "캡틴 거너", status: "CONFIRMED_KR" }],
  [621, { nameCn: "铳击统帅", nameKr: "건 커맨더", status: "CONFIRMED_KR" }],
  [623, { nameCn: "候补军官", nameKr: "장교 후보생", status: "CONFIRMED_KR" }],
  [624, { nameCn: "深蓝魔女", nameKr: "푸른 마녀", status: "CONFIRMED_KR" }],
  [625, { nameCn: "真深蓝魔女", nameKr: "결전의 푸른 마녀", status: "CONFIRMED_KR" }],
  [626, { nameCn: "新义勇兵", nameKr: "신입 의용병", status: "CONFIRMED_KR" }],
  [627, { nameCn: "侦察兵", nameKr: "정찰병", status: "CONFIRMED_KR" }],
  [628, { nameCn: "侦察猎兵", nameKr: "정찰엽병", status: "CONFIRMED_KR" }],
  [629, { nameCn: "突击兵", nameKr: "돌격병", status: "CONFIRMED_KR" }],
  [630, { nameCn: "突击猎兵", nameKr: "돌격엽병", status: "CONFIRMED_KR" }],
  [631, { nameCn: "支援兵", nameKr: "지원병", status: "CONFIRMED_KR" }],
  [632, { nameCn: "支援猎兵", nameKr: "지원엽병", status: "CONFIRMED_KR" }],
  [634, { nameCn: "狙击猎兵", nameKr: "저격엽병", status: "CONFIRMED_KR" }],
  [635, { nameCn: "技术官", nameKr: "기술 교관", status: "CONFIRMED_KR" }],
  [636, { nameCn: "机工士", nameKr: "메카니션", status: "CONFIRMED_KR" }],
  [637, { nameCn: "机工统帅", nameKr: "메카 마스터", status: "CONFIRMED_KR" }],
  [638, { nameCn: "科技铳士", nameKr: "테크니컬 슈터", status: "CONFIRMED_KR" }],
  [639, { nameCn: "妖精少女", nameKr: "엘프 소녀", status: "CONFIRMED_KR" }],
  [640, { nameCn: "歌巫女", nameKr: "가무녀", status: "CONFIRMED_KR" }],
  [641, { nameCn: "圣印歌巫女", nameKr: "성인가의 무녀", status: "CONFIRMED_KR" }],
  [642, { nameCn: "精灵弓手", nameKr: "엘프 궁수", status: "CONFIRMED_KR" }],
  [643, { nameCn: "龙翼弓奏者", nameKr: "용익궁 연주자", status: "CONFIRMED_KR" }],
  [644, { nameCn: "女王特使", nameKr: "여왕 특사", status: "CONFIRMED_KR" }],
  [645, { nameCn: "妖精之望", nameKr: "엘프의 희망", status: "CONFIRMED_KR" }],
  [646, { nameCn: "风舞者", nameKr: "폭풍의 무희", status: "CONFIRMED_KR" }],
] as const;
