import type { HeroSkillKrCatalog } from "./hero-skill-localization.schema";

export const HERO_SKILL_KR_CATALOG: HeroSkillKrCatalog = {
  schemaVersion: 1,
  sourceFamily: "hero-skill-korean-localization",
  records: [
    {
      skillId: 10301,
      sourceNameCn: "突击",
      nameKr: "돌격",
      descKr: "단일 적에게 1배 피해. 치료 방해를 1턴 부여하고, 공격 전 이동 1칸마다 피해 +20%(최대 +60%).",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5020,
      sourceNameCn: "整军",
      nameKr: "군단 정비",
      descKr: "부대 생명이 90% 이상이면 공격과 방어 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10324,
      sourceNameCn: "猛撞",
      nameKr: "맹렬한 돌격",
      descKr: "단일 적에게 1.4배 피해. 대상을 2칸 밀치고 방어 -20%, 호위 불가를 2턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5003,
      sourceNameCn: "破攻",
      nameKr: "무기 파괴",
      descKr: "전투 진입 전 50% 확률로 적의 공격과 지력 -20%. 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5007,
      sourceNameCn: "压制",
      nameKr: "제압",
      descKr: "자신의 남은 생명 비율이 상대보다 높으면 전투 중 공격 +12%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10314,
      sourceNameCn: "气浪",
      nameKr: "폭풍",
      descKr: "공격하여 전투 진입 시 부대 생명이 80% 이상이면 전투 중 받는 피해 -30%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10328,
      sourceNameCn: "骑士精神",
      nameKr: "기사도",
      descKr: "자신 부대 공격 +30%, 면역과 폭풍을 2턴 부여. 사용 후 3칸 추가 이동하고 공격 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 11807,
      sourceNameCn: "帝国冲锋",
      nameKr: "제국의 돌격",
      descKr: "제국의 빛 아군의 공격·방어를 크게 올리고, 공격 전 이동 1칸마다 전투 피해 +5%(최대 +15%). 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10302,
      sourceNameCn: "千骑",
      nameKr: "일기당천",
      descKr: "단일 적에게 1.7배 피해. 전투 후 이동력 -2와 호위 불가를 2턴 부여하며 제거되지 않음.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10208,
      sourceNameCn: "斩阳",
      nameKr: "태양 베기",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. 전투 후 가한 피해량의 30%만큼 생명을 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [10, 12, 40], note: "Legacy Korean sheet hero/data/레딘.js, hero/data/엘윈.js, hero/data/루인.js; cross-checked against current generated Skill 10208 ID/CN/effect." },
    },
    {
      skillId: 10809,
      sourceNameCn: "审判",
      nameKr: "심판",
      descKr: "단일 적 부대를 공격해 1.2배의 피해를 준다. 전투 진입 전 자신 부대의 방어, 마방 +30%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [10], note: "Legacy Korean sheet Hero page for 레딘; cross-checked against current generated Skill 10809 ID/CN/effect." },
    },
    {
      skillId: 10223,
      sourceNameCn: "大喝",
      nameKr: "힘의 외침",
      descKr: "단일 적군을 공격해 1.3배 피해를 준다. 전투 전 상대의 버프 2개를 제거하고 공격, 지력 -20%, 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [12, 40], note: "Legacy Korean sheet hero/data/엘윈.js and hero/data/루인.js; cross-checked against current generated Skill 10223 ID/CN/effect." },
    },
    {
      skillId: 10218,
      sourceNameCn: "剑魂",
      nameKr: "검혼",
      descKr: "단일 적군을 공격해 1.8배 피해를 준다. 전투 전 적의 버프 5개를 제거하고 치료 불가를 2턴 부여한다. 이 효과는 제거되지 않는다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [12], note: "Legacy Korean sheet hero/data/엘윈.js; cross-checked against current generated Skill 10218 ID/CN/effect." },
    },
    {
      skillId: 10103,
      sourceNameCn: "迎头痛击",
      nameKr: "정면일격",
      descKr: "단일 적군을 공격해 1.7배 피해를 준다. 전투 전 공격의 20%를 방어에 더하고 적의 모든 패시브 스킬을 무효화한다. 2턴 지속, 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [12], note: "Legacy Korean sheet hero/data/엘윈.js; cross-checked against current generated Skill 10103 ID/CN/effect." },
    },
    {
      skillId: 10842,
      sourceNameCn: "惩戒",
      nameKr: "징벌",
      descKr: "단일 적 부대를 공격해 1.5배의 마법 피해를 준다. 전투 후 준 피해량의 20%만큼 생명을 회복한다. 근접 병사를 휴대하면 병사도 함께 공격한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [5], note: "Legacy Korean sheet hero/data/크리스.js; cross-checked against current generated Skill 10842 ID/CN/effect." },
    },
    {
      skillId: 10808,
      sourceNameCn: "救赎",
      nameKr: "구원",
      descKr: "단일 적 부대를 공격해 1.5배의 마법 피해를 준다. 전투 후 다른 모든 아군의 생명을 자신의 지력 2배만큼 회복한다. 근접 병사를 휴대하면 병사도 함께 공격한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [5], note: "Legacy Korean sheet hero/data/크리스.js; cross-checked against current generated Skill 10808 ID/CN/effect." },
    },
    {
      skillId: 10601,
      sourceNameCn: "狙击",
      nameKr: "저격",
      descKr: "단일 적을 1.4배 피해로 공격하며 비병에게 더 큰 피해를 준다. 전투 후 50% 확률로 스킬 사용 불가를 1턴 부여한다. 이 효과는 제거되지 않는다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1, 26], note: "Legacy Korean sheet hero/data/매튜.js and hero/data/루나.js; cross-checked against current generated Skill 10601 ID/CN/effect." },
    },
    {
      skillId: 11701,
      sourceNameCn: "影袭",
      nameKr: "그림자 습격",
      descKr: "호위를 무시하고 단일 적 부대를 공격해 1.3배의 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; cross-checked against current generated Skill 11701 ID/CN/effect." },
    },
    {
      skillId: 10604,
      sourceNameCn: "狙足",
      nameKr: "다리 저격",
      descKr: "단일 적을 공격해 1.4배 피해를 주며 비병에게 더 큰 피해를 준다. 전투 후 이동력 -1과 호위 불가를 1턴 부여하며 제거되지 않는다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [34, 42], note: "Legacy Korean sheet hero/data/키리카제.js and hero/data/디오스.js; cross-checked against current generated Skill 10604 ID/CN/effect." },
    },
    {
      skillId: 10501,
      sourceNameCn: "水枪",
      nameKr: "물의 창",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. 물 속에 있을 경우 2배의 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [42], note: "Legacy Korean sheet hero/data/디오스.js; cross-checked against current generated Skill 10501 ID/CN/effect." },
    },
    {
      skillId: 10326,
      sourceNameCn: "破阵",
      nameKr: "진형파괴",
      descKr: "단일 적 부대를 공격해 1배 피해를 준다. 대상을 2칸 밀쳐내고 다음 턴 행동 불가를 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [42, 122], note: "Legacy Korean sheet hero/data/디오스.js and hero/data/힐다.js; cross-checked against current generated Skill 10326 ID/CN/effect." },
    },
    {
      skillId: 10201,
      sourceNameCn: "气刃",
      nameKr: "바람 칼날",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. 근접전 병사를 이끌고 있다면 병사도 함께 공격한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [34], note: "Legacy Korean sheet hero/data/키리카제.js; cross-checked against current generated Skill 10201 ID/CN/effect." },
    },
    {
      skillId: 11711,
      sourceNameCn: "回刺",
      nameKr: "암살",
      descKr: "호위를 무시하고 단일 적 부대를 공격해 1.2배의 피해를 주고 치명타율 +20%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [34, 78, 95], note: "Legacy Korean sheet hero/data/키리카제.js, hero/data/필로테스.js, hero/data/올리버.js; cross-checked against current generated Skill 11711 ID/CN/effect." },
    },
    {
      skillId: 11704,
      sourceNameCn: "掠夺",
      nameKr: "약탈",
      descKr: "호위를 무시하고 단일 적 부대를 공격해 1.1배 피해를 준다. 전투 후 상대의 강화 효과를 최대 3개 강탈한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [78, 95], note: "Legacy Korean sheet hero/data/필로테스.js and hero/data/올리버.js; cross-checked against current generated Skill 11704 ID/CN/effect." },
    },
    {
      skillId: 11778,
      sourceNameCn: "压制射击",
      nameKr: "제압 사격",
      descKr: "단일 적을 공격해 1.25배 피해를 준다. 자신이 방어 지형에 있으면 전투 전 영웅 공격의 1배 수치로 고정 피해를 1회 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [60, 88], note: "Legacy Korean sheet hero/data/시그마.js and hero/data/엘라스타.js; cross-checked against current generated Skill 11778 ID/CN/effect." },
    },
    {
      skillId: 11779,
      sourceNameCn: "重击",
      nameKr: "헤비 어택",
      descKr: "단일 적 부대를 공격해 1.2배 피해를 준다. 자신이 방어 지형에 있으면 전투 전 대상을 1턴 기절시킨다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [60, 112], note: "Legacy Korean sheet hero/data/시그마.js and hero/data/토와.js; cross-checked against current generated Skill 11779 ID/CN/effect." },
    },
    {
      skillId: 10113,
      sourceNameCn: "力突",
      nameKr: "전력 찌르기",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 전투 전 방어의 1.6배로 공격을 대체하는 전력 찌르기 효과를 얻으며 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [48], note: "Legacy Korean sheet hero/data/아론.js; cross-checked against current generated Skill 10113 ID/CN/effect." },
    },
    {
      skillId: 10101,
      sourceNameCn: "穿甲",
      nameKr: "관통",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 전투 후 적 방어 -30%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [48], note: "Legacy Korean sheet hero/data/아론.js; cross-checked against current generated Skill 10101 ID/CN/effect." },
    },
    {
      skillId: 10206,
      sourceNameCn: "盾击",
      nameKr: "방패 공격",
      descKr: "단일 적 부대를 공격해 1배 피해를 준다. 전투 진입 전 적 부대를 1턴 기절시킨다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [48], note: "Legacy Korean sheet hero/data/아론.js; cross-checked against current generated Skill 10206 ID/CN/effect." },
    },
    {
      skillId: 10321,
      sourceNameCn: "疾突",
      nameKr: "질풍 돌격",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 전투 전 부대의 방어와 마방 +30%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [88], note: "Legacy Korean sheet hero/data/엘라스타.js; cross-checked against current generated Skill 10321 ID/CN/effect." },
    },
    {
      skillId: 10311,
      sourceNameCn: "撞击",
      nameKr: "격돌",
      descKr: "단일 적 부대를 공격해 1.2배 피해를 준다. 대상을 2칸 밀쳐내고 이동력 -2와 호위 불가를 1턴 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [122], note: "Legacy Korean sheet hero/data/힐다.js; cross-checked against current generated Skill 10311 ID/CN/effect." },
    },
    {
      skillId: 12018,
      sourceNameCn: "会心直击",
      nameKr: "회심의 일격",
      descKr: "단일 적 부대에 1.3배의 피해를 준다. 전투 전 이동 1칸마다 기술 +10%, 최대 +30%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [95], note: "Legacy Korean sheet hero/data/올리버.js; cross-checked against current generated Skill 12018 ID/CN/effect." },
    },
    {
      skillId: 10707,
      sourceNameCn: "风刃",
      nameKr: "윈드 커터",
      descKr: "단일 적 부대를 공격해 1.5배의 마법 피해를 준다. 비병에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [15], note: "Legacy Korean sheet hero/data/리아나.js; cross-checked against current generated Skill 10707 ID/CN/effect." },
    },
    {
      skillId: 10401,
      sourceNameCn: "雷光",
      nameKr: "뇌광",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 이 스킬로 적을 처치하면 스킬 쿨타임 -3.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [14], note: "Legacy Korean sheet hero/data/쉐리.js; cross-checked against current generated Skill 10401 ID/CN/effect." },
    },
    {
      skillId: 10811,
      sourceNameCn: "圣言",
      nameKr: "성언",
      descKr: "단일 적에게 1.5배의 마법 피해를 주며 마물에게 더 큰 피해를 준다. 전투 후 생명 비율이 가장 낮은 아군을 사용자 지력의 4배만큼 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [31], note: "Legacy Korean sheet hero/data/소피아.js; cross-checked against current generated Skill 10811 ID/CN/effect." },
    },
    {
      skillId: 11739,
      sourceNameCn: "投枪",
      nameKr: "투창",
      descKr: "단일 적에게 0.8배 피해를 준다. 공격 전 이동 1칸마다 피해 +20%, 최대 +60%. 전투 후 2칸 재이동 가능하며 근접 병사를 휴대하면 병사도 함께 공격한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [53], note: "Legacy Korean sheet hero/data/란포드.js; cross-checked against current generated Skill 11739 ID/CN/effect." },
    },
    {
      skillId: 11746,
      sourceNameCn: "虹吸",
      nameKr: "사이펀",
      descKr: "단일 적군에게 1.5배의 마법 피해를 준다. 전투 후 피해량의 30%만큼 생명을 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [93], note: "Legacy Korean sheet hero/data/미지의기사.js; cross-checked against current generated Skill 11746 ID/CN/effect, cooldown/range/target." },
    },
    {
      skillId: 10415,
      sourceNameCn: "奔雷",
      nameKr: "분뢰",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 전투 전 바람 타기를 얻어 생명이 50% 이상일 때 전투 진입 시 받는 피해 -15%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [25, 26, 112], note: "Legacy Korean sheet hero/data/알테뮬러.js, hero/data/루나.js, hero/data/토와.js; icon Skill_FlyCrash2 and effect parity identify current Skill 10415 奔雷. Corrects the earlier rejected 10405 heuristic." },
    },
    {
      skillId: 12095,
      sourceNameCn: "自由之刃",
      nameKr: "자유의 검",
      descKr: "단일 적군을 공격해 1.4배 피해를 준다. 전투 진입 전 대상의 모든 패시브 스킬 효과를 무효화하며 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [62, 77, 112], note: "Legacy Korean sheet hero/data/알프레드.js, hero/data/판.js, hero/data/토와.js; detailed Hero sources consistently use 자유의 검 and match current Skill 12095 ID/CN/effect/icon." },
    },
    {
      skillId: 12052,
      sourceNameCn: "激浪",
      nameKr: "거센 파도",
      descKr: "단일 적 부대를 공격해 1.5배 피해를 준다. 전투 후 이동 시 통과 가능한 모든 지형을 물 속으로 간주하며 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [62, 97], note: "Legacy Korean sheet hero/data/알프레드.js and hero/data/일루시아.js; detailed Hero sources consistently use 거센 파도 and match current Skill 12052 ID/CN/effect/icon." },
    },
    {
      skillId: 12062,
      sourceNameCn: "破刃",
      nameKr: "무기 파괴",
      descKr: "단일 적군을 공격해 1.5배 피해를 준다. 전투 후 적이 주는 피해량 -20%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [91, 122], note: "Legacy Korean sheet hero/data/에밀리아.js and hero/data/힐다.js; icon Skill_Emilia2 and effect parity identify current Skill 12062 破刃. Detailed source label overrides the speed-sheet 칼날 부수기 candidate." },
    },
    {
      skillId: 12104,
      sourceNameCn: "烈风再起",
      nameKr: "열풍재기",
      descKr: "치명타 확률 +10%. 피해를 준 뒤 부대가 약진 효과를 보유하면 4칸 재이동 가능하며, 재이동 효과는 1턴 간격으로 다시 발동할 수 있다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [110], note: "Legacy Korean sheet hero/data/아레스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5024,
      sourceNameCn: "增援",
      nameKr: "증원",
      descKr: "행동 종료 시 자신 부대 생명 20% 회복.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [110], note: "Legacy Korean sheet hero/data/아레스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12103,
      sourceNameCn: "转生的预言",
      nameKr: "전생의 예언",
      descKr: "범위 내 모든 리인카네이션 전생 아군의 공격·방어를 크게 올리고, 주위 3칸 내 적 1명마다 주는 피해 +5%(최대 +20%). 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [110], note: "Legacy Korean sheet hero/data/아레스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12105,
      sourceNameCn: "威风冲阵",
      nameKr: "위풍 돌격",
      descKr: "단일 적에게 1.4배 피해. 전투 전 강화 효과 3개 제거, 주위 2바퀴 내 적 1명마다 치명타 피해 +8%(최대 +32%). 적 처치 시 쿨타임 -3.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [110], note: "Legacy Korean sheet hero/data/아레스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5022,
      sourceNameCn: "防御应援",
      nameKr: "방어 지원",
      descKr: "행동 종료 시 인접한 아군 1명의 방어 +15%, 방어·마방 감소와 치료 방해 면역을 1턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [64], note: "Legacy Korean sheet hero/data/브렌다.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12080,
      sourceNameCn: "黑耀突击",
      nameKr: "흑요돌격",
      descKr: "단일 적에게 1.1배 피해를 주고 2칸 밀어낸다. 공격 전 이동 1칸마다 피해 +20%(최대 +60%). 전투 전 상처 저주를 1턴 부여하며 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [64], note: "Legacy Korean sheet hero/data/브렌다.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11706,
      sourceNameCn: "隐秘",
      nameKr: "은폐",
      descKr: "공격하여 전투 진입 시 치명타율 +10%, 받는 피해 -20%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [64, 146], note: "Legacy Korean sheet hero/data/브렌다.js, hero/data/셀베리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10203,
      sourceNameCn: "看破",
      nameKr: "간파",
      descKr: "치명타율 +10%. 피해를 줄 때 50% 확률로 적의 패시브 스킬을 2턴 무효화하며, 치명타 발생 시 반드시 발동.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [146, 123], note: "Legacy Korean sheet hero/data/셀베리아.js, hero/data/베르너.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10838,
      sourceNameCn: "信仰",
      nameKr: "신앙",
      descKr: "공격하여 전투 진입 시 피해 +15%. 전투 후 생명이 가장 낮은 다른 아군 1명의 생명을 자신의 지력 2배만큼 회복.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99174], note: "Legacy Korean sheet hero/data/아즈사.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12059,
      sourceNameCn: "圣盾",
      nameKr: "성스러운 방패",
      descKr: "전투 진입 시 마방 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99174], note: "Legacy Korean sheet hero/data/아즈사.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5015,
      sourceNameCn: "警戒",
      nameKr: "경계",
      descKr: "공격하여 전투 진입 시 전투 중 방어 +12%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [123, 65], note: "Legacy Korean sheet hero/data/베르너.js, hero/data/비라쥬.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10504,
      sourceNameCn: "驭水",
      nameKr: "파도 타기",
      descKr: "사용 후 이동 시 통과 가능한 모든 지형을 물 속으로 취급하며 2턴 지속. 사용 후 2칸 추가 이동하고 다시 공격 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [65, 52], note: "Legacy Korean sheet hero/data/비라쥬.js, hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12048,
      sourceNameCn: "技巧应援",
      nameKr: "기술 지원",
      descKr: "행동 종료 시 인접한 아군 1명의 기술 +20%, 치료 반전과 재행동 불가 면역을 1턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [65], note: "Legacy Korean sheet hero/data/비라쥬.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10104,
      sourceNameCn: "防御指挥",
      nameKr: "방어 지휘",
      descKr: "주위 2칸 내 모든 아군의 방어 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [65], note: "Legacy Korean sheet hero/data/비라쥬.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5016,
      sourceNameCn: "背水",
      nameKr: "배수의 진",
      descKr: "부대 생명이 50% 이하일 때 전투 진입 시 방어와 마방 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [65], note: "Legacy Korean sheet hero/data/비라쥬.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12068,
      sourceNameCn: "背摔",
      nameKr: "업어 치기",
      descKr: "단일 적에게 1.2배 피해. 이번 공격이 호위되지 않았다면 전투 후 적을 자신의 뒤쪽 빈 칸으로 이동시킨다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [65], note: "Legacy Korean sheet hero/data/비라쥬.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11730,
      sourceNameCn: "孤月",
      nameKr: "고월",
      descKr: "근접 전투 진입 시 영웅이 받는 피해 -20%. 행동 종료 시 병사가 모두 사망했다면 재행동 가능하며 3턴 간격으로 발동.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [52], note: "Legacy Korean sheet hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11725,
      sourceNameCn: "交替",
      nameKr: "교체",
      descKr: "아군 1명을 자신의 위치와 바꾼다. 사용 후 2칸 추가 이동하고 다시 공격 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [52], note: "Legacy Korean sheet hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10304,
      sourceNameCn: "攻击威吓",
      nameKr: "공격 위협",
      descKr: "행동 종료 시 주위 2칸 내 모든 적의 공격·지력 -15%, 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [52], note: "Legacy Korean sheet hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10404,
      sourceNameCn: "龙息",
      nameKr: "용의 숨결",
      descKr: "주위 2칸 내 모든 적에게 0.36배 범위 피해를 주고 각 대상에 무작위 약화 효과를 부여. 전투 후 바람 타기를 얻어 생명 50% 이상일 때 받는 피해 -15%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [52], note: "Legacy Korean sheet hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 6008,
      sourceNameCn: "防御大应援",
      nameKr: "방어 대지원",
      descKr: "행동 종료 시 주위 2칸 내 다른 아군 2명의 받는 피해 -15%, 방어·마방 감소와 치료 방해 면역을 1턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [52], note: "Legacy Korean sheet hero/data/안젤리나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12166,
      sourceNameCn: "晶瓣风暴",
      nameKr: "크리스탈 스톰",
      descKr: "행동 종료 시 주위 1바퀴 적에게 0.1배 범위 피해. 25% 확률로 무작위 장비 스킬 무효를 2턴 부여하며, NPC에는 무작위 속성 -25% 1턴으로 대체.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [101], note: "Legacy Korean sheet hero/data/헬레나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12167,
      sourceNameCn: "晶耀突袭",
      nameKr: "수정 광휘 돌격",
      descKr: "단일 적에게 1.6배 피해. 전투 후 장신구 스킬 무효를 2턴 부여하고 제거 불가. NPC에는 받는 피해 +30% 2턴으로 대체하며 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [101], note: "Legacy Korean sheet hero/data/헬레나.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10102,
      sourceNameCn: "枪阵",
      nameKr: "창진",
      descKr: "인접한 아군 대신 물리 공격을 받는다. 사용 시 호위 범위 2칸, 방어 +20%. 근접 전투 후 미늘의 고정 피해가 반드시 발동하며 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11749,
      sourceNameCn: "铁盔",
      nameKr: "강철 투구",
      descKr: "원거리 공격을 받아 전투 진입 시 25% 확률로 부대가 받는 모든 피해 -50%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11720,
      sourceNameCn: "不屈",
      nameKr: "불굴",
      descKr: "치명적인 피해를 1회 버티고 생명 20% 회복. 전투당 최대 1회 발동.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11748,
      sourceNameCn: "反击",
      nameKr: "반격",
      descKr: "인접한 아군 대신 물리 공격을 받는다. 공격을 받아 전투 진입 시 공격 +12%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11824,
      sourceNameCn: "璀璨的传说",
      nameKr: "찬란한 전설",
      descKr: "범위 내 모든 전설의 저편 아군의 공격·방어를 크게 올리고, 상성 관계가 없는 부대와 교전 시 피해 +15%. 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11747,
      sourceNameCn: "止水",
      nameKr: "고요",
      descKr: "인접한 아군 대신 모든 공격을 받는다. 주위 아군의 받는 치명타 확률 -30%, 원거리 피해 -15%. 사용 시 호위 2칸·지휘 3칸으로 늘어나며 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [55], note: "Legacy Korean sheet hero/data/란디우스.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5025,
      sourceNameCn: "急救",
      nameKr: "구급",
      descKr: "자신 부대 생명 100% 회복.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [66], note: "Legacy Korean sheet hero/data/클라렛.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12010,
      sourceNameCn: "乘风",
      nameKr: "바람의 기운",
      descKr: "공격 전 이동 1칸마다 물리 피해 +5%, 최대 +25%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [66], note: "Legacy Korean sheet hero/data/클라렛.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12011,
      sourceNameCn: "雷闪",
      nameKr: "번개의 일섬",
      descKr: "단일 적에게 1.6배 피해. 적 처치 시 쿨타임 -3, 처치하지 못하면 재행동하지만 주는 피해 -50%를 1턴 받는다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [66], note: "Legacy Korean sheet hero/data/클라렛.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12001,
      sourceNameCn: "逆境",
      nameKr: "역경",
      descKr: "부대 생명이 70% 이하일 때 공격·방어 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [66], note: "Legacy Korean sheet hero/data/클라렛.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12009,
      sourceNameCn: "技巧指挥",
      nameKr: "전술 지휘",
      descKr: "주위 3칸 내 아군 부대가 전투 시 기술 +20%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [66], note: "Legacy Korean sheet hero/data/클라렛.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5014,
      sourceNameCn: "坚守",
      nameKr: "사수",
      descKr: "전투 진입 시 방어 +7%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [53, 89, 115], note: "Legacy Korean sheet hero/data/란포드.js, hero/data/유리아.js, hero/data/로자리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12147,
      sourceNameCn: "庇护之剑",
      nameKr: "수호의 검",
      descKr: "목표 지형에 비호의 검을 설치해 주위 아군의 생명 외 모든 속성 +10% 지휘 효과를 3턴 부여한다. 신앙 중첩에 따라 범위와 회복 지휘가 강화되며, 신앙 보유 시 사용 후 3칸 재이동·공격 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [115], note: "Legacy Korean sheet hero/data/로자리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12148,
      sourceNameCn: "银色之矛",
      nameKr: "은색의 창",
      descKr: "단일 적에게 1.4배 피해, 마물에게 특효. 근접 병사도 함께 공격하며 비호의 검 범위에서 공격 시 전투 후 3칸 재이동 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [115], note: "Legacy Korean sheet hero/data/로자리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12149,
      sourceNameCn: "圣洁怒火",
      nameKr: "성결한 분노",
      descKr: "주위 2칸 내 모든 적에게 0.3배 범위 피해를 주고 강화 효과 2개 제거. 비호의 검 범위에서 사용하면 전투 후 3칸 재이동 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [115], note: "Legacy Korean sheet hero/data/로자리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5008,
      sourceNameCn: "进击",
      nameKr: "진격",
      descKr: "전투 진입 시 자신 부대 공격 +7%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [115], note: "Legacy Korean sheet hero/data/로자리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5005,
      sourceNameCn: "破魔",
      nameKr: "방어막 파괴",
      descKr: "전투 진입 전 50% 확률로 적의 마방 -25%, 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [51, 89], note: "Legacy Korean sheet hero/data/셀파닐.js, hero/data/유리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10116,
      sourceNameCn: "坚韧",
      nameKr: "강인함",
      descKr: "공격을 받아 전투 진입 전 자신의 방어 +5%, 1턴 지속. 중첩 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [89], note: "Legacy Korean sheet hero/data/유리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10829,
      sourceNameCn: "奉献",
      nameKr: "헌신",
      descKr: "전투 후 40% 확률로 다른 아군 부대의 생명을 최대 생명의 15%만큼 회복.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [89], note: "Legacy Korean sheet hero/data/유리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 12014,
      sourceNameCn: "圣裁",
      nameKr: "신성한 제재",
      descKr: "단일 적에게 1.6배 마법 피해. 전투 전 강화 효과 5개 제거 후 재행동 불가와 강화 효과 획득 불가를 2턴 부여하며 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [89], note: "Legacy Korean sheet hero/data/유리아.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10303,
      sourceNameCn: "冲锋",
      nameKr: "돌진",
      descKr: "공격 전 이동 1칸마다 공격 +5%, 최대 +15%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [32], note: "Legacy Korean sheet hero/data/에마링크.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5004,
      sourceNameCn: "破甲",
      nameKr: "장갑 파괴",
      descKr: "전투 진입 전 50% 확률로 적의 방어 -20%, 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [32, 53], note: "Legacy Korean sheet hero/data/에마링크.js, hero/data/란포드.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10209,
      sourceNameCn: "重盾",
      nameKr: "방패벽",
      descKr: "근접 공격을 받아 전투 진입 시 25% 확률로 부대가 받는 피해 -50%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [32], note: "Legacy Korean sheet hero/data/에마링크.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10224,
      sourceNameCn: "招架",
      nameKr: "응수",
      descKr: "인접한 아군 대신 물리 공격을 받는다. 공격을 받을 때 공격의 7%를 방어에 더한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [32], note: "Legacy Korean sheet hero/data/에마링크.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10105,
      sourceNameCn: "防御威吓",
      nameKr: "방어 위협",
      descKr: "행동 종료 시 주위 2칸 내 모든 적의 방어 -15%, 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [32], note: "Legacy Korean sheet hero/data/에마링크.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 5098,
      sourceNameCn: "心眼",
      nameKr: "심안",
      descKr: "치명타율 +15%. 전투에서 치명타가 발생하면 전투 후 적의 모든 패시브 스킬을 2턴 무효화.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [53], note: "Legacy Korean sheet hero/data/란포드.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11740,
      sourceNameCn: "连闪",
      nameKr: "연섬",
      descKr: "단일 적에게 1.4배 피해, 치명타율 +20%. 적 처치 시 쿨타임 -4. 전투 전 고정 피해 1회, 치명타 발생 시 전투 후 고정 피해 1회를 추가로 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [53], note: "Legacy Korean sheet hero/data/란포드.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11823,
      sourceNameCn: "王牌战法",
      nameKr: "조커전술",
      descKr: "범위 내 모든 전략의 대가 아군의 공격·방어를 크게 올리고, 혼합 부대일 때 전투 피해 +15%. 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [53], note: "Legacy Korean sheet hero/data/란포드.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10710,
      sourceNameCn: "干涸",
      nameKr: "고갈",
      descKr: "범위 내 적에게 0.3배 범위 피해. 50% 확률로 침묵을 2턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [51], note: "Legacy Korean sheet hero/data/셀파닐.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 6007,
      sourceNameCn: "攻击大应援",
      nameKr: "공격 대지원",
      descKr: "행동 종료 시 주위 2칸 내 다른 아군 2명의 주는 피해 +15%, 공격·지력 감소와 침묵 면역을 1턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [51], note: "Legacy Korean sheet hero/data/셀파닐.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11728,
      sourceNameCn: "破邪",
      nameKr: "파사",
      descKr: "치명타율 +15%. 범위 내 적에게 0.3배 범위 피해를 주고 강화 효과 1개 제거. 마물에게 특효.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [51], note: "Legacy Korean sheet hero/data/셀파닐.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 11820,
      sourceNameCn: "天煌圣女",
      nameKr: "하늘의 성녀",
      descKr: "범위 내 모든 공주 연맹 아군의 공격·방어를 크게 올리고, 스킬 사용 시 피해 +12%. 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [51], note: "Legacy Korean sheet hero/data/셀파닐.js; unique icon-path match within the Hero catalog and current Skill ID/CN/effect parity verified." },
    },
    {
      skillId: 10705,
      sourceNameCn: "冰冻",
      nameKr: "빙결",
      descKr: "단일 개체에게 1.5배의 피해를 준다. '창병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10703,
      sourceNameCn: "雷击",
      nameKr: "썬더",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. '기병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10706,
      sourceNameCn: "冰锥",
      nameKr: "아이스",
      descKr: "범위 내 다수의 적군에게 0.3배의 피해. '창병'에게 더 큰 피해를 준다. 적의 이동력 -1칸 및 호위 불가를 부여, 2행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10109,
      sourceNameCn: "魔防威吓",
      nameKr: "마방 위협",
      descKr: "[패시브] 행동 종료 시 주위 3칸 내 모든 적 부대 마방 -20%, 1행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10841,
      sourceNameCn: "净化",
      nameKr: "턴 언데드",
      descKr: "단일 개체에게 1.5배의 피해. '마물'에게 더 큰 피해를 준다. 전투 후 대상의 버프를 2개 제거한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10813,
      sourceNameCn: "天罚",
      nameKr: "천벌",
      descKr: "치명타 확률 +50%. 주위 5칸 내 모든 적군에게 0.35배 범위 피해를 입힌다. '마물'과 전투 시 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10711,
      sourceNameCn: "梦魇",
      nameKr: "악몽",
      descKr: "[마법 피해] 전장의 적 1부대에게 0.25배의 피해를 주고 버프를 3개 제거하며 다음 턴 행동할 수 없게 한다. 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10701,
      sourceNameCn: "火球",
      nameKr: "파이어볼",
      descKr: "단일 개체에게 1.5배의 피해. '보병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10712,
      sourceNameCn: "凋零",
      nameKr: "노화",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.3배의 광역 피해를 주며 적에게 '강화 방해'를 부여한다. 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10719,
      sourceNameCn: "封印",
      nameKr: "봉인",
      descKr: "[패시브] 적에게 피해를 줬을 경우 50% 확률로 적에게 '침묵' 부여, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 11813,
      sourceNameCn: "暗之轮舞",
      nameKr: "어둠의 윤무",
      descKr: "[초절강화] 범위 내 모든 '어둠의 윤회' 아군의 공격, 방어 능력치가 크게 상승한다. 전투 중 상대에게 디버프가 3개 이상 걸려 있을 경우 자신 부대가 주는 피해량 +15%, 4턴 지속. 다른 초절강화 스킬과 중첩 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10709,
      sourceNameCn: "大地震",
      nameKr: "어스퀘이크",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.4배의 광역 피해를 준다. '비병'에게 피해를 줄 수 없다. 적의 공격, 지력, 방어 -20%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10716,
      sourceNameCn: "暗镰",
      nameKr: "어둠의 낫",
      descKr: "단일 적에게 1.3배의 피해. 적의 마방을 30% 무시. 전투 후 준 피해량의 50%만큼 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
    {
      skillId: 10717,
      sourceNameCn: "黑洞",
      nameKr: "블랙홀",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.36배의 광역 피해를 준다. 각 부대에게 무작위 디버프를 2개씩 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
    {
      skillId: 20001,
      sourceNameCn: "召唤亡灵",
      nameKr: "망령 소환",
      descKr: "망령술사 부대를 1개 소환한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
    {
      skillId: 11708,
      sourceNameCn: "烟雾",
      nameKr: "연막",
      descKr: "선공으로 전투 진입 시 전투 후 30%의 확률로 발동, 받는 모든 피해량 -30% 지속 1행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99181], note: "Legacy Korean sheet hero/data/율리안.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11708." },
    },
    {
      skillId: 10605,
      sourceNameCn: "万箭",
      nameKr: "화살비",
      descKr: "범위 내 모든 적에게 0.3배의 범위 피해를 입힌다. '비병'을 상대할 시 더 큰 피해를 준다, 버프 1개 제거. 전투 후 3칸 재이동 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99181], note: "Legacy Korean sheet hero/data/율리안.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10605." },
    },
    {
      skillId: 10210,
      sourceNameCn: "战吼",
      nameKr: "전투 함성",
      descKr: "공격하여 전투 진입 전 적 부대의 버프 1개 제거 및 공격, 방어 -10% 지속 1행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99182], note: "Legacy Korean sheet hero/data/리키.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10210." },
    },
    {
      skillId: 11703,
      sourceNameCn: "诡步",
      nameKr: "트릭스터",
      descKr: "치명타 확률 +10%. 전투 중 적 부대를 격파 후 재이동 3칸",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99183], note: "Legacy Korean sheet hero/data/마크렌.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11703." },
    },
    {
      skillId: 5100,
      sourceNameCn: "一闪",
      nameKr: "일섬",
      descKr: "단일 개체에게 1.4배 피해 치명타율 +20%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [143], note: "Legacy Korean sheet hero/data/긴토키.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 5100." },
    },
    {
      skillId: 5021,
      sourceNameCn: "攻击应援",
      nameKr: "공격 지원",
      descKr: "행동 종료 시 인접한 아군 1부대의 공격,지력 +15% 및 면역: '공격, 지력 감소', '침묵',지속 1행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [144], note: "Legacy Korean sheet hero/data/카구라.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 5021." },
    },
    {
      skillId: 10819,
      sourceNameCn: "群体魔抗",
      nameKr: "광역 마방",
      descKr: "범위 내 아군들의 마방+30%, '기절, 강화 방해, 이동력 감소 면역 부여 지속 2행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99185], note: "Legacy Korean sheet hero/data/아단켈모.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10819." },
    },
    {
      skillId: 11780,
      sourceNameCn: "寒冰飞弹",
      nameKr: "프리즈 미사일",
      descKr: "1개의 라인에 있는 모든 적군을 공격하여 0.33배 범위 피해 '창병'에게 특효 적군의 이동력 -1 지속 2행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99185], note: "Legacy Korean sheet hero/data/아단켈모.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11780." },
    },
    {
      skillId: 10815,
      sourceNameCn: "制裁",
      nameKr: "제재",
      descKr: "[마법 피해]주위 2칸 내 모든 적에게 0.3배 범위 피해 동시에 적의 2개 버프 제거.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99184], note: "Legacy Korean sheet hero/data/빛의수호사도.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10815." },
    },
    {
      skillId: 5009,
      sourceNameCn: "血战",
      nameKr: "혈전",
      descKr: "부대의 남은 생명 비율이 적 보다 낮을 경우 전투 진입 시 공격, 방어 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99186], note: "Legacy Korean sheet hero/data/빛과그림자검의영혼.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 5009." },
    },
    {
      skillId: 10406,
      sourceNameCn: "魔防指挥",
      nameKr: "마방 지휘",
      descKr: "주위 2칸 내 모든 아군 마방 +15%",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99187], note: "Legacy Korean sheet hero/data/껍질소녀.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10406." },
    },
    {
      skillId: 10807,
      sourceNameCn: "圣疗",
      nameKr: "홀리 힐",
      descKr: "[지원]광범위 부대에게 지력 4배만큼 생명을 회복한다. 그리고 행동 종료 시 생명을 20% 회복한다. 2행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99191], note: "Legacy Korean sheet hero/data/루그너.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10807." },
    },
    {
      skillId: 11781,
      sourceNameCn: "神圣飞弹",
      nameKr: "홀리 미사일",
      descKr: "1개의 라인에 있는 모든 적군을 공격하여 0.33배 범위 피해를 입힌다. '마물'과 전투 시 더 큰 피해를 입힌다. 1개 버프 제거.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99196], note: "Legacy Korean sheet hero/data/아니에스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11781." },
    },
    {
      skillId: 10804,
      sourceNameCn: "群体护盾",
      nameKr: "광역 실드",
      descKr: "범위 내 아군들의 방어 +20%. '방어, 마방 감소','치료 방해' 면역 부여 쿨타임 2행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99196], note: "Legacy Korean sheet hero/data/아니에스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10804." },
    },
    {
      skillId: 10205,
      sourceNameCn: "剑舞",
      nameKr: "검무",
      descKr: "주위 1바퀴 내 모든 적군에게 0.36배의 범위 피해를 입힌다. 적군에게 '치료 불가' 시전, 1행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99195], note: "Legacy Korean sheet hero/data/반.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10205." },
    },
    {
      skillId: 12069,
      sourceNameCn: "雷暴空间",
      nameKr: "천둥의 공간",
      descKr: "자신 주위 3바퀴 범위내 모든 적군에게 0.33배의 범위 피해를 입힌다. '기병'과 전투 시 더큰 피해를 입힌다. 적군의 방어력 -20% 지속 2행동.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99197], note: "Legacy Korean sheet hero/data/각성자.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12069." },
    },
    {
      skillId: 11791,
      sourceNameCn: "暗龙的吹息",
      nameKr: "암룡의 숨결",
      descKr: "3개의 라인에 있는 모든 적군을 공격하여 0.36배 범위 피해를 입힌다. '승려'와 전투 시 더 큰 피해를 입힌다. 디버프 1개 랜덤 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99197], note: "Legacy Korean sheet hero/data/각성자.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11791." },
    },
    {
      skillId: 10803,
      sourceNameCn: "群体强化",
      nameKr: "광역 강화",
      descKr: "범위 내 아군들의 공격, 지력 +20%. '공격, 지력 면역','스킬 사용 불가 면역' 부여 지속 2행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99209], note: "Legacy Korean sheet hero/data/리나.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10803." },
    },
    {
      skillId: 11750,
      sourceNameCn: "魔力震荡",
      nameKr: "마력 진동",
      descKr: "범위 내 적에게 0.36배의 광역 피해 '마법사'와 '신관'에게 더 큰 피해를 주며 마방 -30% 감소 지속 2행동.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99209], note: "Legacy Korean sheet hero/data/리나.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11750." },
    },
    {
      skillId: 12081,
      sourceNameCn: "铁壁",
      nameKr: "철벽",
      descKr: "부대 생명 90% 이상 시 방어 마방 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99210], note: "Legacy Korean sheet hero/data/제르가디스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12081." },
    },
    {
      skillId: 12090,
      sourceNameCn: "加速应援",
      nameKr: "가속 지원",
      descKr: "행동 종료 시 근접한 1개 아군 부대의 이동력 +1 및 '이동력 저하 면역','치료 저하 면역' 쿨타임 1행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99212], note: "Legacy Korean sheet hero/data/강신자.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12090." },
    },
    {
      skillId: 5012,
      sourceNameCn: "死斗",
      nameKr: "사투",
      descKr: "전투 진입 시 부대 공격, 기술 +12%, 방어, 마방 -7%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99215], note: "Legacy Korean sheet hero/data/안드리올.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 5012." },
    },
    {
      skillId: 10603,
      sourceNameCn: "瞄准",
      nameKr: "조준",
      descKr: "사용 후 부대가 주는 피해량 +10% 지속 1행동 사용 후 재행동 2칸 가능",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99214], note: "Legacy Korean sheet hero/data/네미아.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10603." },
    },
    {
      skillId: 10702,
      sourceNameCn: "陨石",
      nameKr: "메테오",
      descKr: "범위 내 적에게 0.36배의 피해 '보병'에게 더 큰 피해를 준다. 행동 종료 시 생명 20% 감소",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99219], note: "Legacy Korean sheet hero/data/제이스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10702." },
    },
    {
      skillId: 10713,
      sourceNameCn: "酸蚀",
      nameKr: "부식",
      descKr: "범위 내 적에게 0.3배의 광역 피해 및 적에게 '치료 방해'부여, 2행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99220], note: "Legacy Korean sheet hero/data/페트리시아.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10713." },
    },
    {
      skillId: 11788,
      sourceNameCn: "众志",
      nameKr: "모두의 의지",
      descKr: "주위 2칸 내 아군이 1명씩 있을 경우, 방어, 마방 +5%, 최대 +15%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99223], note: "Legacy Korean sheet hero/data/쇼우.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11788." },
    },
    {
      skillId: 12102,
      sourceNameCn: "冰龙的吹息",
      nameKr: "빙룡의 숨결",
      descKr: "3개의 직선 상의 모든 적군에게 0.36배 범위 피해를 입히며 이동력 -1 부여, 지속 2 '창병'에게 더 큰 피해를 입힌다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99225], note: "Legacy Korean sheet hero/data/얼어붙은심연의지배자.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12102." },
    },
    {
      skillId: 10418,
      sourceNameCn: "御风",
      nameKr: "바람 타기",
      descKr: "[패시브]생명이 50% 이상인 경우 전투 진입시 받는 모든 피해량 -15%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99227], note: "Legacy Korean sheet hero/data/타브리스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10418." },
    },
    {
      skillId: 5013,
      sourceNameCn: "致命",
      nameKr: "치명",
      descKr: "[패시브]공격하여 전투 진입 시 공격 +12%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99230], note: "Legacy Korean sheet hero/data/세라피나.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 5013." },
    },
    {
      skillId: 12668,
      sourceNameCn: "辉耀惩戒",
      nameKr: "빛의 징벌",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. 전투 후 준 피해량의 20%만큼 생명을 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99232], note: "Legacy Korean sheet hero/data/빛의소환사.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12668." },
    },
    {
      skillId: 12669,
      sourceNameCn: "辉耀救赎",
      nameKr: "빛의 구원",
      descKr: "[마법 피해]단일 적 부대를 공격해 1.5배의 피해를 준다. 전투 후 모든 다른 아군의 생명을 회복시킨다. 회복량은 자신 지력의 2배.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99232], note: "Legacy Korean sheet hero/data/빛의소환사.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12669." },
    },
    {
      skillId: 12671,
      sourceNameCn: "光辉神剑",
      nameKr: "빛의 신검",
      descKr: "단일 개체 1.4배 피해. 근접 전투 진입 시, 전투 전 적 버프 3개 제거 전투 후 재이동 3칸 원거리 전투 진입 시, 해당 스킬 쿨타임 -1 근거리 병사 대동 시 병사도 함께 공격 해당 스킬은 근접전 패널티 영향을 받지 않음",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99233], note: "Legacy Korean sheet hero/data/시온.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12671." },
    },
    {
      skillId: 12675,
      sourceNameCn: "先制刃袭",
      nameKr: "그림자의 검",
      descKr: "일직선 상 처음 맞는 적에게 0.3배 피해. 사용 후 자신은 '선제기습' 효과 획득 선제기습: 전투 진입 시 부대 피해 +20% 및 선제공격 전투 전 부대 생명 20% 회복, 지속 2행동",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99234], note: "Legacy Korean sheet hero/data/티아나.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12675." },
    },
    {
      skillId: 12979,
      sourceNameCn: "雷光链",
      nameKr: "번개 사슬",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. '기병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99240], note: "Legacy Korean sheet hero/data/사프린.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 12979." },
    },
    {
      skillId: 10704,
      sourceNameCn: "闪电风暴",
      nameKr: "썬더스톰",
      descKr: "범위 내 적들을 공격해 0.3배의 광역 피해를 준다. '기병'에게 더 큰 피해를 주며 적의 방어 -20%, 2행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99240], note: "Legacy Korean sheet hero/data/사프린.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10704." },
    },
    {
      skillId: 10602,
      sourceNameCn: "神射",
      nameKr: "신의 사수",
      descKr: "[물리 피해] 단일 적을 1.3배 피해로 공격, '비병'과 전투 시 더큰 피해를 준다. 전투 전 피해 +30%, 전투 후 적에게 버프 불가 부여, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99243], note: "Legacy Korean sheet hero/data/히비스커스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10602." },
    },
    {
      skillId: 11719,
      sourceNameCn: "绝闪",
      nameKr: "절섬",
      descKr: "[물리 피해]호위를 무시하고 단일 적 부대를 공격해 1.3배의 피해를 준다. 전투 전 상대가 가진 버프를 최대 2개 뺏어온다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99243], note: "Legacy Korean sheet hero/data/히비스커스.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 11719." },
    },
    {
      skillId: 10214,
      sourceNameCn: "剑气",
      nameKr: "검기",
      descKr: "[패시브]공격하여 전투 후 주위 1칸 범위 내 모든 적군에게0.1배 범위 피해를 입힌다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99250], note: "Legacy Korean sheet hero/data/솀.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10214." },
    },
    {
      skillId: 10410,
      sourceNameCn: "风压",
      nameKr: "풍압",
      descKr: "[패시브]다른 부대에게 피해를 준 후 주위 2칸 내 적에게 0.1배의 광역 피해를 주고 50%의 확률로 각 대상에게 무작위 디버프를 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99254], note: "Legacy Korean sheet hero/data/레아.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 10410." },
    },
    {
      skillId: 13076,
      sourceNameCn: "​​猎讯追击",
      nameKr: "사냥과 추격",
      descKr: "단일 개체 1.5배 피해 전투 후 위치 이동 효과 발동 위치 이동: 목표를 3칸 밀치고, 밀쳐지는 경로에 다른 부대나 진입 불가 지형이 있을 경우 자신이 소환한 전투 아룡 또한 대상을 2회 공격 해당 전투에서 (전투 아룡의) 공격 +20%",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [99263], note: "Legacy Korean sheet hero/data/시벨리.js; exact Hero CN + icon + metadata/effect parity against current generated Skill 13076." },
    },
    {
      skillId: 5023,
      sourceNameCn: "魔防应援",
      nameKr: "마방 지원",
      descKr: "행동 종료 시 인접한 아군 1명의 마방 +20%, 기절·강화 방해·이동력 감소 면역 부여, 1턴 지속.",
      status: "CONFIRMED_KR",
      source: { type: "manual-review", heroIds: [5, 22, 30, 56, 91, 134, 99184, 99191, 99203], note: "Korean-server in-game wording/effect manually verified; current generated Skill 5023 ID/CN/effect cross-checked. Legacy +30% records are not reused." },
    },
    {
      skillId: 6003,
      sourceNameCn: "强化",
      nameKr: "강화",
      descKr: "단일 아군의 공격, 지력 +20%. 공격·지력 감소와 침묵에 면역, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [5], note: "Legacy Korean sheet hero/data/크리스.js; exact Hero CN + canonical icon + type/cooldown/range/target/effect parity against current generated Skill 6003." },
    },
    {
      skillId: 10714,
      sourceNameCn: "遗忘",
      nameKr: "망각",
      descKr: "범위 내 적에게 0.3배의 광역 피해를 주고 모든 패시브 스킬을 무효화한다. 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [13], note: "Legacy Korean sheet hero/data/헤인.js; exact Hero CN + canonical icon + type/cooldown/range/area/effect parity against current generated Skill 10714." },
    },
    {
      skillId: 11710,
      sourceNameCn: "偷袭",
      nameKr: "기습",
      descKr: "전투 중 치명타가 발생하면 전투 후 적에게 영웅 공격의 2배만큼 고정 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [27], note: "Legacy Korean sheet hero/data/디하르트.js; exact Hero CN + canonical icon + passive/effect parity against current generated Skill 11710." },
    },
    {
      skillId: 11723,
      sourceNameCn: "背刺",
      nameKr: "백스탭",
      descKr: "공격하여 전투 진입 시 대상 부대 생명이 100%라면 전투 전 영웅 공격의 2배만큼 고정 피해를 1회 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [28], note: "Legacy Korean sheet hero/data/젤다.js; exact Hero CN + canonical icon + passive/effect parity against current generated Skill 11723." },
    },
    {
      skillId: 10802,
      sourceNameCn: "群体治疗",
      nameKr: "매스 힐",
      descKr: "범위 내 아군들의 생명을 시전자 지력의 3배만큼 회복하고 디버프 1개를 제거한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10802." },
    },
    {
      skillId: 10801,
      sourceNameCn: "治疗术",
      nameKr: "힐",
      descKr: "단일 아군의 생명을 시전자 지력의 5배만큼 회복하고 디버프 1개를 제거한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10801." },
    },
    {
      skillId: 6004,
      sourceNameCn: "护盾",
      nameKr: "프로텍션",
      descKr: "단일 아군의 방어 +20%. 방어·마방 감소와 치료 방해에 면역, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 6004." },
    },
    {
      skillId: 10708,
      sourceNameCn: "龙卷风",
      nameKr: "토네이도",
      descKr: "범위 내 적에게 0.3배의 마법 피해를 주며 비병에게 더 큰 피해를 준다. 공격, 지력 -20%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10708." },
    },
    {
      skillId: 6005,
      sourceNameCn: "魔抗",
      nameKr: "레지스트",
      descKr: "단일 아군의 마방 +30%. 기절·강화 방해·이동력 감소에 면역, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 6005." },
    },
    {
      skillId: 12046,
      sourceNameCn: "圣龙的吹息",
      nameKr: "성룡의 숨결",
      descKr: "3개의 직선 상 모든 적에게 0.36배 범위 피해를 주며 마물에게 더 큰 피해를 준다. 버프 1개 제거.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [4], note: "Legacy Korean sheet hero/data/아멜다.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 12046." },
    },
    {
      skillId: 10305,
      sourceNameCn: "攻击指挥",
      nameKr: "공격 지휘",
      descKr: "주위 2칸 내 모든 아군의 공격, 지력 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10305." },
    },
    {
      skillId: 10403,
      sourceNameCn: "风语",
      nameKr: "바람의 분노",
      descKr: "주위 1칸 내 모든 적에게 0.3배 범위 피해를 주고 각 대상에게 무작위 디버프를 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10403." },
    },
    {
      skillId: 10204,
      sourceNameCn: "阳影",
      nameKr: "태양광",
      descKr: "근접 공격으로 전투 진입 시 전투 후 30% 확률로 이번 전투에서 준 피해의 30%만큼 생명을 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10204." },
    },
    {
      skillId: 10306,
      sourceNameCn: "再移动",
      nameKr: "재이동",
      descKr: "공격하여 전투 진입 시 주는 피해 +10%. 남은 이동력이 있으면 공격 후 다시 이동할 수 있다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10306." },
    },
    {
      skillId: 5028,
      sourceNameCn: "野战",
      nameKr: "야전",
      descKr: "이동 시 통과 가능한 모든 지형을 평지로 취급한다. 현재 지형에 방어 상승 효과가 있으면 공격도 같은 수치만큼 상승한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 5028." },
    },
    {
      skillId: 10606,
      sourceNameCn: "迂回",
      nameKr: "우회",
      descKr: "공격하여 전투 진입 시 주는 피해 +10%. 전투 후 다시 2칸 이동할 수 있으며 재이동 효과는 1턴 간격으로 발동한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [1], note: "Legacy Korean sheet hero/data/매튜.js; exact Hero CN + type/cooldown/range/area/effect parity against current generated Skill 10606." },
    },
  ],
};
