export const HERO_JOB_LOCALIZATION_PART_8 = [
  [20220, { nameCn: "S级魔导士", nameKr: "S급 마도사", status: "CONFIRMED_KR" }],
  [20221, { nameCn: "妖精女王", nameKr: "요정 여왕", status: "CONFIRMED_KR" }],
  [20222, { nameCn: "第七任会长", nameKr: "7대 마스터", status: "CONFIRMED_KR" }],
  [20223, { nameCn: "铁腕领主", nameKr: "철완 영주", status: "CONFIRMED_KR" }],
  [20224, { nameCn: "重刃皇女", nameKr: "무쇠검의 황녀", status: "CONFIRMED_KR" }],
  [20225, { nameCn: "无冕帝皇", nameKr: "무관의 제왕", status: "CONFIRMED_KR" }],
  [20226, { nameCn: "兽语者", nameKr: "비스트 테이머", status: "CONFIRMED_KR" }],
  [20227, { nameCn: "驭龙鞭刃", nameKr: "드래곤 테이머", status: "CONFIRMED_KR" }],
  [20228, { nameCn: "荒原兽主", nameKr: "황야의 테이머", status: "CONFIRMED_KR" }],
  [20230, { nameCn: "斗剑少年", nameKr: "검투 소년", status: "CONFIRMED_KR" }],
  [20231, { nameCn: "破枷勇者", nameKr: "속박에서 벗어난 용사", status: "CONFIRMED_KR" }],
  [20232, { nameCn: "圣辉王子", nameKr: "성휘 왕자", status: "CONFIRMED_KR" }],
  [20233, { nameCn: "影子女士", nameKr: null, status: "UNRELEASED_KR" }],
  [20234, { nameCn: "狩魂影刃", nameKr: null, status: "UNRELEASED_KR" }],
  [20235, { nameCn: "寂夜影主", nameKr: null, status: "UNRELEASED_KR" }],
  [20236, { nameCn: "异时剑客", nameKr: null, status: "UNRELEASED_KR" }],
  [20237, { nameCn: "剑骸斗士", nameKr: null, status: "UNRELEASED_KR" }],
  [20238, { nameCn: "剑骸使者", nameKr: null, status: "UNRELEASED_KR" }],
  [20239, { nameCn: "独行利刃", nameKr: null, status: "UNRELEASED_KR" }],
  [20240, { nameCn: "圣园学员", nameKr: null, status: "UNRELEASED_KR" }],
  [20241, { nameCn: "逆命剑姬", nameKr: null, status: "UNRELEASED_KR" }],
  [20242, { nameCn: "绝命天使", nameKr: null, status: "UNRELEASED_KR" }],
  [20244, { nameCn: "天空界神族", nameKr: null, status: "UNRELEASED_KR" }],
  [20245, { nameCn: "阿修罗神军", nameKr: null, status: "UNRELEASED_KR" }],
  [20246, { nameCn: "夜叉王", nameKr: null, status: "UNRELEASED_KR" }],
  [20247, { nameCn: "天空界神族", nameKr: null, status: "UNRELEASED_KR" }],
  [20301, { nameCn: "逆理者", nameKr: "이치의 반역자", status: "CONFIRMED_KR" }],
  [20302, { nameCn: "定衡者", nameKr: "균형 정립자", status: "CONFIRMED_KR" }],
  [20303, { nameCn: "旅时魔骑", nameKr: null, status: "UNRELEASED_KR" }],
  [20304, { nameCn: "掠界狂影", nameKr: null, status: "UNRELEASED_KR" }],
  [20305, { nameCn: "岩铠战兽", nameKr: null, status: "UNRELEASED_KR" }],
  [20306, { nameCn: "千峰怒神", nameKr: null, status: "UNRELEASED_KR" }],
  [20701, { nameCn: "年轻的炼金术士", nameKr: "젊은 연금술사", status: "CONFIRMED_KR" }],
  [20702, { nameCn: "奇想炼金士", nameKr: "기발한 연금술사", status: "CONFIRMED_KR" }],
  [20703, { nameCn: "大炼金术士", nameKr: "대 연금술사", status: "CONFIRMED_KR" }],
  [20704, { nameCn: "圣园学员", nameKr: "성원 학도", status: "CONFIRMED_KR" }],
  [20705, { nameCn: "复兴使徒", nameKr: "부흥의 사도", status: "CONFIRMED_KR" }],
  [20706, { nameCn: "辉光天使", nameKr: "휘광 천사", status: "CONFIRMED_KR" }],
  [20708, { nameCn: "风驭术士", nameKr: null, status: "UNRELEASED_KR" }],
  [20709, { nameCn: "罡风御主", nameKr: null, status: "UNRELEASED_KR" }],
  [20710, { nameCn: "见习学者", nameKr: null, status: "UNRELEASED_KR" }],
  [20711, { nameCn: "资深学者", nameKr: null, status: "UNRELEASED_KR" }],
  [20712, { nameCn: "比拉德大导师", nameKr: null, status: "UNRELEASED_KR" }],
  [20713, { nameCn: "金牌销售", nameKr: null, status: "UNRELEASED_KR" }],
  [20714, { nameCn: "理财传说", nameKr: null, status: "UNRELEASED_KR" }],
  [20715, { nameCn: "魔剑容器", nameKr: null, status: "UNRELEASED_KR" }],
  [20716, { nameCn: "魔剑使者", nameKr: null, status: "UNRELEASED_KR" }],
  [20717, { nameCn: "魔剑主宰", nameKr: null, status: "UNRELEASED_KR" }],
  [20801, { nameCn: "辉耀神眷使", nameKr: "찬란한 빛의 전령사", status: "CONFIRMED_KR" }],
  [20802, { nameCn: "始祖妖精", nameKr: "태초의 엘프", status: "CONFIRMED_KR" }],
  [20803, { nameCn: "星之圣者", nameKr: "별의 세인트", status: "CONFIRMED_KR" }],
  [20804, { nameCn: "星之女王", nameKr: "별의 여왕", status: "CONFIRMED_KR" }],
  [20805, { nameCn: "幸运星", nameKr: "행운의 별", status: "CONFIRMED_KR" }],
  [20806, { nameCn: "神眷者", nameKr: "신의 아이", status: "CONFIRMED_KR" }],
  [20807, { nameCn: "通灵巫女", nameKr: "영혼의 무녀", status: "CONFIRMED_KR" }],
  [20808, { nameCn: "神运圣女", nameKr: "천운의 성녀", status: "CONFIRMED_KR" }],
  [20809, { nameCn: "自然学者", nameKr: "자연 학자", status: "CONFIRMED_KR" }],
  [20810, { nameCn: "自然共鸣者", nameKr: "자연과 공명하는 자", status: "CONFIRMED_KR" }],
  [20812, { nameCn: "星舞者", nameKr: "별의 무희", status: "CONFIRMED_KR" }],
  [20813, { nameCn: "幻梦舞姬", nameKr: "환상의 무희", status: "CONFIRMED_KR" }],
  [20814, { nameCn: "灭龙魔导士", nameKr: "멸룡 마도사", status: "CONFIRMED_KR" }],
  [20815, { nameCn: "武者", nameKr: "무사", status: "CONFIRMED_KR" }],
  [20816, { nameCn: "疾影斗焰", nameKr: "불꽃의 격투", status: "CONFIRMED_KR" }],
  [20817, { nameCn: "炽天之阳", nameKr: "눈부신 태양", status: "CONFIRMED_KR" }],
  [20818, { nameCn: "元素巫祭", nameKr: "원소 제사장", status: "CONFIRMED_KR" }],
  [20819, { nameCn: "万灵使者", nameKr: "만령 사자", status: "CONFIRMED_KR" }],
  [20820, { nameCn: "天国术师", nameKr: "천국 술사", status: "CONFIRMED_KR" }],
  [20821, { nameCn: "弑神天使", nameKr: "갓 킬러 천사", status: "CONFIRMED_KR" }],
  [20822, { nameCn: "听风者", nameKr: null, status: "UNRELEASED_KR" }],
  [20823, { nameCn: "祈风圣使", nameKr: null, status: "UNRELEASED_KR" }],
  [20824, { nameCn: "山罡向导", nameKr: null, status: "UNRELEASED_KR" }],
  [20825, { nameCn: "投资新手", nameKr: null, status: "UNRELEASED_KR" }],
  [20826, { nameCn: "操盘达人", nameKr: null, status: "UNRELEASED_KR" }],
  [20827, { nameCn: "天使投资人", nameKr: null, status: "UNRELEASED_KR" }],
  [20828, { nameCn: "天空界神族", nameKr: null, status: "UNRELEASED_KR" }],
  [20829, { nameCn: "修罗王", nameKr: null, status: "UNRELEASED_KR" }],
  [20830, { nameCn: "梵天继承者", nameKr: null, status: "UNRELEASED_KR" }],
  [201001, { nameCn: "临渊者", nameKr: "심연의 인도자", status: "CONFIRMED_KR" }],
  [201002, { nameCn: "魔渊统领", nameKr: "마계의 지도자", status: "CONFIRMED_KR" }],
  [201003, { nameCn: "魔渊主宰", nameKr: "마계의 주인", status: "CONFIRMED_KR" }],
  [201004, { nameCn: "无厌之火", nameKr: "탐욕의 화염", status: "CONFIRMED_KR" }],
  [201005, { nameCn: "噬界狂炎", nameKr: "잠식의 광염", status: "CONFIRMED_KR" }],
  [201006, { nameCn: "唤灵者", nameKr: "영혼 소환사", status: "CONFIRMED_KR" }],
  [201007, { nameCn: "战魄斗士", nameKr: "전혼 투사", status: "CONFIRMED_KR" }],
  [201008, { nameCn: "凝魂萨满", nameKr: "혼령 주술사", status: "CONFIRMED_KR" }],
  [201009, { nameCn: "血手仔熊", nameKr: null, status: "UNRELEASED_KR" }],
  [201010, { nameCn: "山林守望", nameKr: null, status: "UNRELEASED_KR" }],
  [201011, { nameCn: "森罗霸主", nameKr: null, status: "UNRELEASED_KR" }],
  [201012, { nameCn: "赤色战栗", nameKr: null, status: "UNRELEASED_KR" }],
  [201013, { nameCn: "暗怖骑士", nameKr: null, status: "UNRELEASED_KR" }],
  [201014, { nameCn: "绝末魔神", nameKr: null, status: "UNRELEASED_KR" }],
  [201015, { nameCn: "颂暗使徒", nameKr: null, status: "UNRELEASED_KR" }],
  [201016, { nameCn: "黑暗天使", nameKr: null, status: "UNRELEASED_KR" }],
  [201017, { nameCn: "暗之神剑士", nameKr: null, status: "UNRELEASED_KR" }],
  [201018, { nameCn: "混沌帝王", nameKr: null, status: "UNRELEASED_KR" }],
  [201019, { nameCn: "唤魔剑使", nameKr: null, status: "UNRELEASED_KR" }],
  [201020, { nameCn: "堕夜剑魔", nameKr: null, status: "UNRELEASED_KR" }],
] as const;
