export const HERO_FINAL_JOB_LOCALIZATION_PART_3 = [
  [783, { nameCn: "永序之誓", nameKr: "영원한 서약", status: "CONFIRMED_KR" }],
  [786, { nameCn: "元素召灵使", nameKr: "원소 소환사", status: "CONFIRMED_KR" }],
  [789, { nameCn: "深海复仇者", nameKr: "심해의 복수자", status: "CONFIRMED_KR" }],
  [791, { nameCn: "遂梦之誓", nameKr: "꿈을 이루는 서약", status: "CONFIRMED_KR" }],
  [794, { nameCn: "星灵衣之主", nameKr: "스타드레스의 주인", status: "CONFIRMED_KR" }],
  [797, { nameCn: "庇灵之誓言", nameKr: "수호령의 서약", status: "CONFIRMED_KR" }],
  [808, { nameCn: "神使", nameKr: "오라클", status: "CONFIRMED_KR" }],
  [809, { nameCn: "圣骑统帅", nameKr: "템플러", status: "CONFIRMED_KR" }],
  [810, { nameCn: "圣者", nameKr: "세인트", status: "CONFIRMED_KR" }],
  [811, { nameCn: "先知", nameKr: "프로핏", status: "CONFIRMED_KR" }],
  [812, { nameCn: "女武神", nameKr: "발키리", status: "CONFIRMED_KR" }],
  [813, { nameCn: "公主", nameKr: "프린세스", status: "CONFIRMED_KR" }],
  [814, { nameCn: "圣女骑士", nameKr: "세인트 나이트", status: "CONFIRMED_KR" }],
  [818, { nameCn: "王女", nameKr: "프린세스", status: "CONFIRMED_KR" }],
  [819, { nameCn: "皇家特使", nameKr: "로열 엔보이", status: "CONFIRMED_KR" }],
  [821, { nameCn: "利贝尔女王", nameKr: "리벨 여왕", status: "CONFIRMED_KR" }],
  [823, { nameCn: "木贤者", nameKr: "아바탈", status: "CONFIRMED_KR" }],
  [826, { nameCn: "军师", nameKr: "군사", status: "CONFIRMED_KR" }],
  [828, { nameCn: "梦幻之吻", nameKr: "초능력 소녀", status: "CONFIRMED_KR" }],
  [830, { nameCn: "圣剑公主", nameKr: "성검의 공주", status: "CONFIRMED_KR" }],
  [832, { nameCn: "灵界侦探", nameKr: "영계탐정", status: "CONFIRMED_KR" }],
  [835, { nameCn: "影依圣女", nameKr: "다크 세인트", status: "CONFIRMED_KR" }],
  [837, { nameCn: "钢之圣女", nameKr: "강철의 성녀", status: "CONFIRMED_KR" }],
  [839, { nameCn: "银骑统帅", nameKr: "백은의 발키리", status: "CONFIRMED_KR" }],
  [840, { nameCn: "大贤者", nameKr: "대현자", status: "CONFIRMED_KR" }],
  [843, { nameCn: "灵光圣女", nameKr: "영광의 성녀", status: "CONFIRMED_KR" }],
  [846, { nameCn: "异端裁决者", nameKr: "인퀴지터", status: "CONFIRMED_KR" }],
  [848, { nameCn: "赐圣僧侣", nameKr: "홀리 프리스트", status: "CONFIRMED_KR" }],
  [850, { nameCn: "血晶支配者", nameKr: "핏빛 수정의 지배자", status: "CONFIRMED_KR" }],
  [852, { nameCn: "烈火之仁", nameKr: "열화의 료", status: "CONFIRMED_KR" }],
  [854, { nameCn: "天空之智", nameKr: "천공의 지", status: "CONFIRMED_KR" }],
  [856, { nameCn: "净地末裔", nameKr: "카오스의 후예", status: "CONFIRMED_KR" }],
  [857, { nameCn: "大主教", nameKr: "대주교", status: "CONFIRMED_KR" }],
  [861, { nameCn: "万灵之初诞", nameKr: "모든 영혼의 시조", status: "CONFIRMED_KR" }],
  [863, { nameCn: "眼镜之主", nameKr: "안경이 본체", status: "CONFIRMED_KR" }],
  [866, { nameCn: "原初祈求者", nameKr: "태초의 기도사", status: "CONFIRMED_KR" }],
  [868, { nameCn: "方舟总帅", nameKr: "방주 총사령관", status: "CONFIRMED_KR" }],
  [871, { nameCn: "灵宗首席", nameKr: "영종의 지도자", status: "CONFIRMED_KR" }],
  [873, { nameCn: "驱灵尊者", nameKr: "소울마스터 존자", status: "CONFIRMED_KR" }],
  [875, { nameCn: "月之贤人", nameKr: "달의 현인", status: "CONFIRMED_KR" }],
  [877, { nameCn: "战颂舞姬", nameKr: "전쟁의 무희", status: "CONFIRMED_KR" }],
  [881, { nameCn: "圣护使徒", nameKr: "신성의 사도", status: "CONFIRMED_KR" }],
  [883, { nameCn: "触灵行者", nameKr: "소울 워커", status: "CONFIRMED_KR" }],
  [885, { nameCn: "未世的祈颂", nameKr: "미래의 송가", status: "CONFIRMED_KR" }],
  [887, { nameCn: "圣扉之钥", nameKr: "성문의 열쇠", status: "CONFIRMED_KR" }],
  [890, { nameCn: "辉耀的圣裁", nameKr: "성스러운 빛의 심판관", status: "CONFIRMED_KR" }],
  [892, { nameCn: "贯时神珀", nameKr: "시간을 달리는 자", status: "CONFIRMED_KR" }],
  [894, { nameCn: "命扉圣者", nameKr: "운명의 문 수호자", status: "CONFIRMED_KR" }],
  [896, { nameCn: "格致者", nameKr: "탐구자", status: "CONFIRMED_KR" }],
  [903, { nameCn: "黑暗王子", nameKr: "다크 프린스", status: "CONFIRMED_KR" }],
  [1003, { nameCn: "死神领主", nameKr: "데스 로드", status: "CONFIRMED_KR" }],
  [1007, { nameCn: "混沌化身", nameKr: "디스오더", status: "CONFIRMED_KR" }],
  [1010, { nameCn: "幻影魔姬", nameKr: "미라지 퀸", status: "CONFIRMED_KR" }],
  [1014, { nameCn: "魔神", nameKr: "마신", status: "CONFIRMED_KR" }],
  [1015, { nameCn: "血魔姬", nameKr: "블러드 엠프레스", status: "CONFIRMED_KR" }],
  [1017, { nameCn: "歼灭天使", nameKr: "섬멸천사", status: "CONFIRMED_KR" }],
  [1019, { nameCn: "魔界王选", nameKr: "마족의 왕", status: "CONFIRMED_KR" }],
  [1021, { nameCn: "邪王炎杀", nameKr: "사왕염살", status: "CONFIRMED_KR" }],
  [1024, { nameCn: "前世之力", nameKr: "전생의 힘", status: "CONFIRMED_KR" }],
  [1026, { nameCn: "力·100%", nameKr: "파워 100%", status: "CONFIRMED_KR" }],
  [1028, { nameCn: "魔王化身", nameKr: "마왕의 화신", status: "CONFIRMED_KR" }],
  [1030, { nameCn: "死之统治者", nameKr: "오버로드", status: "CONFIRMED_KR" }],
  [1033, { nameCn: "真祖", nameKr: "진조", status: "CONFIRMED_KR" }],
  [1035, { nameCn: "暗黑骑士", nameKr: "다크 나이트", status: "CONFIRMED_KR" }],
  [1037, { nameCn: "邪神之翼", nameKr: "사신의 날개", status: "CONFIRMED_KR" }],
  [1040, { nameCn: "邪神", nameKr: "사신", status: "CONFIRMED_KR" }],
  [1043, { nameCn: "循梦者", nameKr: "꿈을 쫓는 자", status: "CONFIRMED_KR" }],
  [1046, { nameCn: "终极素体", nameKr: "궁극의 클론", status: "CONFIRMED_KR" }],
  [1048, { nameCn: "全世之坏灭", nameKr: "속세의 종언", status: "CONFIRMED_KR" }],
  [1051, { nameCn: "混沌代行者", nameKr: "혼돈의 대행자", status: "CONFIRMED_KR" }],
  [1053, { nameCn: "断末魔之主", nameKr: "단말마의 주인", status: "CONFIRMED_KR" }],
  [1055, { nameCn: "辉黯使者", nameKr: "빛과 어둠의 사자", status: "CONFIRMED_KR" }],
  [1058, { nameCn: "死灵之械", nameKr: "데스 메카닉", status: "CONFIRMED_KR" }],
  [1060, { nameCn: "魔剑具象", nameKr: "알하자드 형상", status: "CONFIRMED_KR" }],
  [1062, { nameCn: "死灵君王", nameKr: "사령의 군왕", status: "CONFIRMED_KR" }],
  [1064, { nameCn: "黎之魔王", nameKr: "그렌델", status: "CONFIRMED_KR" }],
  [1066, { nameCn: "渊狱召现者", nameKr: "지옥 소환자", status: "CONFIRMED_KR" }],
  [1069, { nameCn: "终焉之神降", nameKr: "종말 신의 강림", status: "CONFIRMED_KR" }],
  [1072, { nameCn: "白狼王", nameKr: "백랑 왕", status: "CONFIRMED_KR" }],
  [1075, { nameCn: "孤高的超王", nameKr: "고고한 초왕", status: "CONFIRMED_KR" }],
  [1078, { nameCn: "光暗主宰", nameKr: "빛과 어둠의 지배자", status: "CONFIRMED_KR" }],
  [1081, { nameCn: "炎狱掌控者", nameKr: "염옥의 지배자", status: "CONFIRMED_KR" }],
  [1083, { nameCn: "匣梦枭魔", nameKr: "상자 속 악마", status: "CONFIRMED_KR" }],
  [1086, { nameCn: "梦之女王", nameKr: "꿈의 여왕", status: "CONFIRMED_KR" }],
  [1088, { nameCn: "碎刃战皇", nameKr: "전쟁의 황제", status: "CONFIRMED_KR" }],
  [1091, { nameCn: "攫命惑心者", nameKr: "유혹의 살인자", status: "CONFIRMED_KR" }],
] as const;
