export const HERO_FINAL_JOB_LOCALIZATION_PART_1 = [
  [104, { nameCn: "大元帅", nameKr: "마샬", status: "CONFIRMED_KR" }],
  [105, { nameCn: "皇家卫士", nameKr: "로열 가디언", status: "CONFIRMED_KR" }],
  [107, { nameCn: "樱花无双", nameKr: "앵화무쌍", status: "CONFIRMED_KR" }],
  [108, { nameCn: "烈波无双", nameKr: "열파무쌍", status: "CONFIRMED_KR" }],
  [110, { nameCn: "凤凰之舞", nameKr: "봉황의 춤", status: "CONFIRMED_KR" }],
  [112, { nameCn: "灵枪斗士", nameKr: "불굴의 파이터", status: "CONFIRMED_KR" }],
  [115, { nameCn: "圣枪统帅", nameKr: "할버드 마스터", status: "CONFIRMED_KR" }],
  [117, { nameCn: "斗神", nameKr: "투신", status: "CONFIRMED_KR" }],
  [118, { nameCn: "枪之圣女", nameKr: "창의 성녀", status: "CONFIRMED_KR" }],
  [120, { nameCn: "诅咒骑士", nameKr: "커스드 나이트", status: "CONFIRMED_KR" }],
  [122, { nameCn: "战王丸", nameKr: "센오마루", status: "CONFIRMED_KR" }],
  [123, { nameCn: "紫晶统帅", nameKr: "에머시스트 마스터", status: "CONFIRMED_KR" }],
  [126, { nameCn: "星海公主", nameKr: "별바다의 히로인", status: "CONFIRMED_KR" }],
  [131, { nameCn: "魔铠斗将改", nameKr: "마갑 대장군 · 개", status: "CONFIRMED_KR" }],
  [134, { nameCn: "漆黑皇女", nameKr: "칠흑의 황녀", status: "CONFIRMED_KR" }],
  [137, { nameCn: "翼盾元帅", nameKr: "아이언윙 마샬", status: "CONFIRMED_KR" }],
  [140, { nameCn: "护世天秤", nameKr: "수호의 저울", status: "CONFIRMED_KR" }],
  [143, { nameCn: "龙火战将", nameKr: "화룡장군", status: "CONFIRMED_KR" }],
  [145, { nameCn: "终啼之枪", nameKr: null, status: "UNRELEASED_KR" }],
  [204, { nameCn: "剑士统帅", nameKr: "소드 마스터", status: "CONFIRMED_KR" }],
  [205, { nameCn: "皇帝", nameKr: "엠퍼러", status: "CONFIRMED_KR" }],
  [206, { nameCn: "英雄", nameKr: "영웅", status: "CONFIRMED_KR" }],
  [207, { nameCn: "剑圣", nameKr: "검성", status: "CONFIRMED_KR" }],
  [208, { nameCn: "勇者", nameKr: "용사", status: "CONFIRMED_KR" }],
  [209, { nameCn: "王者", nameKr: "킹", status: "CONFIRMED_KR" }],
  [211, { nameCn: "修罗", nameKr: "수라", status: "CONFIRMED_KR" }],
  [212, { nameCn: "剑帝", nameKr: "검제", status: "CONFIRMED_KR" }],
  [214, { nameCn: "剑斗统帅", nameKr: "배틀 마스터", status: "CONFIRMED_KR" }],
  [215, { nameCn: "盾剑统帅", nameKr: "가디언 마스터", status: "CONFIRMED_KR" }],
  [217, { nameCn: "破邪剑征", nameKr: "파사의 혈통", status: "CONFIRMED_KR" }],
  [218, { nameCn: "剑姬", nameKr: "소드 프린세스", status: "CONFIRMED_KR" }],
  [221, { nameCn: "女神之刃", nameKr: "여신의 검", status: "CONFIRMED_KR" }],
  [224, { nameCn: "灵剑斗将", nameKr: "차원도 각성자", status: "CONFIRMED_KR" }],
  [226, { nameCn: "皇后", nameKr: "엠프리스", status: "CONFIRMED_KR" }],
  [229, { nameCn: "精灵剑士", nameKr: "엘프 소드 마스터", status: "CONFIRMED_KR" }],
  [231, { nameCn: "灰之英雄", nameKr: "잿빛 영웅", status: "CONFIRMED_KR" }],
  [234, { nameCn: "护卫之主", nameKr: "실드 로드", status: "CONFIRMED_KR" }],
  [236, { nameCn: "炎剑统帅", nameKr: "염검의 사령관", status: "CONFIRMED_KR" }],
  [238, { nameCn: "龙王丸", nameKr: "류오마루", status: "CONFIRMED_KR" }],
  [240, { nameCn: "流浪剑客", nameKr: "방랑 군사", status: "CONFIRMED_KR" }],
  [243, { nameCn: "异星复仇者", nameKr: "크림조의 복수자", status: "CONFIRMED_KR" }],
  [246, { nameCn: "火焰神", nameKr: "화염신", status: "CONFIRMED_KR" }],
  [247, { nameCn: "皇家统帅", nameKr: "로열 마스터", status: "CONFIRMED_KR" }],
  [248, { nameCn: "皇家盾卫", nameKr: "로열 실드", status: "CONFIRMED_KR" }],
  [251, { nameCn: "万事屋之主", nameKr: "해결사 리더", status: "CONFIRMED_KR" }],
  [254, { nameCn: "术法剑师", nameKr: "매직 소드 마스터", status: "CONFIRMED_KR" }],
  [256, { nameCn: "三星", nameKr: "트라이 슈테른", status: "CONFIRMED_KR" }],
  [257, { nameCn: "沙海之王", nameKr: "사막의 왕", status: "CONFIRMED_KR" }],
  [259, { nameCn: "光盾剑卫", nameKr: "빛의 방패 기사", status: "CONFIRMED_KR" }],
  [261, { nameCn: "剑之传承", nameKr: "검의 계승자", status: "CONFIRMED_KR" }],
  [265, { nameCn: "驭空之刃", nameKr: "공중의 칼날", status: "CONFIRMED_KR" }],
  [267, { nameCn: "里万事屋之主", nameKr: "해결사 사무소 주인", status: "CONFIRMED_KR" }],
  [270, { nameCn: "剑之少女", nameKr: "검의 소녀", status: "CONFIRMED_KR" }],
  [273, { nameCn: "黄金雷击姬", nameKr: "성순검의 공주", status: "CONFIRMED_KR" }],
  [275, { nameCn: "神灭魔剑士", nameKr: "신멸 마검사", status: "CONFIRMED_KR" }],
  [277, { nameCn: "精灵剑士", nameKr: "엘프 소드 마스터", status: "CONFIRMED_KR" }],
  [280, { nameCn: "光之剑", nameKr: "빛의 검", status: "CONFIRMED_KR" }],
  [283, { nameCn: "荣光仡刃", nameKr: "영광의 칼날", status: "CONFIRMED_KR" }],
  [285, { nameCn: "守世逆刃", nameKr: "세상을 수호하는 역날", status: "CONFIRMED_KR" }],
  [287, { nameCn: "群山守护者", nameKr: "뭇산의 수호자", status: "CONFIRMED_KR" }],
  [290, { nameCn: "巨神殖装", nameKr: "가이버 기간틱XD", status: "CONFIRMED_KR" }],
  [293, { nameCn: "黑色巨神殖装", nameKr: "블랙 가이버 기간틱XD", status: "CONFIRMED_KR" }],
  [296, { nameCn: "不灭帝皇", nameKr: "불멸의 황제", status: "CONFIRMED_KR" }],
  [304, { nameCn: "骑士统帅", nameKr: "나이트 마스터", status: "CONFIRMED_KR" }],
  [305, { nameCn: "强袭统帅", nameKr: "그랜드 마스터", status: "CONFIRMED_KR" }],
  [306, { nameCn: "皇家骑士", nameKr: "로열 나이트", status: "CONFIRMED_KR" }],
  [307, { nameCn: "突击骑士", nameKr: "스트라이크 마스터", status: "CONFIRMED_KR" }],
  [352, { nameCn: "独角兽统帅", nameKr: "유니콘 마스터", status: "CONFIRMED_KR" }],
  [353, { nameCn: "黑骑士", nameKr: "다크 나이트", status: "CONFIRMED_KR" }],
  [355, { nameCn: "光武·改", nameKr: "사쿠라 전용 광무", status: "CONFIRMED_KR" }],
  [357, { nameCn: "光武·改", nameKr: "스미레 전용 광무", status: "CONFIRMED_KR" }],
  [359, { nameCn: "光武·改", nameKr: "아이리스 전용 광무", status: "CONFIRMED_KR" }],
  [362, { nameCn: "武态·剑", nameKr: "무기 형태 · 검", status: "CONFIRMED_KR" }],
  [365, { nameCn: "法骑统帅", nameKr: "위저드 나이트 마스터", status: "CONFIRMED_KR" }],
  [367, { nameCn: "西卡圣女", nameKr: "시카의 성녀", status: "CONFIRMED_KR" }],
  [370, { nameCn: "机械统帅", nameKr: "휠 제네럴", status: "CONFIRMED_KR" }],
  [372, { nameCn: "征伐骑士王", nameKr: "토벌의 기사왕", status: "CONFIRMED_KR" }],
  [375, { nameCn: "高级坦克兵", nameKr: "고급 전차병", status: "CONFIRMED_KR" }],
  [376, { nameCn: "机械骁骑", nameKr: "메카닉 나이트", status: "CONFIRMED_KR" }],
  [380, { nameCn: "圣灵骁骑", nameKr: "성령 기사", status: "CONFIRMED_KR" }],
  [382, { nameCn: "荒野骑将", nameKr: "황야의 기병 장교", status: "CONFIRMED_KR" }],
  [385, { nameCn: "永夜之誓", nameKr: "영원한 밤의 맹세", status: "CONFIRMED_KR" }],
  [387, { nameCn: "狱渊统帅", nameKr: "지옥의 사령관", status: "CONFIRMED_KR" }],
  [389, { nameCn: "凌踏的冰爪", nameKr: "침략의 서리 발톱", status: "CONFIRMED_KR" }],
  [392, { nameCn: "狂战统帅", nameKr: "광전 사령관", status: "CONFIRMED_KR" }],
  [394, { nameCn: "敛命死神", nameKr: "영혼 수확자", status: "CONFIRMED_KR" }],
] as const;
