export const HERO_JOB_LOCALIZATION_PART_1 = [
  [101, { nameCn: "士官", nameKr: "서전트", status: "CONFIRMED_KR" }],
  [102, { nameCn: "将军", nameKr: "제네럴", status: "CONFIRMED_KR" }],
  [103, { nameCn: "禁卫", nameKr: "가디언", status: "CONFIRMED_KR" }],
  [104, { nameCn: "大元帅", nameKr: "마샬", status: "CONFIRMED_KR" }],
  [105, { nameCn: "皇家卫士", nameKr: "로열 가디언", status: "CONFIRMED_KR" }],
  [106, { nameCn: "游击士", nameKr: "유격사", status: "CONFIRMED_KR" }],
  [107, { nameCn: "樱花无双", nameKr: "앵화무쌍", status: "CONFIRMED_KR" }],
  [108, { nameCn: "烈波无双", nameKr: "열파무쌍", status: "CONFIRMED_KR" }],
  [109, { nameCn: "蝴蝶之舞", nameKr: "나비의 춤", status: "CONFIRMED_KR" }],
  [110, { nameCn: "凤凰之舞", nameKr: "봉황의 춤", status: "CONFIRMED_KR" }],
  [111, { nameCn: "灵枪使", nameKr: "영력 개화", status: "CONFIRMED_KR" }],
  [112, { nameCn: "灵枪斗士", nameKr: "불굴의 파이터", status: "CONFIRMED_KR" }],
  [113, { nameCn: "圣枪使", nameKr: "할버드 전사", status: "CONFIRMED_KR" }],
  [114, { nameCn: "圣枪卫士", nameKr: "할버드 가드", status: "CONFIRMED_KR" }],
  [115, { nameCn: "圣枪统帅", nameKr: "할버드 마스터", status: "CONFIRMED_KR" }],
  [116, { nameCn: "斗士", nameKr: "투사", status: "CONFIRMED_KR" }],
  [117, { nameCn: "斗神", nameKr: "투신", status: "CONFIRMED_KR" }],
  [118, { nameCn: "枪之圣女", nameKr: "창의 성녀", status: "CONFIRMED_KR" }],
  [119, { nameCn: "女武神", nameKr: "발키리", status: "CONFIRMED_KR" }],
  [120, { nameCn: "诅咒骑士", nameKr: "커스드 나이트", status: "CONFIRMED_KR" }],
  [121, { nameCn: "战神丸", nameKr: "센진마루", status: "CONFIRMED_KR" }],
  [122, { nameCn: "战王丸", nameKr: "센오마루", status: "CONFIRMED_KR" }],
  [123, { nameCn: "紫晶统帅", nameKr: "에머시스트 마스터", status: "CONFIRMED_KR" }],
  [124, { nameCn: "佣兵", nameKr: "용병", status: "CONFIRMED_KR" }],
  [125, { nameCn: "星海猎手", nameKr: "별바다의 헌터", status: "CONFIRMED_KR" }],
  [126, { nameCn: "星海公主", nameKr: "별바다의 히로인", status: "CONFIRMED_KR" }],
  [129, { nameCn: "魔动战士", nameKr: "마동력 전사", status: "CONFIRMED_KR" }],
  [130, { nameCn: "魔铠斗将", nameKr: "마갑 대장군", status: "CONFIRMED_KR" }],
  [131, { nameCn: "魔铠斗将改", nameKr: "마갑 대장군 · 개", status: "CONFIRMED_KR" }],
  [132, { nameCn: "皇女", nameKr: "황녀", status: "CONFIRMED_KR" }],
  [133, { nameCn: "龙枪士", nameKr: "드래곤 랜서", status: "CONFIRMED_KR" }],
  [134, { nameCn: "漆黑皇女", nameKr: "칠흑의 황녀", status: "CONFIRMED_KR" }],
  [135, { nameCn: "遗迹少女", nameKr: "유적 소녀", status: "CONFIRMED_KR" }],
  [136, { nameCn: "功勋盾卫", nameKr: "공적 실드", status: "CONFIRMED_KR" }],
  [137, { nameCn: "翼盾元帅", nameKr: "아이언윙 마샬", status: "CONFIRMED_KR" }],
  [139, { nameCn: "守恒者", nameKr: "균형 수호자", status: "CONFIRMED_KR" }],
  [140, { nameCn: "护世天秤", nameKr: "수호의 저울", status: "CONFIRMED_KR" }],
  [141, { nameCn: "临阵新兵", nameKr: "결전을 앞둔 신병", status: "CONFIRMED_KR" }],
  [142, { nameCn: "炽鳞铁卫", nameKr: "화린의 철위군", status: "CONFIRMED_KR" }],
  [143, { nameCn: "龙火战将", nameKr: "화룡장군", status: "CONFIRMED_KR" }],
  [144, { nameCn: "肃杀猎手", nameKr: null, status: "UNRELEASED_KR" }],
  [145, { nameCn: "终啼之枪", nameKr: null, status: "UNRELEASED_KR" }],
  [199, { nameCn: "见习士官", nameKr: "견습 서전트", status: "CONFIRMED_KR" }],
  [201, { nameCn: "战士", nameKr: "파이터", status: "CONFIRMED_KR" }],
  [202, { nameCn: "剑士", nameKr: "소드맨", status: "CONFIRMED_KR" }],
  [203, { nameCn: "盾剑士", nameKr: "글래디에이터", status: "CONFIRMED_KR" }],
  [204, { nameCn: "剑士统帅", nameKr: "소드 마스터", status: "CONFIRMED_KR" }],
  [205, { nameCn: "皇帝", nameKr: "엠퍼러", status: "CONFIRMED_KR" }],
  [206, { nameCn: "英雄", nameKr: "영웅", status: "CONFIRMED_KR" }],
  [207, { nameCn: "剑圣", nameKr: "검성", status: "CONFIRMED_KR" }],
  [208, { nameCn: "勇者", nameKr: "용사", status: "CONFIRMED_KR" }],
  [209, { nameCn: "王者", nameKr: "킹", status: "CONFIRMED_KR" }],
  [210, { nameCn: "少尉", nameKr: "소위", status: "CONFIRMED_KR" }],
  [211, { nameCn: "修罗", nameKr: "수라", status: "CONFIRMED_KR" }],
  [212, { nameCn: "剑帝", nameKr: "검제", status: "CONFIRMED_KR" }],
  [213, { nameCn: "剑斗士", nameKr: "글래디에이터", status: "CONFIRMED_KR" }],
  [214, { nameCn: "剑斗统帅", nameKr: "배틀 마스터", status: "CONFIRMED_KR" }],
  [215, { nameCn: "盾剑统帅", nameKr: "가디언 마스터", status: "CONFIRMED_KR" }],
  [216, { nameCn: "破魔使", nameKr: "파마사", status: "CONFIRMED_KR" }],
  [217, { nameCn: "破邪剑征", nameKr: "파사의 혈통", status: "CONFIRMED_KR" }],
  [218, { nameCn: "剑姬", nameKr: "소드 프린세스", status: "CONFIRMED_KR" }],
  [219, { nameCn: "圣剑士", nameKr: "성검사", status: "CONFIRMED_KR" }],
  [220, { nameCn: "圣光之刃", nameKr: "성스러운 빛의 검", status: "CONFIRMED_KR" }],
  [221, { nameCn: "女神之刃", nameKr: "여신의 검", status: "CONFIRMED_KR" }],
  [222, { nameCn: "不良少年", nameKr: "불량 소년", status: "CONFIRMED_KR" }],
  [223, { nameCn: "灵剑使", nameKr: "영검술사", status: "CONFIRMED_KR" }],
  [224, { nameCn: "灵剑斗将", nameKr: "차원도 각성자", status: "CONFIRMED_KR" }],
  [225, { nameCn: "不良少年", nameKr: "불량 소년", status: "CONFIRMED_KR" }],
  [226, { nameCn: "皇后", nameKr: "엠프리스", status: "CONFIRMED_KR" }],
  [228, { nameCn: "魔剑士", nameKr: "엘프 파이터", status: "CONFIRMED_KR" }],
  [229, { nameCn: "精灵剑士", nameKr: "엘프 소드 마스터", status: "CONFIRMED_KR" }],
  [230, { nameCn: "灰之启动者", nameKr: "재의 기동자", status: "CONFIRMED_KR" }],
  [231, { nameCn: "灰之英雄", nameKr: "잿빛 영웅", status: "CONFIRMED_KR" }],
  [232, { nameCn: "地下守护者", nameKr: "지하의 수호자", status: "CONFIRMED_KR" }],
  [233, { nameCn: "黑色护卫", nameKr: "블랙 가드", status: "CONFIRMED_KR" }],
  [234, { nameCn: "护卫之主", nameKr: "실드 로드", status: "CONFIRMED_KR" }],
  [235, { nameCn: "炎剑使", nameKr: "화염검술사", status: "CONFIRMED_KR" }],
  [236, { nameCn: "炎剑统帅", nameKr: "염검의 사령관", status: "CONFIRMED_KR" }],
  [237, { nameCn: "龙神丸", nameKr: "류진마루", status: "CONFIRMED_KR" }],
  [238, { nameCn: "龙王丸", nameKr: "류오마루", status: "CONFIRMED_KR" }],
  [239, { nameCn: "谜之旅人", nameKr: "수수께끼의 여행자", status: "CONFIRMED_KR" }],
  [240, { nameCn: "流浪剑客", nameKr: "방랑 군사", status: "CONFIRMED_KR" }],
  [241, { nameCn: "异星末裔", nameKr: "크림조의 후예", status: "CONFIRMED_KR" }],
  [242, { nameCn: "异星剑士", nameKr: "크림조의 검사", status: "CONFIRMED_KR" }],
  [243, { nameCn: "异星复仇者", nameKr: "크림조의 복수자", status: "CONFIRMED_KR" }],
  [244, { nameCn: "武士", nameKr: "무사", status: "CONFIRMED_KR" }],
  [245, { nameCn: "烈火武士", nameKr: "열화무사", status: "CONFIRMED_KR" }],
  [246, { nameCn: "火焰神", nameKr: "화염신", status: "CONFIRMED_KR" }],
  [247, { nameCn: "皇家统帅", nameKr: "로열 마스터", status: "CONFIRMED_KR" }],
  [248, { nameCn: "皇家盾卫", nameKr: "로열 실드", status: "CONFIRMED_KR" }],
  [249, { nameCn: "武士", nameKr: "사무라이", status: "CONFIRMED_KR" }],
  [250, { nameCn: "武士之魂", nameKr: "무사의 혼", status: "CONFIRMED_KR" }],
  [251, { nameCn: "万事屋之主", nameKr: "해결사 리더", status: "CONFIRMED_KR" }],
  [252, { nameCn: "辉剑士", nameKr: "빛의 소드맨", status: "CONFIRMED_KR" }],
  [253, { nameCn: "剑术士", nameKr: "검술사", status: "CONFIRMED_KR" }],
  [254, { nameCn: "术法剑师", nameKr: "매직 소드 마스터", status: "CONFIRMED_KR" }],
  [255, { nameCn: "指挥官", nameKr: "지휘관", status: "CONFIRMED_KR" }],
  [256, { nameCn: "三星", nameKr: "트라이 슈테른", status: "CONFIRMED_KR" }],
  [257, { nameCn: "沙海之王", nameKr: "사막의 왕", status: "CONFIRMED_KR" }],
  [258, { nameCn: "光盾使", nameKr: "빛의 방패", status: "CONFIRMED_KR" }],
  [259, { nameCn: "光盾剑卫", nameKr: "빛의 방패 기사", status: "CONFIRMED_KR" }],
] as const;
