export const HERO_JOB_LOCALIZATION_PART_7 = [
  [1112, { nameCn: "异星浪人", nameKr: "크림조의 떠돌이", status: "CONFIRMED_KR" }],
  [1113, { nameCn: "异星贵族", nameKr: "크림조의 귀족", status: "CONFIRMED_KR" }],
  [1114, { nameCn: "异星王子", nameKr: "크림조의 왕자", status: "CONFIRMED_KR" }],
  [1115, { nameCn: "闪击骑士", nameKr: "쉐도우 나이트", status: "CONFIRMED_KR" }],
  [1116, { nameCn: "闪击统帅", nameKr: "쉐도우 나이트 마스터", status: "CONFIRMED_KR" }],
  [1117, { nameCn: "暗精灵", nameKr: "다크 엘프", status: "CONFIRMED_KR" }],
  [1118, { nameCn: "黑妖刺客", nameKr: "다크 엘프 암살자", status: "CONFIRMED_KR" }],
  [1120, { nameCn: "女忍", nameKr: "밴디트", status: "CONFIRMED_KR" }],
  [1121, { nameCn: "妙想忍者", nameKr: "묘상닌자", status: "CONFIRMED_KR" }],
  [1122, { nameCn: "幻神丸", nameKr: "겐진마루", status: "CONFIRMED_KR" }],
  [1123, { nameCn: "忍部首领", nameKr: "닌자두목", status: "CONFIRMED_KR" }],
  [1124, { nameCn: "幻王丸", nameKr: "겐오마루", status: "CONFIRMED_KR" }],
  [1125, { nameCn: "月影魔姬", nameKr: "달그림자의 몽마", status: "CONFIRMED_KR" }],
  [1126, { nameCn: "血梦之主", nameKr: "핏빛 서큐버스", status: "CONFIRMED_KR" }],
  [1127, { nameCn: "女妖邪", nameKr: "여요사", status: "CONFIRMED_KR" }],
  [1128, { nameCn: "妖邪剑使", nameKr: "요사의 검사", status: "CONFIRMED_KR" }],
  [1129, { nameCn: "星丽剑姬", nameKr: "성려검희", status: "CONFIRMED_KR" }],
  [1130, { nameCn: "掠袭游侠", nameKr: "스트라이크 레인저", status: "CONFIRMED_KR" }],
  [1131, { nameCn: "强袭斗将", nameKr: "포스 제네럴", status: "CONFIRMED_KR" }],
  [1132, { nameCn: "漫游者", nameKr: "방랑자", status: "CONFIRMED_KR" }],
  [1133, { nameCn: "独行客", nameKr: "외톨이 여객", status: "CONFIRMED_KR" }],
  [1134, { nameCn: "独行义侠", nameKr: "외톨이 협객", status: "CONFIRMED_KR" }],
  [1135, { nameCn: "反抗军", nameKr: "반란군", status: "CONFIRMED_KR" }],
  [1136, { nameCn: "抗暴统帅", nameKr: "복수의 지휘관", status: "CONFIRMED_KR" }],
  [1137, { nameCn: "远行者", nameKr: "여행자", status: "CONFIRMED_KR" }],
  [1138, { nameCn: "远行浪客", nameKr: "방랑 낭객", status: "CONFIRMED_KR" }],
  [1139, { nameCn: "精灵刺客", nameKr: "엘프 암살자", status: "CONFIRMED_KR" }],
  [1140, { nameCn: "暮影刺客", nameKr: "황혼의 암살자", status: "CONFIRMED_KR" }],
  [1141, { nameCn: "恶念容器", nameKr: "악념의 그릇", status: "CONFIRMED_KR" }],
  [1142, { nameCn: "恶欲裁罚", nameKr: "악한 욕망의 징벌자", status: "CONFIRMED_KR" }],
  [1143, { nameCn: "希望之种", nameKr: "희망의 씨앗", status: "CONFIRMED_KR" }],
  [1144, { nameCn: "希望之花", nameKr: "희망의 꽃", status: "CONFIRMED_KR" }],
  [1145, { nameCn: "诡毒处刑官", nameKr: "간악한 처형관", status: "CONFIRMED_KR" }],
  [1146, { nameCn: "暗楔女统帅", nameKr: "어둠의 여장군", status: "CONFIRMED_KR" }],
  [1147, { nameCn: "王国隐侍", nameKr: "왕국 비밀 조력자", status: "CONFIRMED_KR" }],
  [1148, { nameCn: "影锋暗将", nameKr: "음영의 장군", status: "CONFIRMED_KR" }],
  [1149, { nameCn: "街机浪客", nameKr: "아케이드 방랑자", status: "CONFIRMED_KR" }],
  [1150, { nameCn: "忍者", nameKr: "닌자", status: "CONFIRMED_KR" }],
  [1151, { nameCn: "马克", nameKr: "나이프", status: "CONFIRMED_KR" }],
  [1152, { nameCn: "忍者Ginzu", nameKr: "닌자 긴주", status: "CONFIRMED_KR" }],
  [1153, { nameCn: "小刀马克", nameKr: "맥 더 나이프", status: "CONFIRMED_KR" }],
  [1154, { nameCn: "暗夜幽刃", nameKr: "어둠의 인도자", status: "CONFIRMED_KR" }],
  [1155, { nameCn: "暗夜君王", nameKr: "어둠의 군주", status: "CONFIRMED_KR" }],
  [1156, { nameCn: "雾幻之刃", nameKr: "무환의 칼날", status: "CONFIRMED_KR" }],
  [1157, { nameCn: "复仇的叛忍", nameKr: "복수의 탈주닌자", status: "CONFIRMED_KR" }],
  [1158, { nameCn: "断命之天神", nameKr: "단명의 천신", status: "CONFIRMED_KR" }],
  [1159, { nameCn: "漂泊舞娘", nameKr: "떠돌이 무희", status: "CONFIRMED_KR" }],
  [1160, { nameCn: "诡袭者", nameKr: "습격자", status: "CONFIRMED_KR" }],
  [1161, { nameCn: "寒光影姬", nameKr: "서늘한 빛의 그림자", status: "CONFIRMED_KR" }],
  [1162, { nameCn: "媚视之刺", nameKr: "시선의 가시", status: "CONFIRMED_KR" }],
  [1163, { nameCn: "幽视暗裁者", nameKr: "어둠의 심판자", status: "CONFIRMED_KR" }],
  [1164, { nameCn: "丑角", nameKr: "어릿광대", status: "CONFIRMED_KR" }],
  [1165, { nameCn: "暗刃镰客", nameKr: "낫을 든 어둠의 방랑자", status: "CONFIRMED_KR" }],
  [1167, { nameCn: "惊魂假面", nameKr: "공포의 가면", status: "CONFIRMED_KR" }],
  [1168, { nameCn: "流浪保镖", nameKr: "떠돌이 경호원", status: "CONFIRMED_KR" }],
  [1169, { nameCn: "异界的战士", nameKr: "이계의 전사", status: "CONFIRMED_KR" }],
  [1170, { nameCn: "白牙斗将", nameKr: "백아 대장군", status: "CONFIRMED_KR" }],
  [1171, { nameCn: "辉刃义贼", nameKr: "칼날 의적", status: "CONFIRMED_KR" }],
  [1172, { nameCn: "圣辉游侠", nameKr: "성휘 레인저", status: "CONFIRMED_KR" }],
  [1173, { nameCn: "幻影秘盗", nameKr: null, status: "UNRELEASED_KR" }],
  [1174, { nameCn: "万秘主宰", nameKr: null, status: "UNRELEASED_KR" }],
  [1175, { nameCn: "残响之种", nameKr: null, status: "UNRELEASED_KR" }],
  [1176, { nameCn: "守护之蕾", nameKr: null, status: "UNRELEASED_KR" }],
  [1177, { nameCn: "孤高之花", nameKr: null, status: "UNRELEASED_KR" }],
  [1201, { nameCn: "圣兽", nameKr: "홀리 비스트", status: "CONFIRMED_KR" }],
  [1202, { nameCn: "刻耳柏洛斯", nameKr: "켈베로스", status: "CONFIRMED_KR" }],
  [1203, { nameCn: "斯库拉", nameKr: "스킬라", status: "CONFIRMED_KR" }],
  [1204, { nameCn: "提亚马特", nameKr: "티아매트", status: "CONFIRMED_KR" }],
  [1205, { nameCn: "贝希摩斯", nameKr: "베히모스", status: "CONFIRMED_KR" }],
  [1206, { nameCn: "海德拉", nameKr: "히드라", status: "CONFIRMED_KR" }],
  [1207, { nameCn: "巴哈姆特", nameKr: "바하무트", status: "CONFIRMED_KR" }],
  [1208, { nameCn: "龙裔", nameKr: "용의 후예", status: "CONFIRMED_KR" }],
  [1209, { nameCn: "龙战士", nameKr: "드래곤 파이터", status: "CONFIRMED_KR" }],
  [1210, { nameCn: "龙族统帅", nameKr: "드래곤 제네럴", status: "CONFIRMED_KR" }],
  [1211, { nameCn: "龙之子", nameKr: "용의 아이", status: "CONFIRMED_KR" }],
  [1212, { nameCn: "龙胤继承者", nameKr: "용의 계승자", status: "CONFIRMED_KR" }],
  [1213, { nameCn: "灵龙转生使", nameKr: "정령용의 환생", status: "CONFIRMED_KR" }],
  [1215, { nameCn: "原初之龙", nameKr: "원시의 용", status: "CONFIRMED_KR" }],
  [1216, { nameCn: "金息幻龙", nameKr: "금빛 숨결의 용", status: "CONFIRMED_KR" }],
  [1217, { nameCn: "佑世真龙", nameKr: "세계 구원의 용", status: "CONFIRMED_KR" }],
  [1218, { nameCn: "龙力继承者", nameKr: "용력 계승자", status: "CONFIRMED_KR" }],
  [1219, { nameCn: "炎龙王之裔", nameKr: "염룡왕의 후예", status: "CONFIRMED_KR" }],
  [20201, { nameCn: "电玩少年", nameKr: "게임 보이", status: "CONFIRMED_KR" }],
  [20202, { nameCn: "队长", nameKr: "캡틴", status: "CONFIRMED_KR" }],
  [20203, { nameCn: "婴儿", nameKr: "베이비", status: "CONFIRMED_KR" }],
  [20204, { nameCn: "突击队长", nameKr: "캡틴 코만도", status: "CONFIRMED_KR" }],
  [20205, { nameCn: "天才婴儿", nameKr: "베이비 헤드", status: "CONFIRMED_KR" }],
  [20206, { nameCn: "海潮之遗", nameKr: "파도의 유물", status: "CONFIRMED_KR" }],
  [20207, { nameCn: "礁岸斗士", nameKr: "절벽의 투사", status: "CONFIRMED_KR" }],
  [20208, { nameCn: "海礁统帅", nameKr: "암초 통솔자", status: "CONFIRMED_KR" }],
  [20209, { nameCn: "见习仆役", nameKr: "견습 시종", status: "CONFIRMED_KR" }],
  [20210, { nameCn: "蔷薇侍者", nameKr: "로즈 메이드", status: "CONFIRMED_KR" }],
  [20211, { nameCn: "小恶魔女仆", nameKr: "소악마 서번트", status: "CONFIRMED_KR" }],
  [20212, { nameCn: "封锁者", nameKr: "봉쇄자", status: "CONFIRMED_KR" }],
  [20213, { nameCn: "再起者", nameKr: "재기자", status: "CONFIRMED_KR" }],
  [20214, { nameCn: "复兴之剑", nameKr: "부흥의 검", status: "CONFIRMED_KR" }],
  [20215, { nameCn: "剑术导师", nameKr: "검술 현자", status: "CONFIRMED_KR" }],
  [20216, { nameCn: "神剑士", nameKr: "신검사", status: "CONFIRMED_KR" }],
  [20217, { nameCn: "匡正之剑", nameKr: "시정의 검", status: "CONFIRMED_KR" }],
  [20218, { nameCn: "女王亲卫", nameKr: "여왕의 친위병", status: "CONFIRMED_KR" }],
  [20219, { nameCn: "荣光宰相", nameKr: "영광의 재상", status: "CONFIRMED_KR" }],
] as const;
