import type { HeroSkillKrCatalog } from "./hero-skill-localization.schema";

export const HERO_SKILL_KR_CATALOG: HeroSkillKrCatalog = {
  schemaVersion: 1,
  sourceFamily: "hero-skill-korean-localization",
  records: [
    {
      skillId: 10301,
      sourceNameCn: "突击",
      nameKr: "돌격",
      descKr: "단일 적에게 1배 피해. 치료 방해를 1턴 부여하고, 공격 전 이동 1칸마다 피해 +20%(최대 +60%).",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5020,
      sourceNameCn: "整军",
      nameKr: "군단 정비",
      descKr: "부대 생명이 90% 이상이면 공격과 방어 +10%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10324,
      sourceNameCn: "猛撞",
      nameKr: "맹렬한 돌격",
      descKr: "단일 적에게 1.4배 피해. 대상을 2칸 밀치고 방어 -20%, 호위 불가를 2턴 부여.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5003,
      sourceNameCn: "破攻",
      nameKr: "무기 파괴",
      descKr: "전투 진입 전 50% 확률로 적의 공격과 지력 -20%. 1턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 5007,
      sourceNameCn: "压制",
      nameKr: "제압",
      descKr: "자신의 남은 생명 비율이 상대보다 높으면 전투 중 공격 +12%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10314,
      sourceNameCn: "气浪",
      nameKr: "폭풍",
      descKr: "공격하여 전투 진입 시 부대 생명이 80% 이상이면 전투 중 받는 피해 -30%.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10328,
      sourceNameCn: "骑士精神",
      nameKr: "기사도",
      descKr: "자신 부대 공격 +30%, 면역과 폭풍을 2턴 부여. 사용 후 3칸 추가 이동하고 공격 가능.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 11807,
      sourceNameCn: "帝国冲锋",
      nameKr: "제국의 돌격",
      descKr: "제국의 빛 아군의 공격·방어를 크게 올리고, 공격 전 이동 1칸마다 전투 피해 +5%(최대 +15%). 4턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10302,
      sourceNameCn: "千骑",
      nameKr: "일기당천",
      descKr: "단일 적에게 1.7배 피해. 전투 후 이동력 -2와 호위 불가를 2턴 부여하며 제거되지 않음.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [6], note: "Migrated from the Leon-only Stage 5 presentation overlay." },
    },
    {
      skillId: 10705,
      sourceNameCn: "冰冻",
      nameKr: "빙결",
      descKr: "단일 개체에게 1.5배의 피해를 준다. '창병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10703,
      sourceNameCn: "雷击",
      nameKr: "썬더",
      descKr: "단일 적 부대를 공격해 1.5배의 피해를 준다. '기병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10706,
      sourceNameCn: "冰锥",
      nameKr: "아이스",
      descKr: "범위 내 다수의 적군에게 0.3배의 피해. '창병'에게 더 큰 피해를 준다. 적의 이동력 -1칸 및 호위 불가를 부여, 2행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10109,
      sourceNameCn: "魔防威吓",
      nameKr: "마방 위협",
      descKr: "[패시브] 행동 종료 시 주위 3칸 내 모든 적 부대 마방 -20%, 1행동 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10841,
      sourceNameCn: "净化",
      nameKr: "턴 언데드",
      descKr: "단일 개체에게 1.5배의 피해. '마물'에게 더 큰 피해를 준다. 전투 후 대상의 버프를 2개 제거한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10813,
      sourceNameCn: "天罚",
      nameKr: "천벌",
      descKr: "치명타 확률 +50%. 주위 5칸 내 모든 적군에게 0.35배 범위 피해를 입힌다. '마물'과 전투 시 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8], note: "Legacy Korean sheet hero/data/라나.js; cross-checked against frozen Stage 6 Hero 8 Skill ID/CN/effect." },
    },
    {
      skillId: 10711,
      sourceNameCn: "梦魇",
      nameKr: "악몽",
      descKr: "[마법 피해] 전장의 적 1부대에게 0.25배의 피해를 주고 버프를 3개 제거하며 다음 턴 행동할 수 없게 한다. 제거 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10701,
      sourceNameCn: "火球",
      nameKr: "파이어볼",
      descKr: "단일 개체에게 1.5배의 피해. '보병'에게 더 큰 피해를 준다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10712,
      sourceNameCn: "凋零",
      nameKr: "노화",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.3배의 광역 피해를 주며 적에게 '강화 방해'를 부여한다. 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10719,
      sourceNameCn: "封印",
      nameKr: "봉인",
      descKr: "[패시브] 적에게 피해를 줬을 경우 50% 확률로 적에게 '침묵' 부여, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 11813,
      sourceNameCn: "暗之轮舞",
      nameKr: "어둠의 윤무",
      descKr: "[초절강화] 범위 내 모든 '어둠의 윤회' 아군의 공격, 방어 능력치가 크게 상승한다. 전투 중 상대에게 디버프가 3개 이상 걸려 있을 경우 자신 부대가 주는 피해량 +15%, 4턴 지속. 다른 초절강화 스킬과 중첩 불가.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10709,
      sourceNameCn: "大地震",
      nameKr: "어스퀘이크",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.4배의 광역 피해를 준다. '비병'에게 피해를 줄 수 없다. 적의 공격, 지력, 방어 -20%, 2턴 지속.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [9], note: "Legacy Korean sheet hero/data/보젤.js; cross-checked against frozen Stage 6 Hero 9 Skill ID/CN/effect." },
    },
    {
      skillId: 10716,
      sourceNameCn: "暗镰",
      nameKr: "어둠의 낫",
      descKr: "단일 적에게 1.3배의 피해. 적의 마방을 30% 무시. 전투 후 준 피해량의 50%만큼 회복한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
    {
      skillId: 10717,
      sourceNameCn: "黑洞",
      nameKr: "블랙홀",
      descKr: "[마법 피해] 범위 내 적들을 공격해 0.36배의 광역 피해를 준다. 각 부대에게 무작위 디버프를 2개씩 부여한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
    {
      skillId: 20001,
      sourceNameCn: "召唤亡灵",
      nameKr: "망령 소환",
      descKr: "망령술사 부대를 1개 소환한다.",
      status: "LEGACY_SHEET_KR",
      source: { type: "legacy-korean-sheet", heroIds: [8, 9], note: "Shared legacy Korean skill in hero/data/라나.js and hero/data/보젤.js; cross-checked against frozen Stage 6 Skill ID/CN/effect." },
    },
  ],
};
