export const HERO_FINAL_JOB_LOCALIZATION_PART_2 = [
  [396, { nameCn: "焰锋统帅", nameKr: "화염의 통솔자", status: "CONFIRMED_KR" }],
  [398, { nameCn: "破阵骁将", nameKr: "파진 전사", status: "CONFIRMED_KR" }],
  [405, { nameCn: "龙骑统帅", nameKr: "드래곤 마스터", status: "CONFIRMED_KR" }],
  [406, { nameCn: "圣天马统帅", nameKr: "페가수스 마스터", status: "CONFIRMED_KR" }],
  [408, { nameCn: "帝国密使", nameKr: "제국 첩보원", status: "CONFIRMED_KR" }],
  [411, { nameCn: "翠晶统帅", nameKr: "비취 수정 기사단장", status: "CONFIRMED_KR" }],
  [412, { nameCn: "圣天马星骑", nameKr: "홀리 페가수스 나이트", status: "CONFIRMED_KR" }],
  [416, { nameCn: "魔翼斗将", nameKr: "검은 날개의 투장", status: "CONFIRMED_KR" }],
  [417, { nameCn: "锋翼统帅", nameKr: "아이언윙 마스터", status: "CONFIRMED_KR" }],
  [419, { nameCn: "驭龙骑士", nameKr: "드래곤 기사", status: "CONFIRMED_KR" }],
  [421, { nameCn: "堕临之灾厄", nameKr: "타락의 재앙", status: "CONFIRMED_KR" }],
  [423, { nameCn: "凛空皓翼", nameKr: "차가운 하늘의 밝은 날개", status: "CONFIRMED_KR" }],
  [425, { nameCn: "御空的霜翼", nameKr: "하늘을 가르는 서리 날개", status: "CONFIRMED_KR" }],
  [428, { nameCn: "终末之誓", nameKr: "종말의 맹세", status: "CONFIRMED_KR" }],
  [431, { nameCn: "凛空黯翼", nameKr: "암흑의 비상", status: "CONFIRMED_KR" }],
  [433, { nameCn: "赤曜征服者", nameKr: "적요의 정복자", status: "CONFIRMED_KR" }],
  [436, { nameCn: "缭乱的天狗姬", nameKr: "혼란의 텐구공주", status: "CONFIRMED_KR" }],
  [440, { nameCn: "灿金辉翼", nameKr: "빛나는 금빛 날개", status: "CONFIRMED_KR" }],
  [442, { nameCn: "罪渊黯翼", nameKr: "죄악의 검은 날개", status: "CONFIRMED_KR" }],
  [445, { nameCn: "救世孤星", nameKr: null, status: "UNRELEASED_KR" }],
  [447, { nameCn: "灿虹之星", nameKr: null, status: "UNRELEASED_KR" }],
  [450, { nameCn: "渡魂天翼", nameKr: null, status: "UNRELEASED_KR" }],
  [452, { nameCn: "迦楼罗王", nameKr: null, status: "UNRELEASED_KR" }],
  [503, { nameCn: "海骑统帅", nameKr: "서펜트 마스터", status: "CONFIRMED_KR" }],
  [505, { nameCn: "海斗统帅", nameKr: "마린 마스터", status: "CONFIRMED_KR" }],
  [509, { nameCn: "执政官", nameKr: "집정관", status: "CONFIRMED_KR" }],
  [512, { nameCn: "深海的风铃", nameKr: "심해의 풍경", status: "CONFIRMED_KR" }],
  [514, { nameCn: "幻逝谜伶", nameKr: "환상의 배우", status: "CONFIRMED_KR" }],
  [516, { nameCn: "穹海纵横王", nameKr: "바다의 제왕", status: "CONFIRMED_KR" }],
  [518, { nameCn: "驭潮将星", nameKr: "파도의 지배자", status: "CONFIRMED_KR" }],
  [521, { nameCn: "海平之望", nameKr: null, status: "UNRELEASED_KR" }],
  [604, { nameCn: "游侠", nameKr: "레인저", status: "CONFIRMED_KR" }],
  [605, { nameCn: "弓骑统帅", nameKr: "보우 마스터", status: "CONFIRMED_KR" }],
  [609, { nameCn: "帝国皇子", nameKr: "제국 왕자", status: "CONFIRMED_KR" }],
  [610, { nameCn: "吟游诗人", nameKr: "음유시인", status: "CONFIRMED_KR" }],
  [613, { nameCn: "狼骑统帅", nameKr: "울프 마스터", status: "CONFIRMED_KR" }],
  [615, { nameCn: "破灭之翼", nameKr: "파멸의 날개", status: "CONFIRMED_KR" }],
  [618, { nameCn: "天空神", nameKr: "천공신", status: "CONFIRMED_KR" }],
  [621, { nameCn: "铳击统帅", nameKr: "건 커맨더", status: "CONFIRMED_KR" }],
  [625, { nameCn: "真深蓝魔女", nameKr: "결전의 푸른 마녀", status: "CONFIRMED_KR" }],
  [628, { nameCn: "侦察猎兵", nameKr: "정찰엽병", status: "CONFIRMED_KR" }],
  [630, { nameCn: "突击猎兵", nameKr: "돌격엽병", status: "CONFIRMED_KR" }],
  [632, { nameCn: "支援猎兵", nameKr: "지원엽병", status: "CONFIRMED_KR" }],
  [634, { nameCn: "狙击猎兵", nameKr: "저격엽병", status: "CONFIRMED_KR" }],
  [637, { nameCn: "机工统帅", nameKr: "메카 마스터", status: "CONFIRMED_KR" }],
  [638, { nameCn: "科技铳士", nameKr: "테크니컬 슈터", status: "CONFIRMED_KR" }],
  [641, { nameCn: "圣印歌巫女", nameKr: "성인가의 무녀", status: "CONFIRMED_KR" }],
  [643, { nameCn: "龙翼弓奏者", nameKr: "용익궁 연주자", status: "CONFIRMED_KR" }],
  [645, { nameCn: "妖精之望", nameKr: "엘프의 희망", status: "CONFIRMED_KR" }],
  [648, { nameCn: "风暴主宰", nameKr: "폭풍의 지배자", status: "CONFIRMED_KR" }],
  [651, { nameCn: "大商人才媛", nameKr: "거상의 재녀", status: "CONFIRMED_KR" }],
  [704, { nameCn: "巫师", nameKr: "위저드", status: "CONFIRMED_KR" }],
  [705, { nameCn: "女王", nameKr: "퀸", status: "CONFIRMED_KR" }],
  [706, { nameCn: "黑暗公主", nameKr: "다크 프린세스", status: "CONFIRMED_KR" }],
  [707, { nameCn: "隐士", nameKr: "허미트", status: "CONFIRMED_KR" }],
  [708, { nameCn: "黑暗统帅", nameKr: "다크 마스터", status: "CONFIRMED_KR" }],
  [709, { nameCn: "创造家", nameKr: "크리에이터", status: "CONFIRMED_KR" }],
  [712, { nameCn: "魔能核心", nameKr: "매직 코어", status: "CONFIRMED_KR" }],
  [714, { nameCn: "魔导元帅", nameKr: "마도 원수", status: "CONFIRMED_KR" }],
  [716, { nameCn: "科学狂人", nameKr: "매드 사이언티스트", status: "CONFIRMED_KR" }],
  [718, { nameCn: "魔蔷薇之棘", nameKr: "마계의 장미", status: "CONFIRMED_KR" }],
  [719, { nameCn: "炎晶魔导师", nameKr: "화염수정 마법사", status: "CONFIRMED_KR" }],
  [722, { nameCn: "西卡招魂师", nameKr: "시카의 초혼사", status: "CONFIRMED_KR" }],
  [725, { nameCn: "高等妖精", nameKr: "하이 엘프", status: "CONFIRMED_KR" }],
  [727, { nameCn: "皇家女仆", nameKr: "로열 메이드", status: "CONFIRMED_KR" }],
  [730, { nameCn: "织魔师", nameKr: "마법 재봉사", status: "CONFIRMED_KR" }],
  [731, { nameCn: "帝国宰相", nameKr: "제국 재상", status: "CONFIRMED_KR" }],
  [733, { nameCn: "巅峰不死者", nameKr: "초즌 오브 언데드", status: "CONFIRMED_KR" }],
  [735, { nameCn: "水晶女皇", nameKr: "수정 여왕", status: "CONFIRMED_KR" }],
  [741, { nameCn: "裁决威光", nameKr: "여신의 심판", status: "CONFIRMED_KR" }],
  [743, { nameCn: "裂心法师", nameKr: "디스페어 메이지", status: "CONFIRMED_KR" }],
  [746, { nameCn: "玛娜导师", nameKr: "마나의 스승", status: "CONFIRMED_KR" }],
  [749, { nameCn: "月隐谪仙", nameKr: "달의 선인", status: "CONFIRMED_KR" }],
  [751, { nameCn: "禁忌预视者", nameKr: "금기의 선지자", status: "CONFIRMED_KR" }],
  [754, { nameCn: "灵能破坏者", nameKr: "영능력 파괴자", status: "CONFIRMED_KR" }],
  [756, { nameCn: "导力传人", nameKr: "도력 조종자", status: "CONFIRMED_KR" }],
  [760, { nameCn: "异维法皇", nameKr: "이차원의 대주교", status: "CONFIRMED_KR" }],
  [763, { nameCn: "致真者", nameKr: "진실을 깨우친 자", status: "CONFIRMED_KR" }],
  [766, { nameCn: "全视者", nameKr: "전지자", status: "CONFIRMED_KR" }],
  [767, { nameCn: "破龙魔导士", nameKr: "용멸 마도사", status: "CONFIRMED_KR" }],
  [768, { nameCn: "精灵魔导士", nameKr: "정령 마도사", status: "CONFIRMED_KR" }],
  [771, { nameCn: "赤冕法皇", nameKr: "붉은 관의 법황", status: "CONFIRMED_KR" }],
  [774, { nameCn: "定律魔女", nameKr: "법칙의 마녀", status: "CONFIRMED_KR" }],
  [777, { nameCn: "裁决之镰", nameKr: "심판의 낫", status: "CONFIRMED_KR" }],
  [779, { nameCn: "咒法术师", nameKr: "주문 술사", status: "CONFIRMED_KR" }],
  [781, { nameCn: "圣雷召现使", nameKr: "신성한 번개 소환사", status: "CONFIRMED_KR" }],
] as const;
