export const HERO_JOB_LOCALIZATION_PART_4 = [
  [647, { nameCn: "狂风之弦", nameKr: "광풍의 활", status: "CONFIRMED_KR" }],
  [648, { nameCn: "风暴主宰", nameKr: "폭풍의 지배자", status: "CONFIRMED_KR" }],
  [649, { nameCn: "商会千金", nameKr: "상회 아가씨", status: "CONFIRMED_KR" }],
  [650, { nameCn: "干练的能人", nameKr: "유능한 일꾼", status: "CONFIRMED_KR" }],
  [651, { nameCn: "大商人才媛", nameKr: "거상의 재녀", status: "CONFIRMED_KR" }],
  [701, { nameCn: "魔术师", nameKr: "메이지", status: "CONFIRMED_KR" }],
  [702, { nameCn: "大魔法师", nameKr: "아크 메이지", status: "CONFIRMED_KR" }],
  [703, { nameCn: "召唤师", nameKr: "서모너", status: "CONFIRMED_KR" }],
  [704, { nameCn: "巫师", nameKr: "위저드", status: "CONFIRMED_KR" }],
  [705, { nameCn: "女王", nameKr: "퀸", status: "CONFIRMED_KR" }],
  [706, { nameCn: "黑暗公主", nameKr: "다크 프린세스", status: "CONFIRMED_KR" }],
  [707, { nameCn: "隐士", nameKr: "허미트", status: "CONFIRMED_KR" }],
  [708, { nameCn: "黑暗统帅", nameKr: "다크 마스터", status: "CONFIRMED_KR" }],
  [709, { nameCn: "创造家", nameKr: "크리에이터", status: "CONFIRMED_KR" }],
  [710, { nameCn: "发明家", nameKr: "발명가", status: "CONFIRMED_KR" }],
  [711, { nameCn: "魔法容器", nameKr: "매직 소울", status: "CONFIRMED_KR" }],
  [712, { nameCn: "魔能核心", nameKr: "매직 코어", status: "CONFIRMED_KR" }],
  [713, { nameCn: "魔导士", nameKr: "마도사", status: "CONFIRMED_KR" }],
  [714, { nameCn: "魔导元帅", nameKr: "마도 원수", status: "CONFIRMED_KR" }],
  [715, { nameCn: "科学家", nameKr: "사이언티스트", status: "CONFIRMED_KR" }],
  [716, { nameCn: "科学狂人", nameKr: "매드 사이언티스트", status: "CONFIRMED_KR" }],
  [717, { nameCn: "蔷薇使者", nameKr: "식물의 사역", status: "CONFIRMED_KR" }],
  [718, { nameCn: "魔蔷薇之棘", nameKr: "마계의 장미", status: "CONFIRMED_KR" }],
  [719, { nameCn: "炎晶魔导师", nameKr: "화염수정 마법사", status: "CONFIRMED_KR" }],
  [720, { nameCn: "西卡侍女", nameKr: "시카의 시녀", status: "CONFIRMED_KR" }],
  [721, { nameCn: "西卡通灵者", nameKr: "시카의 샤먼", status: "CONFIRMED_KR" }],
  [722, { nameCn: "西卡招魂师", nameKr: "시카의 초혼사", status: "CONFIRMED_KR" }],
  [723, { nameCn: "大精灵", nameKr: "하이엘프", status: "CONFIRMED_KR" }],
  [724, { nameCn: "精灵使", nameKr: "정령술사", status: "CONFIRMED_KR" }],
  [725, { nameCn: "高等妖精", nameKr: "하이 엘프", status: "CONFIRMED_KR" }],
  [726, { nameCn: "女仆长", nameKr: "메이드장", status: "CONFIRMED_KR" }],
  [727, { nameCn: "皇家女仆", nameKr: "로열 메이드", status: "CONFIRMED_KR" }],
  [728, { nameCn: "缚灵师", nameKr: "소울 바인더", status: "CONFIRMED_KR" }],
  [729, { nameCn: "魔法裁缝", nameKr: "마법의 재봉사", status: "CONFIRMED_KR" }],
  [730, { nameCn: "织魔师", nameKr: "마법 재봉사", status: "CONFIRMED_KR" }],
  [731, { nameCn: "帝国宰相", nameKr: "제국 재상", status: "CONFIRMED_KR" }],
  [732, { nameCn: "不死者", nameKr: "불사신", status: "CONFIRMED_KR" }],
  [733, { nameCn: "巅峰不死者", nameKr: "초즌 오브 언데드", status: "CONFIRMED_KR" }],
  [734, { nameCn: "水晶魔使", nameKr: "수정마도사", status: "CONFIRMED_KR" }],
  [735, { nameCn: "水晶女皇", nameKr: "수정 여왕", status: "CONFIRMED_KR" }],
  [736, { nameCn: "火焰使", nameKr: "화염술사", status: "CONFIRMED_KR" }],
  [737, { nameCn: "炎晶使徒", nameKr: "화염 수정의 사도", status: "CONFIRMED_KR" }],
  [738, { nameCn: "秘术师", nameKr: "비술사", status: "CONFIRMED_KR" }],
  [739, { nameCn: "光之子", nameKr: "빛의 아이", status: "CONFIRMED_KR" }],
  [740, { nameCn: "涟漪辉光", nameKr: "빛의 물결", status: "CONFIRMED_KR" }],
  [741, { nameCn: "裁决威光", nameKr: "여신의 심판", status: "CONFIRMED_KR" }],
  [742, { nameCn: "暗谋法师", nameKr: "바이스 메이지", status: "CONFIRMED_KR" }],
  [743, { nameCn: "裂心法师", nameKr: "디스페어 메이지", status: "CONFIRMED_KR" }],
  [745, { nameCn: "玛娜术士", nameKr: "마나술사", status: "CONFIRMED_KR" }],
  [746, { nameCn: "玛娜导师", nameKr: "마나의 스승", status: "CONFIRMED_KR" }],
  [747, { nameCn: "玉蟾先生", nameKr: "옥섬 선생", status: "CONFIRMED_KR" }],
  [748, { nameCn: "竹隐方士", nameKr: "대나무 선인", status: "CONFIRMED_KR" }],
  [749, { nameCn: "月隐谪仙", nameKr: "달의 선인", status: "CONFIRMED_KR" }],
  [750, { nameCn: "探求者", nameKr: "탐구자", status: "CONFIRMED_KR" }],
  [751, { nameCn: "禁忌预视者", nameKr: "금기의 선지자", status: "CONFIRMED_KR" }],
  [752, { nameCn: "人工智能", nameKr: "인공지능", status: "CONFIRMED_KR" }],
  [753, { nameCn: "灵能傀儡", nameKr: "영능력 꼭두각시", status: "CONFIRMED_KR" }],
  [754, { nameCn: "灵能破坏者", nameKr: "영능력 파괴자", status: "CONFIRMED_KR" }],
  [755, { nameCn: "导力操纵者", nameKr: "도력 계승자", status: "CONFIRMED_KR" }],
  [756, { nameCn: "导力传人", nameKr: "도력 조종자", status: "CONFIRMED_KR" }],
  [757, { nameCn: "学生", nameKr: "학생", status: "CONFIRMED_KR" }],
  [758, { nameCn: "次元行者", nameKr: "차원 여행자", status: "CONFIRMED_KR" }],
  [759, { nameCn: "次元术师", nameKr: "차원술사", status: "CONFIRMED_KR" }],
  [760, { nameCn: "异维法皇", nameKr: "이차원의 대주교", status: "CONFIRMED_KR" }],
  [761, { nameCn: "研习者", nameKr: "연구자", status: "CONFIRMED_KR" }],
  [762, { nameCn: "求道者", nameKr: "구도자", status: "CONFIRMED_KR" }],
  [763, { nameCn: "致真者", nameKr: "진실을 깨우친 자", status: "CONFIRMED_KR" }],
  [764, { nameCn: "观测者", nameKr: "관찰자", status: "CONFIRMED_KR" }],
  [765, { nameCn: "行吟歌者", nameKr: "방랑 가수", status: "CONFIRMED_KR" }],
  [766, { nameCn: "全视者", nameKr: "전지자", status: "CONFIRMED_KR" }],
  [767, { nameCn: "破龙魔导士", nameKr: "용멸 마도사", status: "CONFIRMED_KR" }],
  [768, { nameCn: "精灵魔导士", nameKr: "정령 마도사", status: "CONFIRMED_KR" }],
  [770, { nameCn: "龙炎咒师", nameKr: "용염 주술사", status: "CONFIRMED_KR" }],
  [771, { nameCn: "赤冕法皇", nameKr: "붉은 관의 법황", status: "CONFIRMED_KR" }],
  [772, { nameCn: "炼金士", nameKr: "연금술사", status: "CONFIRMED_KR" }],
  [773, { nameCn: "炼金学者", nameKr: "연금술 학자", status: "CONFIRMED_KR" }],
  [774, { nameCn: "定律魔女", nameKr: "법칙의 마녀", status: "CONFIRMED_KR" }],
  [775, { nameCn: "塑者", nameKr: "창조물", status: "CONFIRMED_KR" }],
  [776, { nameCn: "审判执使", nameKr: "심판의 집사", status: "CONFIRMED_KR" }],
  [777, { nameCn: "裁决之镰", nameKr: "심판의 낫", status: "CONFIRMED_KR" }],
  [778, { nameCn: "咒法学者", nameKr: "주문 학파의 학자", status: "CONFIRMED_KR" }],
  [779, { nameCn: "咒法术师", nameKr: "주문 술사", status: "CONFIRMED_KR" }],
  [780, { nameCn: "唤雷祈者", nameKr: "번개 소환 기도사", status: "CONFIRMED_KR" }],
  [781, { nameCn: "圣雷召现使", nameKr: "신성한 번개 소환사", status: "CONFIRMED_KR" }],
  [782, { nameCn: "定序者", nameKr: "질서 확립자", status: "CONFIRMED_KR" }],
  [783, { nameCn: "永序之誓", nameKr: "영원한 서약", status: "CONFIRMED_KR" }],
  [784, { nameCn: "萌芽之灵", nameKr: "피어나는 영혼", status: "CONFIRMED_KR" }],
  [785, { nameCn: "元素学者", nameKr: "원소 학자", status: "CONFIRMED_KR" }],
  [786, { nameCn: "元素召灵使", nameKr: "원소 소환사", status: "CONFIRMED_KR" }],
  [787, { nameCn: "里溯源学者", nameKr: "인오리진 학자", status: "CONFIRMED_KR" }],
  [788, { nameCn: "深海魔法师", nameKr: "심해의 마법사", status: "CONFIRMED_KR" }],
  [789, { nameCn: "深海复仇者", nameKr: "심해의 복수자", status: "CONFIRMED_KR" }],
  [790, { nameCn: "创梦者", nameKr: "꿈을 창조하는 자", status: "CONFIRMED_KR" }],
  [791, { nameCn: "遂梦之誓", nameKr: "꿈을 이루는 서약", status: "CONFIRMED_KR" }],
  [792, { nameCn: "公会新人", nameKr: "길드 신입", status: "CONFIRMED_KR" }],
  [793, { nameCn: "星灵魔导士", nameKr: "성령 마도사", status: "CONFIRMED_KR" }],
  [794, { nameCn: "星灵衣之主", nameKr: "스타드레스의 주인", status: "CONFIRMED_KR" }],
  [795, { nameCn: "灾厄之源", nameKr: "재앙의 근원", status: "CONFIRMED_KR" }],
  [796, { nameCn: "逆命之蝶", nameKr: "운명을 거스르는 나비", status: "CONFIRMED_KR" }],
  [797, { nameCn: "庇灵之誓言", nameKr: "수호령의 서약", status: "CONFIRMED_KR" }],
  [801, { nameCn: "修士", nameKr: "클레릭", status: "CONFIRMED_KR" }],
] as const;
