'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const rows=d=>Array.isArray(d)?d:(d.records||[]);
const errors=[];
const b0=read('data/contracts/hero-exclusive-equipment-relation-scope-contract.v1.json');
const b1=read('data/contracts/hero-exclusive-equipment-relation-source-contract.v1.json');
const b2=read('data/validation/hero-exclusive-equipment-relation-stageB2-fixture-summary.v1.json');
const h52v=read('data/validation/hero-page-stage5-2-final.v1.json');
const heroes=rows(read('data/hero-name-master.v1.json'));
const heroIds=new Set(heroes.map(x=>Number(x.heroId)));
const acq=rows(read('data/generated/equipment_stage2_7_acquisition.json')).filter(x=>x.acquisitionClass==='exclusive-equipment');
const exIds=new Set(acq.map(x=>Number(x.equipmentId)));
const source=rows(read('data/generated/hero-page-stage5-2-exclusive-central.v1.json'));
if(b0.stage!=='B-0'||b0.status!=='FROZEN')errors.push('B-0 not frozen');
if(b1.stage!=='B-1'||b1.status!=='FROZEN')errors.push('B-1 not frozen');
if(b2.stage!=='B-2'||b2.status!=='PASS'||b2.completion!=='COMPLETE')errors.push('B-2 not complete');
if(h52v.status!=='PASS'||h52v.completion!=='COMPLETE')errors.push('Hero 5-2 upstream not complete');
if(heroes.length!==267||heroIds.size!==267)errors.push('Hero master must be 267 unique IDs');
if(acq.length!==167||exIds.size!==167)errors.push('Exclusive population must be 167 unique IDs');
if(source.length!==267)errors.push('Hero 5-2 source must contain 267 rows');
const edges=[],seenPair=new Set(),seenEq=new Set(),seenHero=new Set();
let leak=0,unknownHero=0,resolverMismatch=0,ownerMismatch=0,dupPair=0,dupEq=0,multiHero=0;
for(const r of source){
 const x=r.exclusiveEquipment;if(!x||x.status!=='RELEASED')continue;
 const heroId=Number(r.heroId),equipmentId=Number(x.equipmentId),ownerHeroId=Number(x.ownerHeroId);
 if(!heroIds.has(heroId))unknownHero++;
 if(!exIds.has(equipmentId)||x.acquisitionClass!=='exclusive-equipment')leak++;
 if(x.ownerResolver!=='ConfigDataEquipmentInfo.SkillHero')resolverMismatch++;
 if(ownerHeroId!==heroId)ownerMismatch++;
 const pk=`${heroId}:${equipmentId}`;if(seenPair.has(pk))dupPair++;seenPair.add(pk);
 if(seenEq.has(equipmentId))dupEq++;seenEq.add(equipmentId);
 if(seenHero.has(heroId))multiHero++;seenHero.add(heroId);
 edges.push({heroId,equipmentId,relationType:'exclusive',provenance:[{sourceKind:'EQUIPMENT_SKILL_HERO',table:'ConfigDataEquipmentInfo',recordId:equipmentId,field:'SkillHero',value:ownerHeroId}],verificationStatus:'VERIFIED'});
}
edges.sort((a,b)=>a.heroId-b.heroId||a.equipmentId-b.equipmentId);
const unmapped=[...exIds].filter(id=>!seenEq.has(id)).sort((a,b)=>a-b);
for(const [label,value] of Object.entries({leak,unknownHero,resolverMismatch,ownerMismatch,dupPair,dupEq,multiHero}))if(value)errors.push(`${label}=${value}`);
if(edges.length!==167)errors.push(`edges=${edges.length}`);
if(seenEq.size!==167)errors.push(`mappedEquipment=${seenEq.size}`);
if(unmapped.length)errors.push(`unmapped=${unmapped.length}`);
const summary={canonicalHeroCount:heroes.length,exclusiveEquipmentCount:acq.length,canonicalEdgeCount:edges.length,mappedExclusiveEquipmentCount:seenEq.size,uniqueOwnerHeroCount:seenHero.size,unmappedExclusiveEquipmentCount:unmapped.length,duplicatePairCount:dupPair,multiOwnerEquipmentCount:dupEq,multipleEquipmentHeroCount:multiHero,excludedEquipmentLeakCount:leak,unknownHeroIdCount:unknownHero,ownerResolverMismatchCount:resolverMismatch,ownerHeroMismatchCount:ownerMismatch,heuristicEdgeCount:0,hardErrorCount:errors.length};
const output={version:1,stage:'B-3',relation:'HeroExclusiveEquipmentOwnership',status:errors.length?'FAIL':'COMPLETE',sourcePolicy:'Only the frozen 167 exclusive-equipment population is admitted. Ownership is the already validated ConfigDataEquipmentInfo.SkillHero relation preserved by Hero Stage 5-2; no general-equipment or heuristic inference is allowed.',sources:['data/contracts/hero-exclusive-equipment-relation-scope-contract.v1.json','data/contracts/hero-exclusive-equipment-relation-source-contract.v1.json','data/validation/hero-exclusive-equipment-relation-stageB2-fixture-summary.v1.json','data/hero-name-master.v1.json','data/generated/equipment_stage2_7_acquisition.json','data/generated/hero-page-stage5-2-exclusive-central.v1.json','data/validation/hero-page-stage5-2-final.v1.json'],summary,records:edges};
const validation={version:1,stage:'B-3',checkpoint:'full-canonical-ownership-generation',status:errors.length?'FAIL':'PASS',completion:errors.length?'BLOCKED':'COMPLETE',generatedArtifact:'data/generated/hero-exclusive-equipment-relations.v1.json',generationMode:'REUSE_VALIDATED_SKILLHERO_CHECKPOINT',authoritativeProvenance:'ConfigDataEquipmentInfo.SkillHero',summary,unmappedExclusiveEquipmentIds:unmapped,hardErrors:errors,cardinalityObservation:{uniqueOwnerHeroCount:seenHero.size,heroesWithMultipleExclusiveEquipment:multiHero,equipmentWithMultipleOwners:dupEq,frozenAsInvariant:false,boundary:'B-4 owns cardinality freeze.'},nextStage:'B-4 full relation validation and cardinality freeze',decision:errors.length?'B-3 BLOCKED':'B-3 PASS / COMPLETE; proceed to B-4 without reopening B-1/B-2.'};
fs.mkdirSync(path.join(root,'data/generated'),{recursive:true});fs.mkdirSync(path.join(root,'data/validation'),{recursive:true});
fs.writeFileSync(path.join(root,'data/generated/hero-exclusive-equipment-relations.v1.json'),JSON.stringify(output,null,2)+'\n');
fs.writeFileSync(path.join(root,'data/validation/hero-exclusive-equipment-relation-stageB3-summary.v1.json'),JSON.stringify(validation,null,2)+'\n');
console.log(JSON.stringify(validation,null,2));if(errors.length)process.exitCode=1;
