'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG = path.join(ROOT, 'data', 'configdata');
const OUT = path.join(ROOT, 'data', 'validation', 'hero-display-stat-investigation.v1.json');
const JOB_LINKS = path.join(ROOT, 'data', 'generated', 'hero-job-links.v1.json');

const SOURCE_FILES = [
  'ConfigDataHeroInfo.json','ConfigDataJobInfo.json','ConfigDataJobConnectionInfo.json','ConfigDataJobLevelInfo.json','ConfigDataSkillInfo.json','ConfigDataPropertyModifyInfo.json','ConfigDataHeroStarInfo.json','ConfigDataSoldierInfo.json',
];
const RELEVANT_KEY = /(soldier|army|troop|cmd|rate|ratio|modify|modifier|correction|talent|star|skill|job|hp|health|life|atk|attack|magic|int|def|dex|master|property)/i;
const STAT_KEYS = ['HP','AT','Magic','DF','MagicDF','DEX'];
const MASTERY_PROPERTY_ID_TO_STAT = {87:'HP',88:'AT',89:'DF',90:'Magic',91:'MagicDF',92:'DEX'};
const NAMED_HERO_TERMS = ['夜叉王凯','修罗王秋亚人','迦楼罗王力伽','利昂','马修','格尼尔','艾梅达'];

function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function writeJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`);}
function recordsOf(value){if(Array.isArray(value))return value;if(Array.isArray(value?.records))return value.records;if(Array.isArray(value?.Data))return value.Data;return [];}
function idOf(record){if(!record||typeof record!=='object')return null;for(const key of ['ID','Id','id','Hero_ID','HeroID','HeroId','heroId'])if(Number.isInteger(record[key]))return record[key];return null;}
function uniqueIntegers(values){return [...new Set(values.filter(Number.isInteger))].sort((a,b)=>a-b);}
function arraysEqual(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>v===b[i]);}
function histogram(values){const map=new Map();for(const value of values)map.set(String(value),(map.get(String(value))||0)+1);return Object.fromEntries([...map.entries()].sort((a,b)=>Number(a[0])-Number(b[0])));}

function summarizeSource(filename){
  const file=path.join(CONFIG,filename);if(!fs.existsSync(file))return{filename,status:'missing'};
  try{const raw=readJson(file);if(raw&&!Array.isArray(raw)&&Array.isArray(raw.m_bytes))return{filename,status:'legacy-textasset',recordCount:null,rootKeys:Object.keys(raw)};const records=recordsOf(raw);const keyCounts=new Map();for(const record of records){if(!record||typeof record!=='object'||Array.isArray(record))continue;for(const key of Object.keys(record))keyCounts.set(key,(keyCounts.get(key)||0)+1);}const keys=[...keyCounts.keys()].sort();return{filename,status:records.length?'direct-json':'empty-or-unknown-shape',recordCount:records.length,rootType:Array.isArray(raw)?'array':typeof raw,keys,relevantKeys:keys.filter(k=>RELEVANT_KEY.test(k)),keyPresence:Object.fromEntries(keys.map(k=>[k,keyCounts.get(k)])),records};}catch(error){return{filename,status:'invalid-json',error:error instanceof Error?error.message:String(error)};}
}
function compactSource(source){const{records,...summary}=source;return summary;}
function indexById(records){const map=new Map();for(const record of records||[]){const id=idOf(record);if(Number.isInteger(id)&&!map.has(id))map.set(id,record);}return map;}
function relevantProjection(record){if(!record||typeof record!=='object')return null;const out={};for(const[key,value]of Object.entries(record)){if(['ID','Id','id','Name','Name_Eng','Desc','DescStrKey'].includes(key)||RELEVANT_KEY.test(key))out[key]=value;}return out;}
function findArrayFields(record,matcher){const found={};if(!record||typeof record!=='object')return found;for(const[key,value]of Object.entries(record))if(matcher.test(key)&&Array.isArray(value))found[key]=value;return found;}
function fullStatProjection(record){if(!record)return null;const out={ID:idOf(record),JobLevelUpHeroLevel:record.JobLevelUpHeroLevel??null,rank_code:record.rank_code??null};for(const stat of STAT_KEYS){out[`${stat}_INI`]=record[`${stat}_INI`]??null;out[`${stat}_UP`]=record[`${stat}_UP`]??null;}return out;}
function masteryRewards(job){const rewards=[];for(let i=1;i<=3;i++){const propertyId=job?.[`Property${i}_ID`];const value=job?.[`Property${i}_Value`];if(Number.isInteger(propertyId)&&Number.isFinite(value)&&propertyId!==0&&value!==0)rewards.push({propertyId,stat:MASTERY_PROPERTY_ID_TO_STAT[propertyId]||null,value});}return rewards;}
function masteryTotalsForLink(link,jobIndex){const totals=Object.fromEntries(STAT_KEYS.map(k=>[k,0]));const jobs=[];for(const jobId of uniqueIntegers((link?.connections||[]).map(x=>x.jobId))){const job=jobIndex.get(jobId);if(!job)continue;const rewards=masteryRewards(job);for(const reward of rewards)if(reward.stat)totals[reward.stat]+=reward.value;jobs.push({jobId,name:job.Name??null,rank:job.Rank??null,rewards});}return{totals,jobs};}
function heroNameValues(record){return Object.entries(record||{}).filter(([key,value])=>typeof value==='string'&&/(name|title)/i.test(key)).map(([key,value])=>({key,value}));}

function main(){
  const sources=SOURCE_FILES.map(summarizeSource),byName=new Map(sources.map(s=>[s.filename,s]));const required=['ConfigDataHeroInfo.json','ConfigDataJobInfo.json','ConfigDataJobConnectionInfo.json','ConfigDataJobLevelInfo.json','ConfigDataSkillInfo.json'];const blocked=required.filter(name=>byName.get(name)?.status!=='direct-json');if(blocked.length){writeJson(OUT,{version:5,stage:'4-final-gates-investigation',status:'SOURCE_BLOCKED',blocked,sourceSummary:sources.map(compactSource)});process.exitCode=2;return;}
  const links=readJson(JOB_LINKS),linkRecords=Array.isArray(links?.records)?links.records:[],playableIds=new Set(linkRecords.map(x=>x.heroId).filter(Number.isInteger));const fixtureHeroIds=uniqueIntegers([1,3,4,5,6,7,8,9,...linkRecords.slice(0,8).map(x=>x.heroId)]);
  const heroRecords=byName.get('ConfigDataHeroInfo.json').records,heroIndex=indexById(heroRecords),jobIndex=indexById(byName.get('ConfigDataJobInfo.json').records),connectionIndex=indexById(byName.get('ConfigDataJobConnectionInfo.json').records),jobLevelIndex=indexById(byName.get('ConfigDataJobLevelInfo.json').records),skillIndex=indexById(byName.get('ConfigDataSkillInfo.json').records);

  const namedHeroMatches=[];for(const record of heroRecords){const names=heroNameValues(record);const matches=NAMED_HERO_TERMS.filter(term=>names.some(item=>item.value.includes(term)));if(matches.length)namedHeroMatches.push({heroId:idOf(record),matches,names,record:relevantProjection(record)});}

  const cmdFields=[...new Set(heroRecords.flatMap(record=>Object.keys(record||{}).filter(key=>/Cmd_INI$/i.test(key))))].sort();const cmdRows=[];for(const link of linkRecords){const hero=heroIndex.get(link.heroId);if(!hero)continue;const raw=Object.fromEntries(cmdFields.map(key=>[key,Number.isFinite(hero[key])?hero[key]:0]));cmdRows.push({heroId:link.heroId,nameKr:link.nameKr,raw});}const cmdFieldStats=Object.fromEntries(cmdFields.map(key=>{const values=cmdRows.map(r=>r.raw[key]),nonzero=values.filter(v=>v!==0);return[key,{nonzeroCount:nonzero.length,min:nonzero.length?Math.min(...nonzero):0,max:nonzero.length?Math.max(...nonzero):0,distinct:uniqueIntegers(nonzero),notDivisibleBy100:nonzero.filter(v=>v%100!==0).slice(0,20)}];}));

  const talentRows=[];let connectionMismatchCount=0;for(const link of linkRecords){const hero=heroIndex.get(link.heroId);if(!hero)continue;const connectionIds=uniqueIntegers([link.primaryJobConnectionId,...(link.useableJobConnectionIds||[]),...(link.connections||[]).map(x=>x.jobConnectionId)]),arrays=connectionIds.map(id=>connectionIndex.get(id)?.TalentSkill_IDs).filter(Array.isArray),primary=connectionIndex.get(link.primaryJobConnectionId)?.TalentSkill_IDs||arrays[0]||[],allConnectionsAgree=arrays.every(arr=>arraysEqual(arr,primary));if(!allConnectionsAgree)connectionMismatchCount++;const initialStar=hero.Star,prefixThroughInitialAllSame=Number.isInteger(initialStar)&&initialStar>=1&&primary.length>=initialStar?primary.slice(0,initialStar).every(id=>id===primary[initialStar-1]):null;talentRows.push({heroId:link.heroId,nameKr:link.nameKr,initialStar,talentIds:primary,talentLength:primary.length,allConnectionsAgree,prefixThroughInitialAllSame});}
  const talentByInitialStar={};for(const star of uniqueIntegers(talentRows.map(r=>r.initialStar))){const rows=talentRows.filter(r=>r.initialStar===star);talentByInitialStar[star]={heroCount:rows.length,lengthHistogram:histogram(rows.map(r=>r.talentLength)),prefixThroughInitialAllSame:rows.filter(r=>r.prefixThroughInitialAllSame===true).length,prefixThroughInitialNotSame:rows.filter(r=>r.prefixThroughInitialAllSame===false).length,examples:rows.slice(0,8)};}

  const formulaHeroIds=new Set(fixtureHeroIds);for(const match of namedHeroMatches)if(Number.isInteger(match.heroId)&&playableIds.has(match.heroId))formulaHeroIds.add(match.heroId);const formulaFixtures=[],referencedTalentSkillIds=[];
  for(const heroId of [...formulaHeroIds].sort((a,b)=>a-b)){const link=linkRecords.find(x=>x.heroId===heroId)||null,hero=heroIndex.get(heroId)||null;if(!link||!hero)continue;const connectionIds=uniqueIntegers([...(link.connections||[]).map(x=>x.jobConnectionId),...(link.useableJobConnectionIds||[]),link.primaryJobConnectionId]),connections=connectionIds.map(id=>connectionIndex.get(id)).filter(Boolean);for(const record of connections)for(const value of Object.values(findArrayFields(record,/talent|skill/i)))for(const id of value)if(Number.isInteger(id))referencedTalentSkillIds.push(id);const mastery=masteryTotalsForLink(link,jobIndex),connectionDetails=(link.connections||[]).map(conn=>{const jc=connectionIndex.get(conn.jobConnectionId),job=jobIndex.get(conn.jobId),levels=(conn.jobLevelIds||[]).map(id=>jobLevelIndex.get(id)).filter(Boolean);return{jobConnectionId:conn.jobConnectionId,jobId:conn.jobId,jobName:job?.Name??conn.job?.nameCn??null,rank:job?.Rank??conn.job?.rank??null,talentSkillIds:jc?.TalentSkill_IDs??[],masteryRewards:masteryRewards(job),jobLevels:levels.map(fullStatProjection),finalJobLevel:levels.length?fullStatProjection(levels[levels.length-1]):null};});formulaFixtures.push({heroId,nameKr:link.nameKr,nameCn:link.nameCn??null,nameEn:link.nameEn??null,heroNames:heroNameValues(hero),initialStar:hero.Star,starArrays:Object.fromEntries(STAT_KEYS.map(k=>[k,hero[`${k}Star`]??[]])),cmdRaw:Object.fromEntries(cmdFields.map(key=>[key,Number.isFinite(hero[key])?hero[key]:0])),masteryTotals:mastery.totals,masteryJobs:mastery.jobs,connections:connectionDetails});}

  const talentSkillIds=uniqueIntegers(referencedTalentSkillIds),talentSkills=talentSkillIds.map(id=>{const record=skillIndex.get(id);return record?relevantProjection(record):{ID:id,missing:true};}),propertyModifyRecords=(byName.get('ConfigDataPropertyModifyInfo.json')?.records||[]).filter(r=>Number.isInteger(r.ID)&&r.ID>=65&&r.ID<=104);
  writeJson(OUT,{version:5,stage:'4-final-gates-investigation',status:'EVIDENCE_COLLECTED',purpose:'Direct-JSON evidence for remaining Stage 4 semantic gates; no final formula is promoted here.',sourceSummary:sources.map(compactSource),playableHeroCount:playableIds.size,namedHeroMatches,cmdEvidence:{fields:cmdFields,fieldStats:cmdFieldStats,fixtureRows:cmdRows.filter(r=>formulaHeroIds.has(r.heroId))},talentEvidence:{heroCount:talentRows.length,connectionMismatchCount,lengthHistogram:histogram(talentRows.map(r=>r.talentLength)),byInitialStar:talentByInitialStar,fixtureRows:talentRows.filter(r=>formulaHeroIds.has(r.heroId)),referencedTalentSkills:talentSkills},propertyModifyEvidence:propertyModifyRecords,formulaFixtures,gateStatus:{displayJobStats:'EVIDENCE_ONLY',heroSoldierModifiers:'EVIDENCE_ONLY',talentStarProgression:'EVIDENCE_ONLY'},safetyDecision:'No final arithmetic or selection rule is inferred in this diagnostic. Named fields, distributions, mappings, and representative records are emitted for evidence-backed validation.'});console.log(`EVIDENCE_COLLECTED: ${OUT}`);console.log(`playable=${playableIds.size} namedMatches=${namedHeroMatches.length} formulaFixtures=${formulaFixtures.length} cmdFields=${cmdFields.join(',')} talentConnectionMismatches=${connectionMismatchCount}`);
}
main();
