'use strict';

const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..'),DATA=path.join(ROOT,'data');
const C=path.join(DATA,'contracts','hero-soldier-command-final.v1.json'),I0=path.join(DATA,'validation','hero-soldier-command-integration-i0-f.v1.json');
const N2=path.join(DATA,'generated','hero-soldier-command-base.v1.json'),S1=path.join(DATA,'generated','hero-sp-soldier-command-base.v1.json'),R5=path.join(DATA,'generated','hero-soldier-bond-command-contribution.v1.json'),ART=path.join(DATA,'generated','hero-soldier-command-modifiers.v1.json'),OUT=path.join(DATA,'validation','hero-soldier-command-modifiers-i2.v1.json');
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'));}function write(f,v){fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,`${JSON.stringify(v,null,2)}\n`,'utf8');}function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');}
function index(rows){const m=new Map();for(const r of rows||[]){const id=Number(r.heroId);if(!Number.isInteger(id)||m.has(id))throw new Error(`bad heroId ${r.heroId}`);m.set(id,r);}return m;}function eq(a,b){return JSON.stringify(a)===JSON.stringify(b);}function sum(a,b){return {hp:a.hp+b.hp,at:a.at+b.at,df:a.df+b.df,magicDf:a.magicDf+b.magicDf};}
function main(){const c=read(C),i0=read(I0),n2=read(N2),s1=read(S1),r5=read(R5),art=read(ART),errors=[];if(i0.status!==c.authority.integrationExpectedStatus)errors.push(`I0=${i0.status}`);const nm=index(n2.records),sm=index(s1.records),rm=index(r5.records),am=index(art.records);if(nm.size!==267||rm.size!==267||am.size!==267)errors.push(`normal/hero3/output counts ${nm.size}/${rm.size}/${am.size}`);if(sm.size!==25||art.spVariantCount!==25)errors.push(`SP counts ${sm.size}/${art.spVariantCount}`);
 let normalBaseMismatchCount=0,hero3MismatchCount=0,normalFinalMismatchCount=0,spEligibilityMismatchCount=0,spBaseMismatchCount=0,spFinalMismatchCount=0,sourceLabelMismatchCount=0;
 for(const [id,nrow] of nm){const rr=rm.get(id),out=am.get(id);if(!rr||!out){errors.push(`hero ${id} missing R5/output`);continue;}const h3=rr.contribution;if(!eq(out.normal?.base,nrow.base))normalBaseMismatchCount++;if(!eq(out.normal?.hero3Contribution,h3))hero3MismatchCount++;if(!eq(out.normal?.final,sum(nrow.base,h3)))normalFinalMismatchCount++;if(out.normal?.baseSource!=='N2_HEROINFO_HERO_OWNED_BASE')sourceLabelMismatchCount++;const eligible=sm.has(id);if(out.spEligible!==eligible||Boolean(out.sp)!==eligible)spEligibilityMismatchCount++;if(eligible){const sb=sm.get(id).base;if(!eq(out.sp?.base,sb))spBaseMismatchCount++;if(!eq(out.sp?.hero3Contribution,h3))hero3MismatchCount++;if(!eq(out.sp?.final,sum(sb,h3)))spFinalMismatchCount++;if(out.sp?.baseSource!=='S1_SPHEROINFO_REPLACEMENT_BASE')sourceLabelMismatchCount++;}}
 const fixtureResults={};for(const [name,f] of Object.entries(c.fixtures)){const r=am.get(f.heroId);fixtureResults[name]={normal:!!r&&eq(r.normal?.final,f.normalFinal),sp:!!r?.sp&&eq(r.sp.final,f.spFinal)};if(!fixtureResults[name].normal||!fixtureResults[name].sp)errors.push(`${name} fixture failed`);}
 for(const [k,v] of Object.entries({normalBaseMismatchCount,hero3MismatchCount,normalFinalMismatchCount,spEligibilityMismatchCount,spBaseMismatchCount,spFinalMismatchCount,sourceLabelMismatchCount}))if(v)errors.push(`${k}=${v}`);if(art.recordCount!==267)errors.push(`artifact recordCount=${art.recordCount}`);
 const result={version:1,stage:'I2',status:errors.length?'FAIL':'PASS',owner:'HERO_SOLDIER_COMMAND_FINAL_INDEPENDENT_VALIDATION',artifactOwner:art.semanticOwner,recordCount:am.size,spVariantCount:art.spVariantCount,normalBaseMismatchCount,hero3MismatchCount,normalFinalMismatchCount,spEligibilityMismatchCount,spBaseMismatchCount,spFinalMismatchCount,sourceLabelMismatchCount,fixtureResults,artifactSha256:sha(ART),hardErrors:errors,blockers:errors.length?['I2_VALIDATION_FAILED']:[],review:[]};write(OUT,result);console.log(JSON.stringify(result,null,2));if(errors.length)process.exitCode=1;}
main();
