/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment_.$equipmentId'
import { Route as EquipmentExclusiveRouteImport } from './routes/equipment_.exclusive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/equipment_/$equipmentId',
  path: '/equipment/$equipmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentExclusiveRoute = EquipmentExclusiveRouteImport.update({
  id: '/equipment_/exclusive',
  path: '/equipment/exclusive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/equipment': typeof EquipmentRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment/exclusive': typeof EquipmentExclusiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/equipment': typeof EquipmentRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment/exclusive': typeof EquipmentExclusiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/equipment': typeof EquipmentRoute
  '/equipment_/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment_/exclusive': typeof EquipmentExclusiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banners'
    | '/equipment'
    | '/equipment/$equipmentId'
    | '/equipment/exclusive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banners'
    | '/equipment'
    | '/equipment/$equipmentId'
    | '/equipment/exclusive'
  id:
    | '__root__'
    | '/'
    | '/banners'
    | '/equipment'
    | '/equipment_/$equipmentId'
    | '/equipment_/exclusive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannersRoute: typeof BannersRoute
  EquipmentRoute: typeof EquipmentRoute
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
  EquipmentExclusiveRoute: typeof EquipmentExclusiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment_/$equipmentId': {
      id: '/equipment_/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment_/exclusive': {
      id: '/equipment_/exclusive'
      path: '/equipment/exclusive'
      fullPath: '/equipment/exclusive'
      preLoaderRoute: typeof EquipmentExclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannersRoute: BannersRoute,
  EquipmentRoute: EquipmentRoute,
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
  EquipmentExclusiveRoute: EquipmentExclusiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
